### ISSUE TITLE
Broken design

### ISSUE THREAD

**Issue by diegoje** [videojs/http-streaming#100]
This morning I noticed that the videos on my site were all broken, as if a css file had not loaded. I then looked online and saw https://videojs.github.io/http-streaming/ also had the same problem I'm having.

I also saw VideoJS updated to version 7 - could this be the source of the problem?

<img width="915" alt="screen shot 2018-05-20 at 09 49 44" src="https://user-images.githubusercontent.com/16388805/40277213-2d322c66-5c13-11e8-9e6f-b61a6cc4cce5.png">

What could I do to go around this problem?

Thanks,
Diego

**Comment by gkatsev** [comment]
for some reason, it's missing the `video-js` class.

**Comment by diegoje** [comment]
Right, so I got this working by downloading previous versions.

Here's what I have now:
* video.js 6.9.0
* videojs-http-streaming 1.0.1

**Comment by gkatsev** [comment]
oh, looks like the missing video-js class broke as part of our IE8 removal work in vjs 7 (https://github.com/videojs/video.js/pull/5041). I'll take a look at this tomorrow.

**Comment by gkatsev** [comment]
Ah, figured out why it got through, in my local examples I was testing without having a class attribute at all but the VHS example has one.

**Comment by gkatsev** [comment]
I have a PR for this: https://github.com/videojs/video.js/pull/5194

**Comment by gkatsev** [comment]
The fix is live now, though, the unpkg url may be cached, so you may need to clear your cache

**Comment by diegoje** [comment]
Amazing - thank you!

**Comment by gkatsev** [comment]
You're welcome. Thanks for noticing :)
