### ISSUE TITLE
HLS Caching Issue

### ISSUE THREAD

**Issue by ishang3** [videojs/http-streaming#1008]
Briefly describe the issue.
We have been stuck on this issue where the player is requesting for old .ts files instead of the latest ones. As soon as we open the chrome developer tools and click "disable cache" then the server is receiving request. If not, then the browser is holding the old playlist.m3u8 chunk and requesting an old ts chunk file which by the time is already deleted - our server is holding a maximum of 15 chunk files. 

We are using this command to enable the node js apache webserver with cors and cache disabled:
http-server --cors -p 8080 -c -1

Do you have any ideas that we could use to solve this issue on the browser side?

### Browsers
what browsers are affected? please include browser and version for each
* Chrome

**Comment by Gregory-Gerard** [comment]
Did you tried to disable caching for m3u8 files in your server (Apache or Nginx)?

For example with nginx : `add_header Cache-Control no-cache; # Prevent caching of HLS fragments`
