### ISSUE TITLE
Video streaming not starting after loading a map

### ISSUE THREAD

**Issue by John2397** [videojs/http-streaming#1009]
So basically I'm currently using a library called mapbox-gl-js where a map is displayed on the screen.

I have a video element created dynamically and appears on top of the map, in which I want to stream a .m3u8 file.

The problem is that, if the video is created AFTER I load the map on the screen (that is, after the map.on('load'),.. function), it never starts.

But it starts correctly if I create the video element BEFORE the map loads.

[This is a JSFiddle](https://jsfiddle.net/hm1v2twz/) where video loads correctly when element is created before the map loading function.

[This is a JSFiddle](https://jsfiddle.net/hm1v2twz/1/) where video does NOT load correctly  when video element is created inside the map loading function (the element appears but never starts).

The strange thing is that the above problem does not occur if I use a .mp4 video instead of a .m3u8 one, so that's why I'm posting this issue here.

[This is a JSFiddle](https://jsfiddle.net/y8s5cmvz/1/) showing that there is no problem loading an mp4 video AFTER the map loading function.

I have also posted this issue on the mapbox-gl-js page on github, because I'm not sure whose problem is this, or if I'm doing something wrong and there is no problem at all.

**Comment by Gregory-Gerard** [comment]
Your video tag is created in an eventListener (map onload), after video.js is loaded. So you need to manually setup your video with video.js by adding `videojs('#my_video')` after adding video tag to DOM.

Here is an working example of your code : https://jsfiddle.net/qmu9zt7j/

**Comment by John2397** [comment]
Thank you a lot!
