### ISSUE TITLE
HLS Event playback freezes on seek event

### ISSUE THREAD

**Issue by drajvver** [videojs/http-streaming#1012]
## Description
I have an event playlist that has been left after finishing the live stream. It is 5:35hrs long. Whenever I seek some time forward, to 2:45:00 for example it loads fine and plays back the video. But when after that I will seek back to, for example 1:24:00 I can still see the player loading all the .ts files in network tab, but player itself is stuck in the buffering mode with spinning wheel. Pausing and clicking play again fixes this problem.
The player essentially gets stuck in the 'seeking' event, never recovering from it. 'seeking' event is the last one that player emits before I have to recover it manually.
All my HLS playlists are created by NGINX RTMP and FFMPEG, nothing more. Keyframes are set to 2s, 25fps.

JSBin: https://jsbin.com/nenuwelaho/2/edit?html,output

## Sources
I can't publish the exact source that has this happening, but most of my HLS playlist behave the same way. This one sometimes has the same issue: https://b-zone.nowstorage.cloud/hls/f10663e2-625c-4638-7093-08d877356f68.m3u8
This is an abandoned LIVE playlist, but you can achieve the same effect as I described above.
It is not 100% consistent, but after a few seeks it will happen.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play the stream
2. Seek backwards (it should play fine, sometime it even hangs on 1st seek)
3. Seek backwards once again
4. Player should freeze, while still loading segments in the background.

### Expected
Video should seek to the clicked point and not freeze.

### Error output
No errors in console.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming ?.?.? (it's the one bundled with VJS 7.10.2)

### videojs version
what version of videojs does this occur with?
video.js 7.10.2

### Browsers
what browsers are affected? please include browser and version for each
* Any browser that uses non-native HLS

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* All (?)

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* No plugins

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* No additional JS

**Comment by gkatsev** [comment]
Far seeks are definitely an issue that we have. What can cause this issue is if the segment durations are much different from the target duration and if the actual segment durations are off from the duration in the manifest. This is because we make a guess based on the information in the manifest and our guess can be wrong if the segment is say 1.99s long but in the manifest it is 2s because over hundreds of segments, that .01s can add up for us to guess a wildly incorrect segment, and we sometimes fail to recover from this.

**Comment by ryankashi** [comment]
I am getting this same issue - I see the following error inside of my console:

`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. `

If I try to seek my video, however, I am still able to seek:

`player.currentTime(120)`

After seeking, I am able to pause and play via the console as expected although the UI no longer shows (i.e. fullscreen button or volume slider) In addition, after doing that, I continually get the warning:

`VIDEOJS: WARN: We received no playlist to switch to. Please check your stream.`

I don't know if this may help somebody who is more familiar with how everything works for the player? This is with videojs 7.x.x

**Comment by gkatsev** [comment]
We've done various fixes to far seeks since the issue has been opened. Can you re-test with latest Video.js or https://videojs-http-streaming.netlify.app/ and report back? If possible, could you provide a new source if you are still able to reproduce the issue?
