### ISSUE TITLE
Player delays when unmuting on iOS 14.2

### ISSUE THREAD

**Issue by javanone** [videojs/http-streaming#1017]
## Description
When unmuting a video on a device (iPhone, iPad) running iOS 14.2, the video pauses or delays briefly before continuing. On a device with iOS 13.7 or 14.1, this does not occur. Here is [a link to a HLS demonstration on stackblitz.](https://hls-test.stackblitz.io/) Or, [you can click here to view the demo in GitHub](https://github.com/javanone/hls-test/tree/master).
The demo has a HLS Live and HLS VOD example. The delay is more notable on the HLS Live example.

## Steps to reproduce

1. Play an HLS Video on an iPhone/iPad with iOS 14.2 (Browser doesn't seem to matter - tested with Safari, Chrome, and Firefox)
2. Mute the video
3. Unmute the video - it will have a slight delay. 

### Expected
On a Windows or Mac computer, or on an Apple Device with an older iOS, unmuting the video doesn't cause a delay of any kind.

### videojs version
Project is using 7.10.2

### Browsers
Chrome, Safari, Firefox

### Platforms
iPhone/iPad with iOS 14.2

**Comment by jienco** [comment]
I have seen the exact same issue. Wondering if there are any plans to fix it

**Comment by gkatsev** [comment]
Issues like these are often related to OS level changes and often fix themselves in a subsequent issue.
