### ISSUE TITLE
Parsing custom ms3u8 playlist

### ISSUE THREAD

**Issue by pabloVoorvaart** [videojs/http-streaming#1019]
Hello,

I have a playlist like looks like this:

    #EXTM3U
    #EXT-X-ERROR: Stream open failed
    #EXT-X-ENDLIST

#EXT-X-ERROR is a custom tag implemented by the CDN and so videojs wont identify this playlist as an error and will not fail.

So I need a way to check the playlist loaded is not error. I was thinking of implementing a small parser function every time a request is made in [http-streaming/src/xhr.js](https://github.com/videojs/http-streaming/blob/master/src/xhr.js)
    ​

But I don't know if this is an optimal way to do it.

Regards, Pablo.

**Comment by gkatsev** [comment]
I think you want to look at our custom tag parser option: https://github.com/videojs/http-streaming#customtagparsers. See https://github.com/videojs/m3u8-parser#custom-parsers

**Comment by pabloVoorvaart** [comment]
Hey @gkatsev thanks for answering.

yes I think this is what I want, but how do I extract the playlist data? 

Is there some kind of event that is triggered every time the player fetches the playlist? 

Can I hook into the xhr request the player makes? 

Regards, Pablo.

**Comment by gkatsev** [comment]
You can likely peek behind the scenes at the playlist via `player.tech().vhs.playlists.media()`.
As for XHR, our only recommended way hook is `beforeRequest`, though, you can override `xhr` but we don't recommend it. See https://github.com/videojs/http-streaming#vhsxhr.
