### ISSUE TITLE
Video js cannot play HLS stream with which VLC and Plyr has not problem

### ISSUE THREAD

**Issue by walec51** [videojs/http-streaming#1020]
## Description
Stops playing at beginning with error:

```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Video found in segment when we expected only audio. We can't switch to a stream with video from an audio only stream. To get rid of this message, please add codec information to the manifest. Switching to another playlist.
```

## Steps to reproduce

https://codepen.io/walec51/pen/KKgVKew

### Expected
Play the stream. VLC and Plyr had no problem with opening

https://cdn3.wowza.com/2/amtleCs5MHlKamdX/YmtOQ242/hls/vyzpcz8d/playlist.m3u8

### Actual
Stopped with error after first second

### Error output

version 7.6.0
```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Video found in segment when we expected only audio. We can't switch to a stream with video from an audio only stream. To get rid of this message, please add codec information to the manifest. Switching to another playlist.
```

version 7.11.0

```
MEDIA_ERR_DECODE
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.0 and 7.11.0
#### browsers
probably all, tested on Firefox and Chrome
#### OSes
tested on Windows 10
### plugins
plain video js

**Comment by gkatsev** [comment]
Looks like that zero-length segment at the beginning of the video is tripping us up for some reason. Is that something you're able to change?
Looks like that segment includes only audio and no video as well as no i-frames which would cause issues.

**Comment by walec51** [comment]
I em not able to change it on the server side as this is a playlist generated by Wowza Media Cloud. I've also reported a support ticket to them as this is probably an issue from both sides - the first segment from Wowza is useless however in the realm of the HLS protocol so Video JS should handle it as other players do.

**Comment by gkatsev** [comment]
It's likely something that we should handle. Unfortunately, this is the first time we've seen this issue, and we're pretty busy with a bunch of other playback issues, so, it may be awhile before we're able to get to this.
