### ISSUE TITLE
experimentalBufferBasedABR HLS: type errors over slow connections

### ISSUE THREAD

**Issue by blacktrash** [videojs/http-streaming#1025]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.
[minimal demo](https://blacktrash.org/test/videojs/exabr.html)
(the official demos do not load 7.11.0)
When connection is slow at each load of a variant HLS playlist an error is thrown; see below.

## Sources
I have not encountered a source where this doesn't happen (might work w/o a master, but then there is no ABR).

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. enable experimentalBufferBasedABR
2. throttle connection to something like slow 2G or similar so that a down switch on load is needed
3. start playback

### Expected
There should be no errors, instead the down switch warning should appear (it does not in this case)

### Error output
```
Uncaught TypeError: master is undefined
    simpleSelector https://blacktrash.org/test/videojs/video-7.11.0.js:50117
    movingAverageBandwidthSelector https://blacktrash.org/test/videojs/video-7.11.0.js:50296
    checkABR_ https://blacktrash.org/test/videojs/video-7.11.0.js:57170
    abrTimer_ https://blacktrash.org/test/videojs/video-7.11.0.js:57188
    setInterval handler*startABRTimer_ https://blacktrash.org/test/videojs/video-7.11.0.js:57187
    MasterPlaylistController https://blacktrash.org/test/videojs/video-7.11.0.js:57131
    src https://blacktrash.org/test/videojs/video-7.11.0.js:60160
    handleSource https://blacktrash.org/test/videojs/video-7.11.0.js:60617
    setSource https://blacktrash.org/test/videojs/video-7.11.0.js:12026
    Html5 https://blacktrash.org/test/videojs/video-7.11.0.js:21418
    loadTech_ https://blacktrash.org/test/videojs/video-7.11.0.js:24505
    src_ https://blacktrash.org/test/videojs/video-7.11.0.js:26836
    src https://blacktrash.org/test/videojs/video-7.11.0.js:26783
    setSourceHelper https://blacktrash.org/test/videojs/video-7.11.0.js:12391
    setSourceHelper https://blacktrash.org/test/videojs/video-7.11.0.js:12393
    setSource https://blacktrash.org/test/videojs/video-7.11.0.js:12132
    timeoutId https://blacktrash.org/test/videojs/video-7.11.0.js:4684
    setTimeout handler*setTimeout https://blacktrash.org/test/videojs/video-7.11.0.js:4679
    setSource https://blacktrash.org/test/videojs/video-7.11.0.js:12131
    src https://blacktrash.org/test/videojs/video-7.11.0.js:26775
    MediaLoader https://blacktrash.org/test/videojs/video-7.11.0.js:12615
    addChild https://blacktrash.org/test/videojs/video-7.11.0.js:3770
    handleAdd https://blacktrash.org/test/videojs/video-7.11.0.js:3902
    initChildren https://blacktrash.org/test/videojs/video-7.11.0.js:3951
    Player https://blacktrash.org/test/videojs/video-7.11.0.js:23845
    videojs$1 https://blacktrash.org/test/videojs/video-7.11.0.js:29347
    <anonymous> https://blacktrash.org/test/videojs/exabr.html:31
```

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming packed with vjs 7.11.0

### videojs version
what version of videojs does this occur with?
video.js 7.11.0

**Comment by gkatsev** [comment]
Thanks! I had just noticed this issue the other day too. Thankfully, it seems like it doesn't cause any issues beyond just a warning. I'll make a PR for it.

Also, have you been testing the new ABR stuff? How is it looking on your end?

**Comment by blacktrash** [comment]
> Thanks! I had just noticed this issue the other day too. Thankfully, it seems like it doesn't cause any issues beyond just a warning. I'll make a PR for it.

Great. Thank you.

> Also, have you been testing the new ABR stuff? How is it looking on your end?

I had just started testing - not technically, just viewing - when I was a bit side-tracked by narrowing down this 'error'. So I haven't felt big differences yet. - Also not for the worse though ;-)

**Comment by gkatsev** [comment]
We'll get it into a Video.js release soon. Please let us know how it works for you as you get more time to test with it!

> Also not for the worse though ;-)

That's what I like to hear 🙂
