### ISSUE TITLE
Audio stream stalls after first segment in latest http-streaming but not legacy video-contrib-hls

### ISSUE THREAD

**Issue by cazzerson** [videojs/http-streaming#1034]
## Description

I'm working on an CloudFront-backed HLS A/V streaming player using video.js and are finding that while our video resources stream just fine, the audio resources stop playing (and is stuck on an infinite loading spinner) after the first (~7s) segment.

Interestingly, while I'm able to reproduce this on the [newer RC demo](https://videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fd171yf8pzr8938.cloudfront.net%2F12002_C0016_0001-playlist.m3u8&type=&keysystems=&buffer-water=false&override-native=true), it works fine on the [older video-contrib-hls demo](https://videojs.github.io/videojs-contrib-hls/). 

It also works fine in video.js 7.9.7.

## Sources

An example playlist URL is `https://d171yf8pzr8938.cloudfront.net/12002_C0016_0001-playlist.m3u8`. 

## Steps to reproduce

1. Visit [newer RC demo with example playlist loaded](https://videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fd171yf8pzr8938.cloudfront.net%2F12002_C0016_0001-playlist.m3u8&type=&keysystems=&buffer-water=false&override-native=true)
2. Press play
3. Wait ~7 seconds and it should stop playing
4. Visit [older video-contrib-hls demo](https://videojs.github.io/videojs-contrib-hls/)
5. Load example playlist `https://d171yf8pzr8938.cloudfront.net/12002_C0016_0001-playlist.m3u8`
6. Press play and it should continue to stream the content beyond the first ~7 seconds

### Expected

The player should stream the entire resource.

### Error output

In our player, I'm seeing `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.` in the Chrome dev console, but I see the same behavior in the RC player without that error message in the console.

### videojs-http-streaming version

videojs-http-streaming >=2.2.4

### videojs version

video.js >=7.10.0

### Browsers

* Chrome 87
* Firefox 83

### Platforms

* Reproduced on recent versions of macOS and Windows in multiple browsers

### Other Plugins

* n/a

### Other JavaScript

* n/a

**Comment by cazzerson** [comment]
Just an update after working on this some more. The audio stream works in video.js `7.9.7`, but not in `>=7.10.0` (i.e. http-streaming `>=2.2.3`).

**Comment by brandonocasey** [comment]
Just submitted a fix for this issue, would you mind if we hosted your content on our end for testing in the future?

**Comment by cazzerson** [comment]
Thank you! Also just wanted to note that we talked about the test content on Slack.
