### ISSUE TITLE
BufferBasedABR + log.debug spams console

### ISSUE THREAD

**Issue by phloxic** [videojs/http-streaming#1041]
## Description

When enabling `experimentalBufferBasedABR` and `videojs.log.level('debug')` the console is spammed with debug messages.
https://videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fe3e2p5m2.ssl.hwcdn.net%2Fhls%2Fmain.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=true&override-native=true

## Sources
Is a certain source or a certain segment affected?

No.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Go to https://videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fe3e2p5m2.ssl.hwcdn.net%2Fhls%2Fmain.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=true&override-native=true
2. open console, tons of repeated message (especially at the outset, while buffering?) like the following:

```
VIDEOJS: DEBUG: VHS: MPC > allowing switch 2-/hls/360p/playlist.m3u8 -> 2-/hls/360p/playlist.m3u8 as current playlist is live video.core.js:84:49
VIDEOJS: DEBUG: VHS: PlaylistSelector > choosing {"id":"2-/hls/360p/playlist.m3u8","bandwidth":912767,"width":640,"height":360,"codecs":"avc1.4D0028,mp4a.40.2"} using resolutionPlusOneRep with options 
Object { bandwidth: 4194304, width: 640, height: 264, limitRenditionByPlayerDimensions: true }
video.core.js:84:49
VIDEOJS: DEBUG: VHS: MPC > allowing switch 2-/hls/360p/playlist.m3u8 -> 2-/hls/360p/playlist.m3u8 as current playlist is live video.core.js:84:49
VIDEOJS: DEBUG: VHS: PlaylistSelector > choosing {"id":"2-/hls/360p/playlist.m3u8","bandwidth":912767,"width":640,"height":360,"codecs":"avc1.4D0028,mp4a.40.2"} using resolutionPlusOneRep with options 
Object { bandwidth: 4194304, width: 640, height: 264, limitRenditionByPlayerDimensions: true }
video.core.js:84:49
```

### Expected

The flood of message should be stemmed to a certain degree. Ideally by catching repeated messages, and reporting something like: "last message repeated x times".

Detecting (and ability to copy) relevant messages can be done to a certain extent by clever filtering or turning off debug level and then inspecting `log.history()`, but part of debugging is arguably stumbling over the unexpected which cannot be filtered for.

More importantly, I observed, certainly with several players on the page, that this affects player behaviour from sluggish to slightly erratic. The latter kind of defeats the purpose of debugging.

Further observation:  message interval is especially short after initializing the player. But it can't really be related to buffering because this happens also when `preload` is set to `none`.

Obviously this issue is not crucial functionality-wise, but makes it hard to explore the experimental feature in depth and give feedback.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
Recent video.js offering buffer based ABR.

**Comment by gkatsev** [comment]
That makes sense though, I'm not exactly sure it's possible to limit these. Maybe we'd want to log these in an even higher log level instead, like log level ridiculous or something and then in debug log only log when there was a change or something.

**Comment by gkatsev** [comment]
Basically, the logs are pretty simplistic, and basically just pipe what they're given to console.log/warn/error. Trying to be clever with them will just add a lot of unnecessary complexity.

**Comment by blacktrash** [comment]
I understand, and I certainly did not intend to encourage more log complexity. Although the log _is_ a rather complex experience for the user in this scenario.

Other approach: Are these message (still) _needed_?

Are these repeated messages buffer based ABR specific? If yes, are/were they more important/intended for the _development_ of the feature, or were they meant as user facing? Can they be omitted now that the feature has been rolled out? Or when it sheds its experimental state? Are you/the player developers (still) inspecting these messages?

**Comment by gkatsev** [comment]
It is something that we still use. The logs aren't specific to the new option, they were around before. In fact, before you'll probably see a bunch of them at once and then a long pause and then a bunch of them at once instead of a having them often and regularly.
It does make sense for us to do something about this.

**Comment by blacktrash** [comment]
No worries. For my own purposes I can work around it. So no rush. I mainly wanted to point out that the logging overload potentially influences player behaviour, so feedback on the new feature may in turn tricky to disect.

**Comment by gkatsev** [comment]
Thanks, I hadn't even thought that the logging could cause an issue.
Video.js recently added a "debug" mode that can be enabled at runtime https://github.com/videojs/video.js/pull/6687. We should probably hook into that and not do any logging until debug logging is enabled. Then figure out a better way of logging these items, perhaps via a "ridiculous" log level.

**Comment by blacktrash** [comment]
I must be missing something, but neither setting the `debug` player option, nor sth. like `videojs.players.myplayer.debug(true)` seems to do anything. I need more coffee ;-)
But on the remote chance that I understand what this is supposed to do - turn on debug for a specific player(?) - this would ease things a lot already.

**Comment by brandonocasey** [comment]
The only way (i think to turn on debug logging is globally via `videojs.log.level('debug')`

**Comment by gkatsev** [comment]
Yeah, VHS doesn't use the new debug option currently. I'm saying we should :)

As @brandonocasey said, the way to do things right now is changing the log level. (Debug mode should potentially change the log level too if it doesn't currently)
