### ISSUE TITLE
Livestream with discontinuities not loading

### ISSUE THREAD

**Issue by apredoi** [videojs/http-streaming#1042]
## Description
We're unable to load live streams that have discontinuities on http-streaming > 2.0. This only happens in live mode and the video loads fine when we're no longer streaming.
Code sample:
https://jsbin.com/jawavucovo/1/edit?html,output
This video recording shows the stream loading fine in video.js 7.9.7 and http-streaming 1.13.4 but not on video.js 7.11.1 and http-streaming 2.4.2:
https://streamable.com/zv7ao8
## Sources
Here is the manifest even though it is no longer live, and at the time of reading loads fine:
Manifest URL: https://streamstage-eastus-1-streamstageeastus-usea.streaming.media.azure.net/0565333b-e3d0-4814-a42a-09c86185e2bd/5794c2a3-6293-47dc-9fee-b6f791e9cfa2.ism/Manifest(video,format=m3u8-aapl)
## Steps to reproduce
1. Start a livestream using OBS
2. Open a VPN connection
3. Wait for OBS to reconnect 
### Expected
The livestream should load as it did with the older version
### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.0.0+
### videojs version
what version of videojs does this occur with?
video.js 7.10+
### Browsers
what browsers are affected? please include browser and version for each
Presumably all, tested with:
* Firefox 84
* Brave 1.18.78 Chromium: 87.0.4280.141

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* MacOS 10.15.7
### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* No (see video)
### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* No (see video)

**Comment by gkatsev** [comment]
This could be related to broken PDT behavior we have. It's something we're actively working on right now.

**Comment by gkatsev** [comment]
Circling back on this one, I think we have this fixed in recent versions of VHS.
