### ISSUE TITLE
WebVTT subtitles are disabled if request is aborted while in waiting state

### ISSUE THREAD

**Issue by claudiah12** [videojs/http-streaming#1046]
## Description
I have an HLS video with WebVTT subtitles in the manifest, and noticed that at random points during playback the captions would be disabled with no user interaction. The subtitles track is being disabled by this [error handler for subtitles](https://github.com/videojs/http-streaming/blob/124834a2c219fbab2d9568bb9ad31f7003444353/src/media-groups.js#L249). The error appears to simply be triggered when a request is aborted while it's still in the waiting state, due to [this logic in vtt-segment-loader.js](https://github.com/videojs/http-streaming/blob/a29e241e6979ddd27ca6f7e2ff84bab1f4c7c450/src/vtt-segment-loader.js#L280), where a call to this.stopForError is made, even if the error is due to the request being aborted. 

The function will not trigger an error if this.pendingSegment_ does not exist, but it seems that if the request is "waiting" at the time of the abort call, this.pendingSegment_ will not be cleared ([source](https://github.com/videojs/http-streaming/blob/9919b85a6ec71b446a86887fcd5f2d8475ddf4ad/src/segment-loader.js#L666)), and an error will be triggered. The abort itself seems to be due to the bit rate changing during playback and triggering a mediachanging event, so it doesn't appear that there's actually a problem with streaming the subtitles.

Any insight in how to avoid getting in to this error state would be greatly appreciated! My instinct is that in vtt-segment-loader.js, `if (!this.pendingSegment_)` should actually be` if (error.code === REQUEST_ERRORS.ABORTED)` since the comment says that logic is just for when the request was aborted, but I'm not sure that I fully understand how error states are intended to work in relation to aborted requests.

## Sources
https://livectorprodmedia13-usso.licdn.com/1cb17cef-f4ee-4aec-93d8-ca67bed23ff2/L4E5db8b0c139c1b000-livemanifest.ism/manifest(format=m3u8-aapl)
However, I haven't been able to reproduce the error outside of our web app, and we haven't made the captions feature public yet so it's not available to test. I'm wondering though if the fact that our web app is making a lot of other requests simultaneously could make it more likely that a request is aborted while it's pending?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load the video
2. Turn on the captions

### Expected
Expect the captions to stay on for the whole video, but they become disabled at some point during playback.
Turning them back on manually works fine

### Error output
n/a

## Additional Information
Apologies for not being able to give real steps to reproduce since we haven't publicly launched our captions feature

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.3.0

### videojs version
what version of videojs does this occur with?
video.js 7.11.0

**Comment by gkatsev** [comment]
We'd have to look at this some more but it's very likely that's what's happening is that when an issue occurs we abort all the loaders but when the stream recovers we end up not restarting the vtt segment loader along with the other loaders.
I've added it to our backlog to investigate. But if you get the chance, it's possible this is happenings because we don't call load on the vtt segment loader here https://github.com/videojs/http-streaming/blob/b34a77063745eebd30bba4194f44ff2344cae63e/src/master-playlist-controller.js#L512-L517 (and potentially in similar places through the MPC)

**Comment by gkatsev** [comment]
Might be better to use `delegateLoaders_` instead of manually calling load on the individual loaders.
