### ISSUE TITLE
PlaybackWatcher's checkCurrentTime "waiting" on VizioTV incorrectly detects and recovers after 5 checks w/ no update to currentTime (some devices like these are less frequent at providing updates)

### ISSUE THREAD

**Issue by chwagssd** [videojs/http-streaming#1052]
https://github.com/videojs/http-streaming/blob/ad5c2704319d29971c5d50db04b16f3970df547a/src/playback-watcher.js#L265

- Vizio TV (Chromium 
- VideoJS 7.8.3
- @videojs/http-streaming 2.3.0
- @videojs/vhs-utils 2.2.1
- Tried with latest VideoJS but video playback does not work on Vizio TV 1/2 the time, but the same code `this.consecutiveUpdates >= 5` is in that branch, so condition will likely still exist

I'm using VideoJS w/ HLS on a Vizio TV. While I realize that doesn't get a lot of attention in testing, I wanted to point something out, which hopefully can get its own config options. Around discontinuities and rendition switching (stepping up from lower to higher bitrate TS pieces), the VizioTV enters into this state every single time, where VideoJS thinks it is "waiting" (even though no "waiting" event fires) because it hasn't received an update to `<HTMLVideo>.currentTime` after 5 consecutive checks.

I played around with this `if (this.consecutiveUpdates >= 5 && currentTime === this.lastRecordedTime)` and changed it to 10, and found that the the Vizio TV (50" and 24" running their version of Chromium) consistently gets to `this.consecutiveUpdates === 6` before reporting an update to the `player.currentTime()`. These devices only have 1 video decoder, and it seems like around discontinuities only this occurs, so the resulting behavior is

1. When switching renditions (i.e. when `enableLowInitialPlaylist===true`, normally happens after the 1st segment), the video player rewinds itself due to a call to `this.waiting_()`, and then proceeds as normal
2. In cases with discontinuities, such as the following playlist, it gets stuck on a repeating loop where it hits the discontinuity at 30.033 seconds, and then video visually freezes, but audio keeps rewinding/looping
   - [hls-freezes-at-30s.zip](https://github.com/videojs/http-streaming/files/5875048/hls-freezes-at-30s.zip)
   - Video of the behavior we see: https://photos.app.goo.gl/7YuoZADX6uQEhTf98

I want to request either (a) configuration option for something like `maxPlayheadStuckWaiting` in seconds, or (b) could the check be increased to 5? Perhaps a threshold based on the frequency of timeupdate events in the stats might provide a better auto-config than the static approach, but 5 is consistency too low, and I have been seeing this behavior for a long time.

**Comment by gkatsev** [comment]
Looks like that value has been 5 for about 5 years now. Though, increasing it a tiny bit is probably OK?
Alternatively, we can make it a Config item https://github.com/videojs/http-streaming/blob/main/src/config.js, which makes it configurable but still makes it something most users won't touch.
@gesinger @brandonocasey thoughts?

**Comment by gesinger** [comment]
I think a Config option would make sense for it. Maybe something like `CONSECUTIVE_TIMEUPDATES_BEFORE_WAITING`?

**Comment by brandonocasey** [comment]
An option or increasing it are both fine with me. I lean towards increasing the value so that things just work and we have less of users to configure 🤷🏻 .

**Comment by gkatsev** [comment]
> An option or increasing it are both fine with me. I lean towards increasing the value so that things just work and we have less of users to configure 🤷🏻 .

Yeah, that's why I was going with Config rather than a regular option, since it isn't documented and kind of "at your own risk" type of thing.
