### ISSUE TITLE
Manually method to add AES encrypted key to hls streaming

### ISSUE THREAD

**Issue by whatever1211** [videojs/http-streaming#1053]
## Description
Our system using encrypted AES m3u8.
To enforce the "base key" from server, we do one more time encrypt of "base key" on client side. But we don't know how to manually set the "new key" back to videojs.

Is there a way to manually add "new key" based on "base key" to videojs?
Or is there a way to interfere with the videojs key xhr and modify the response before videojs set encrypt key?

### Expected
Modify the response key from source uri, and set new key to videojs.

### videojs version
what version of videojs does this occur with?
video.js 7.8.4

**Comment by gkatsev** [comment]
You can modify request options with [`beforeRequest`](https://github.com/videojs/http-streaming#vhsxhr) but it's worth noting that this won't help you for Safari and iOS because we use native playback there and so `beforeRequest` won't run.

**Comment by jehazXu** [comment]
这个有人有替代方案吗
