### ISSUE TITLE
Can I get the missing frame information of the video?

### ISSUE THREAD

**Issue by mraiguo** [videojs/http-streaming#1061]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
https://jsbin.com/cababor/2/edit?html,output

As shown in the demo, the video is missing a lot of frames and each time it passes these points in time it triggers a seeking event (how do I distinguish between these seeking and manual seeking), I want to know the information about the missing frames

## Sources
https://v3-ws.zy.cetav.com.cn/65/video/17b0594b547a11eb96b8fa20200c3759/2e7c70ca6f60ec874729196de748abc0.1280.720.false/2e7c70ca6f60ec874729196de748abc0.1280.720.m3u8

## Steps to reproduce
1. Play this video
2. Listening to seeking events
3. Play for twenty seconds
 will see seeking event be triggered

**Comment by gkatsev** [comment]
What kind of information are you looking for?
