### ISSUE TITLE
Safari keeps lowest resolution playback with HLS livestream

### ISSUE THREAD

**Issue by tf-kevin** [videojs/http-streaming#1062]
## Description
Safari on macOS does not use the correct / highest resolution when playing back a HLS livestream. It always uses the lowest resolution that is available. 

## Sources

playlist.m3u8

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=750,RESOLUTION=426x240,CODECS="avc1.42c015,mp4a.40.2"
live_transcoder/live_9d16381e1d_240p/chunks.m3u8?nimblesessionid=2589
#EXT-X-STREAM-INF:BANDWIDTH=1700,RESOLUTION=854x480,CODECS="avc1.77.30,mp4a.40.2"
live_transcoder/live_9d16381e1d_480p/chunks.m3u8?nimblesessionid=2589
#EXT-X-STREAM-INF:BANDWIDTH=2500,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
live_transcoder/live_9d16381e1d_720p/chunks.m3u8?nimblesessionid=2589
#EXT-X-STREAM-INF:BANDWIDTH=3700,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2"
live_transcoder/live_9d16381e1d_1080p/chunks.m3u8?nimblesessionid=2589

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load the player with options below and a HLS livestream playlist
2. Play the stream and wait

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
videojs options:
`
autoplay: false,
muted: false,
            controls: true,
            aspectRatio: '16:9',
            language: 'de',
            liveui: true,
            responsive: true,
            html5: {
                vhs: {
                    withCredentials: false,
                    overrideNative: !videojs.browser.IS_SAFARI,
                    smoothQualityChange: true,
                    limitRenditionByPlayerDimensions: false,
                }
            }
`

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.2.4

### videojs version
what version of videojs does this occur with?
video.js 7.10.2

### Browsers
what browsers are affected? please include browser and version for each
* Safari (current versions)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* macOS

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* videojs-hls-quality-selector
* videojs-contrib-quality-levels

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* React

**Comment by gkatsev** [comment]
Safari plays back natively by default, and also in your case, since you don't set overrideNative, which we don't really recommend right now anyway.
What version of Safari are you using exactly? Is it 14? If so, I've noticed that it will limit the rendition selection to the player size, so, if your player dimensions are smallish, it'll only choose the smallest. It should switch up if you go fullscreen, though.

**Comment by tf-kevin** [comment]
Thanks for your feedback, @gkatsev. 
I've tested it with the current Safari version (14.0.3). The player dimensions are 1232x693, so a chosen rendition of 240p would be weird. The stream plays in the correct rendition if I open the HLS playlist directly, so I thought this could be an issue with the player.

**Comment by gkatsev** [comment]
That's definitely weird. Can you try using a regular video element in the same size without Video.js and see whether it's choosing the same rendition?
Also, in Safari dev tools, under settings->console you can enable Media Logging which may give you more info about what's happening.

**Comment by tf-kevin** [comment]
I might have got a clue what might have happened. 
After reading the Apple HLS specifications I think that the "BANDWIDTH" argument in the master playlist needs to be in Bit/s not Kbit/s. After overwriting the playlist manually it seems to work fine, even in videojs. 

Excerpt: 
> 9.13. The BANDWIDTH attribute MUST be the largest sum of peak segment bit rates that is produced by any playable combination of renditions.
[https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices)

Can you give me a hint about if that is correct? If so we can go ahead and close this issue.

**Comment by gkatsev** [comment]
That's right. If you check the spec, it defined BANDWIDTH as bits per second: https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#section-4.4.6.2
> The value is a decimal-integer of bits per second

**Comment by tf-kevin** [comment]
Thanks for the reference to the IETF doc.
I will close this issue now as it was an issue not related to this repo.
