### ISSUE TITLE
XMLHttpRequest cannot load skd://drmtoday?assetId=.... due to access control checks error in Safari

### ISSUE THREAD

**Issue by barnapisti1994** [videojs/http-streaming#1069]
Hi guys!
I'm trying to play an HLS video using the latest version of videojs(7.11.4) and videojs-contrib-eme(3.8.0). After getting the manifest it starts fetching the first segments but fails with the 'XMLHttpRequest cannot load skd://drmtoday?assetId=.... due to access control ' error. I have provided custom functions for fetching the license and certificate for Fairplay DRM but those are not called at all. Aside of that I followed the basic setup guide for HLS playback. Are there some general causes behind an issue like this?

**Comment by gkatsev** [comment]
Are you able to share a reduced example? If you can't share it publicly, would you be able to share it privately (you can message me on [slack](http://slack.videojs.com))
