### ISSUE TITLE
HLS playback broken in v2.6.0

### ISSUE THREAD

**Issue by DispatchCommit** [videojs/http-streaming#1076]
## Description

HLS video does not play with http-streaming v2.6.0 - There is no issue when using 2.5.0.

## Sources
don't have a publicly accessible link available - could provide a temporary reproduction link if required though, would just take bypassing auth and cors checks.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Use Video.js with http-streaming v2.6.0
2. Load an HLS live stream into the player
3. ...
4. Stream will never load, blank / black player with loading circle is all that appears. Does not go away.

### Expected

HLS Video to play like normal.

### Error output

![image](https://user-images.githubusercontent.com/45262335/108452709-c9c9dd80-721d-11eb-83c5-a387f3e926f1.png)

![image](https://user-images.githubusercontent.com/45262335/108453048-80c65900-721e-11eb-93d7-59d12870a6c6.png)

## Additional Information

Myself and another developer for 2 separate live streaming platforms have both encountered this breaking issue, yet there are no existing reports of issues on Github. 

![image](https://user-images.githubusercontent.com/45262335/108452797-039ae400-721e-11eb-94d6-8fadce51ab5a.png)

### videojs-http-streaming version

videojs-http-streaming **2.6.0**

### videojs version

video.js **7.11.4**

### Browsers

Chrome / Chromium based browsers.

### Platforms

Probably all, but tested on Windows 10

### Other Plugins

Contrib Quality Levels, HLS quality selector

### Other JavaScript

I use Vue.js inside Nuxt.js. The other developer is using React. Both appear to have issues.

-----

Further investigation needed likely, but I wanted to make sure I brought this to attention first and created a place to document issues, and reproducible instructions.

**Comment by gkatsev** [comment]
Does it work on https://videojs-http-streaming.netlify.app/ or still broken there?

**Comment by gkatsev** [comment]
Reading the convo, yeah, I think it likely is fixed by https://github.com/videojs/http-streaming/pull/1072. It's broken if you're minifying your build (which you probably are).
We're going to release a patch tomorrow with that change but if you can try linking in the main branch and see whether it works for you, that would be helpful.

**Comment by DispatchCommit** [comment]
> It's broken if you're minifying your build

Well of course minifying files! 😄 and the error message *looks* like an issue caused by minification.

ALSO, I accidentally pushed v2.6.0 into our production build thinking it was fine because running in the dev build (un-minified) worked fine. Wasn't until I verified the deployment did I realize that the player broke.

> We're going to release a patch tomorrow with that change

 Awesome, based on what we've discussed so far, I think this would resolve the issue. 
 
 > try linking in the main branch and see whether it works for you, that would be helpful.

Oh, gotta remember how to do that through NPM... believe it's:

`npm install videojs/http-streaming#main` 

(if that works, I'll push to staging and let you know if it works shortly)

**Comment by gkatsev** [comment]
Unfortunately, installing from github won't work because it doesn't have the built files.

**Comment by gkatsev** [comment]
> ALSO, I accidentally pushed v2.6.0 into our production build thinking it was fine because running in the dev build (un-minified) worked fine. Wasn't until I verified the deployment did I realize that the player broke.

Oops, sorry that happened.

**Comment by DispatchCommit** [comment]
> installing from github won't work

That's a shame, I love that trick for quick testing and feedback without much effort 😞
It's 9pm for me, and if the patch ships tomorrow, would be easiest for me to just wait for the patch and test that. 

> Oops, sorry that happened.

😄 All good, that's why rollbacks exist. At least this issue was immediately obvious.

**Comment by gkatsev** [comment]
👍🏻 sounds good.

**Comment by gkatsev** [comment]
@DispatchCommit VHS 2.6.1 is out. Please try it out!

**Comment by datagutt** [comment]
VHS 2.6.1 seems to work fine on my end (i am the person in the screenshot).
We should probably hear from @DispatchCommit first though, to see if it works on his platform as well.

**Comment by gkatsev** [comment]
Thanks!

**Comment by DispatchCommit** [comment]
Confirming this issue is resolved in VHS v2.6.1

Thanks for the help @gkatsev, glad to see this working as expected!

**Comment by gkatsev** [comment]
Thanks for circling back!
