### ISSUE TITLE
Auto-played demuxed stream fails to play and infinitely stalls

### ISSUE THREAD

**Issue by evanfarina** [videojs/http-streaming#1084]
## Description
The stream in question contains demuxed audio and video streams and there is a small timeline difference of around 1 second between the audio and video streams (see attached screenshot). The stream fails to play with auto-play enabled but plays correctly when auto-play is disabled and the stream is started by user interaction. See [this demo](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=true&muted=false&minified=false&sync-workers=false&liveui=false&partial=false&url=https%3A%2F%2Flivectorprodmedia12-usea.licdn.com%2F0c13be2a-1820-4837-8318-29b9e6187219%2FL4D5ded7c97c980f000-livemanifest.ism%2Fmanifest(format%3Dm3u8-aapl)&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&override-native=true&preload=auto&mirror-source=true) to reproduce the issue.

## Sources
https://livectorprodmedia12-usea.licdn.com/0c13be2a-1820-4837-8318-29b9e6187219/L4D5ded7c97c980f000-livemanifest.ism/manifest(format=m3u8-aapl)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Visit the [http-streaming demo page](https://videojs-http-streaming.netlify.app/)
2. Enter the source: https://livectorprodmedia12-usea.licdn.com/0c13be2a-1820-4837-8318-29b9e6187219/L4D5ded7c97c980f000-livemanifest.ism/manifest(format=m3u8-aapl)
3. Check the `AutoPlay` checkbox
4. Click the "load" button to load the source with the above settings

### Expected
The stream should play like any other demuxed stream.

### Error output
No error output, no failed network requests, nothing obvious found in verbose video.js log output

## Additional Information
I've spent some time digging into this myself and have the below notes. I believe the issue is a race condition, though I haven't gotten to the bottom of the issue yet.

Call stack from AutoPlay case:

1. `setupMasterPlaylistLoaderListeners_` is called
2. `setupFirstPlay` is called
3. MasterPlaylistController.load() called
4. mainSegmentLoader_.load() is called, and succeeds
5. audioSegmentLoader_.load() is called, but returns early because `this.playlist` is undefined (due to race condition, though I don't believe this is an issue as working demuxed follow this same path)
6. *race* media-groups.AUDIO.loadedplaylist event is handled, audio playlist is setup
7. *race* media-groups.AUDIO.loadedmetadata event is handled, audio playlist is setup

In the manual-play case, #6 and #7 happen before #3 and therefore the playlist plays. *NOTE* - Working demuxed sources follow the same path as the above and play fine. There is something happening after #6 and #7 that allows other sources to play, but I haven't figured out what that 'something' is yet.

### videojs-http-streaming version
Latest in repo

![image](https://user-images.githubusercontent.com/8199672/109556221-8a648200-7aa4-11eb-892f-188604f5c9cc.png)

**Comment by gesinger** [comment]
Thank you for the detailed issue and source @evanfarina !

# Why not using autoplay still plays the video

Our gap skipper is skipping the gap. From the debug logs:

> VIDEOJS: DEBUG: VHS: PlaybackWatcher > skipTheGap_: currentTime: 0 scheduled currentTime: 0 nextRange start: 1.147888

This is because the playback-watcher sees a `waiting` event from the tech (from the video element) after there's buffered contents (since it's unlikely a user hits play before some of the content is buffered).

# Why using autoplay doesn't play the video

The `waiting` event happens too quickly, before any content is buffered, so playback-watcher has no gap to skip.

# What we can probably do

Although it would be best for the content not to have a gap at the start, playback-watcher should be able to handle this scenario. Right now, the playback monitoring only starts on `canplay`: https://github.com/videojs/http-streaming/blob/c348174d1c433dd7fe7b68378da4b2b18266c954/src/playback-watcher.js#L89

This should probably start monitoring on `play` as well. I added that listener and it fixed the autoplay behavior.

We should do a bit more testing and thinking, but this, or something like it, is probably the approach we'll take.

**Comment by JeppeTh** [comment]
Not sure if related but I have problem playing live streams when not playing from the live edge,
I'm running on Samsung Tizen - latest versions of videojs etc.

When playing from a point in the past of a live stream I basically always end up in a `vhs-gap-skip` loop. Seems to be triggered by a `waiting` event
Is there some way to avoid this?
```
Mon Jul 20 22:20:13 2026 : playing State:3 Currenttime:65.28'
Mon Jul 20 22:20:15 2026 : canplaythrough State:4 Currenttime:66.904'
Mon Jul 20 22:20:15 2026 : start:0 end:33589.68000000038 l:1 duration:0 State:4 Currenttime:66.904'
Mon Jul 20 22:20:17 2026 : canplaythrough State:4 Currenttime:68.789'
Mon Jul 20 22:20:17 2026 : start:0 end:33593.520000000375 l:1 duration:0 State:4 Currenttime:68.789'
Mon Jul 20 22:20:46 2026 : waiting State:1 Currenttime:98.003'
Mon Jul 20 22:20:46 2026 : usage:vhs-gap-skip State:1 Currenttime:99.873333'
Mon Jul 20 22:20:46 2026 : seeking State:1 Currenttime:99.873333'
Mon Jul 20 22:20:47 2026 : seeked State:4 Currenttime:99.84'
Mon Jul 20 22:20:47 2026 : canplay State:4 Currenttime:99.84'
Mon Jul 20 22:20:47 2026 : playing State:4 Currenttime:99.84'
Mon Jul 20 22:20:47 2026 : canplaythrough State:4 Currenttime:99.84'
Mon Jul 20 22:20:47 2026 : start:0 end:33620.40000000035 l:1 duration:0 State:4 Currenttime:99.84'
Mon Jul 20 22:20:49 2026 : waiting State:1 Currenttime:102.154'
Mon Jul 20 22:20:49 2026 : usage:vhs-gap-skip State:1 Currenttime:103.713333'
Mon Jul 20 22:20:49 2026 : seeking State:1 Currenttime:103.713333'
Mon Jul 20 22:20:49 2026 : seeked State:4 Currenttime:103.68'
Mon Jul 20 22:20:49 2026 : canplay State:4 Currenttime:103.68'
Mon Jul 20 22:20:49 2026 : playing State:4 Currenttime:103.68'
Mon Jul 20 22:20:50 2026 : canplaythrough State:4 Currenttime:103.68'
Mon Jul 20 22:20:50 2026 : start:0 end:33624.24000000035 l:1 duration:0 State:4 Currenttime:103.68'
Mon Jul 20 22:20:52 2026 : waiting State:1 Currenttime:105.587'
Mon Jul 20 22:20:52 2026 : usage:vhs-gap-skip State:1 Currenttime:107.553333'
Mon Jul 20 22:20:52 2026 : seeking State:1 Currenttime:107.553333'
Mon Jul 20 22:20:52 2026 : seeked State:4 Currenttime:107.52'
Mon Jul 20 22:20:52 2026 : canplay State:4 Currenttime:107.52'
Mon Jul 20 22:20:52 2026 : canplaythrough State:4 Currenttime:107.52'
Mon Jul 20 22:20:52 2026 : start:0 end:33624.24000000035 l:1 duration:0 State:4 Currenttime:107.52'
Mon Jul 20 22:20:55 2026 : waiting State:1 Currenttime:110.021'
Mon Jul 20 22:20:55 2026 : usage:vhs-gap-skip State:1 Currenttime:111.393333'
Mon Jul 20 22:20:55 2026 : seeking State:1 Currenttime:111.393333'
Mon Jul 20 22:20:55 2026 : seeked State:4 Currenttime:111.36'
Mon Jul 20 22:20:55 2026 : canplay State:4 Currenttime:111.36'
Mon Jul 20 22:20:55 2026 : playing State:4 Currenttime:111.36'
Mon Jul 20 22:20:55 2026 : canplaythrough State:4 Currenttime:111.36'
Mon Jul 20 22:20:55 2026 : start:0 end:33631.92000000034 l:1 duration:0 State:4 Currenttime:111.36'
```

EDIT: probably not related. Did some additional investigation
https://github.com/videojs/http-streaming/issues/1610
