### ISSUE TITLE
call videoElement.load() or video.js Player.load() will error

### ISSUE THREAD

**Issue by wmlgl** [videojs/http-streaming#1096]
## Description
call videoElement.load() or video.js Player.load() will error

## Sources
demo https://jsfiddle.net/wmlgl/d1xyt8mr/27/

## Steps to reproduce
1.click demo play button
2.click demo load button

### Error output
The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
video.js 7.10.1

### Browsers
what browsers are affected? please include browser and version for each
chrome  89.0.4389.72

### Platforms
what platforms are affected? please include operating system and version or device and version for each
window 10 

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Yeah, unfortunately, that's a known issue see videojs/video.js#7005. I would recommend against calling `load` when VHS is used. However, it is something that we should handle properly.
