### ISSUE TITLE
Unable to get 'VHS' on IOS

### ISSUE THREAD

**Issue by cuiD2488** [videojs/http-streaming#1102]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Unable to get 'VHS' on IOS

## Sources
https://home-new.roadshowchina.cn/Wap/Index/play.html?mid=10868

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.Click the "网络" button of the player
2.Check whether the data in the top red box is displayed normally
3.

### Expected
Expect to display data —— this.player.tech({IWillNotUseThisInPlugins: true}).vhs

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
Video.js 7.5.4
@videojs/http-streaming @version 2.4.2

### Browsers
ios safari 
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
 * videojs-contrib-hls
 * @version 5.15.0
 * @copyright 2018 Brightcove, Inc
 * @license Apache-2.0
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by ziddey** [comment]
https://github.com/videojs/http-streaming#browsers-which-support-mse

iOS doesn't support MSE, only native hls

**Comment by cuiD2488** [comment]
> https://github.com/videojs/http-streaming#browsers-which-support-mse
> 
> iOS不支持MSE，仅支持本地hls

Thank you for your reply，So I can't use it on IOS?

**Comment by cuiD2488** [comment]
> https://github.com/videojs/http-streaming#browsers-which-support-mse
> 
> iOS doesn't support MSE, only native hls

If I want to get the corresponding data on IOS, what should I do?

**Comment by gkatsev** [comment]
The short answer is that no, this isn't available on iOS.
The slightly longer answer is that on iPads *only* you could enable VHS, however, we don't recommend doing so because we haven't been testing extensively with Safari compared to Chrome and Firefox.

**Comment by dsine-de** [comment]
Just a quick question - how would I get the framerate when `vhs` is not available?
I do this on non-Safari browsers:

```js
player.tech(false).vhs.playlists.media().attributes['FRAME-RATE']
```

Is there any other way if there is no `vhs` property?

**Comment by gkatsev** [comment]
native apis do not provide this information. Your best bet is to download the manifest separately and parse it out manually.

**Comment by dsine-de** [comment]
Thank you!

Do I have to import `m3u8-parser` or is it already available in the `video.js` module?

```js
import videojs from 'video.js';
import {Parser} from 'm3u8-parser';

const video = document.getElementById(...

const player = videojs(video, { ...
const parser = new Parser();

player.one('loadedmetadata', async () => {
	parser.push(await (await fetch(video.querySelector('source').src)).text());
	parser.end();

	console.log(parser.manifest.playlists[0].attributes['FRAME-RATE']);
});
```
