### ISSUE TITLE
Currently included mpd-parser version is flagged with security issues

### ISSUE THREAD

**Issue by heennkkee** [videojs/http-streaming#1107]
## Description
The library xmldom is flagged with security problems (causing `npm audit` to be sad). This is fixed in xmldom >= 0.5.0.
mpd-parser depends on xmldom and from 16.0 it is updated to xmldom 0.5.0.
@video.js/http-streaming is currently depending on mpd-parser 15.4 (which depends on xmldom 0.4.0).

The solution would be to depend on mpd-parser 16.0 instead.

## Sources
N/A (https://github.com/videojs/http-streaming/blob/main/package.json#L64)

## Steps to reproduce
1. Create a new project
2. Install @videojs/http-streaming with npm `npm install @videojs/http-streaming`
3. Run `npm audit`

### Expected
No warnings

### Error output
![image](https://user-images.githubusercontent.com/12745884/112851760-92b3db00-90ab-11eb-9ec8-602186b766b5.png)

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
videojs-http-streaming 2.6.4

### videojs version
video.js 7.11.4

### Browsers
N/A

### Platforms
N/A

### Other Plugins
N/A

### Other JavaScript
N/A

**Comment by gkatsev** [comment]
We'll update it soon!
However, I just wanted to note that xmldom is only used by mpd-parser when it's run in node.js and thus isn't a concern for this library since VHS only runs in browsers.

**Comment by ryrere** [comment]
Thanks for the great project. Will the mpd-parser and xmldom dependencies be updated soon? There's a security alert at the top of our repositories and we don't want to get in the habit of ignoring those alerts.

<img width="686" alt="screenshot" src="https://user-images.githubusercontent.com/84041096/117869315-7fba2c00-b24f-11eb-8fe5-5256dcc26b61.png">
