### ISSUE TITLE
"export 'generateSidxKey' was not found in 'mpd-parser'

### ISSUE THREAD

**Issue by xiaoxue1341** [videojs/http-streaming#1115]
![image](https://user-images.githubusercontent.com/14305101/113980678-5c2f4a80-9879-11eb-92b4-0f30bbc5251f.png)

**Comment by gkatsev** [comment]
Are you using npm or yarn? Also, are you using a bundler? If so, what bundler?
Can you run `npm ls mpd-parser` and post the result?

**Comment by gkatsev** [comment]
Also, what version of Video.js and VHS are you using?
