### ISSUE TITLE
Http-Streaming support Verimatrix Multi-DRM Core

### ISSUE THREAD

**Issue by vitaliy-shahanyants** [videojs/http-streaming#1129]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

## Description
This is not an issue, it's more so support.

We have Verimatrix Multi-DRM Core and we were wondering if you support it.

If you do support would you mind sending me the documentation?

TheoPlayer supports it: https://docs.theoplayer.com/how-to-guides/04-drm/09-verimatrix-multirights.md

Please let me know.

Thank you.

**Comment by gkatsev** [comment]
Unfortunately, we don't have the bandwidth to support it directly.
