### ISSUE TITLE
Videojs infinitely calls URL when overriding Safari's default HLS player

### ISSUE THREAD

**Issue by barnapisti1994** [videojs/http-streaming#1136]
## Description
I used the overrideNative guide to override the default HLS player of Safari. After loading the manifests videojs starts calling a DRM related URL infinitely (throws thousands of errors in a few seconds). It calls this URL:

`skd://drmtoday?assetId=(our asset id)`

This is the related part of the manifest:

```
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://drmtoday?assetId=(our asset id)",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
#EXT-X-MAP:URI="(our url)",BYTERANGE="2091@0"
```

I have seen that the library doesn't support the SAMPLE-AES encryption currently. Could it be the cause of the issue?

Unfortunately using the default HLS player is not an option because it doesn't provide an access to the current and available representations. What is the best way to solve this problem? Using a different encoding?

### Expected
I would expect videojs to throw an error and terminate instead of calling a URL more than a thousand times.

### Error output
XMLHttpRequest cannot load the URL due to access control checks.

### videojs-http-streaming version
videojs-http-streaming 2.8.`

### videojs version
what version of videojs does this occur with?
video.js 7.12.1

### Browsers
Safari 14.0.3 and earlier versions

### Platforms
macOS 11.2.3

### Other Plugins
videojs-contrib-eme 3.8.0

### Other JavaScript
React

**Comment by gkatsev** [comment]
Yeah, it's possible that SAMPLE-AES is the issue, though, when keyformat is `com.apple.streamingkeydelivery` I think that means it's fairplay DRM rather than HLSe?
It's likely a combination of the two, either no SAMPLE-AES support or no fairplay with MSE support.

**Comment by barnapisti1994** [comment]
Thanks for the quick answer @gkatsev! I did some further research on the problem. When parsing the hls manifest using the m3u8 parser it assigns key objects to each segment like this:
```
  {
    method: 'SAMPLE-AES',
    uri: 'skd://drmtoday?assetId=(our asset id)'
  }
```
After processing the segments have `'skd://drmtoday?assetId=(our asset id)'` as segment.key.resolvedUri. Because of this the following part of the videojs code tries to fetch they key from this invalid url.
```
  if (segment.key && !segment.key.bytes) {
    var keyRequestOptions = videojs$1.mergeOptions(xhrOptions, {
      uri: segment.key.resolvedUri,
      responseType: 'arraybuffer'
    });
    var keyRequestCallback = handleKeyResponse(segment, finishProcessingFn);
    var keyXhr = xhr(keyRequestOptions, keyRequestCallback);
    activeXhrs.push(keyXhr);
  }
```
The decryption works fine with the native HLS player of Safari when we fetch a certificate and a license using the videojs-contrib-eme plugin. How could we use the certificate and the license key to decrypt these segments when overriding the native HLS player?

**Comment by gkatsev** [comment]
I think the answer is that we don't really support fairplay with MSE. One thing that needs to happen is to use `com.apple.fps.2_0` rather than `com.apple.fps.1_0` to declaring the license stuff, but I'm not sure if there's anything else we'd need to do.
