### ISSUE TITLE
play HLS m3u8 not working

### ISSUE THREAD

**Issue by WeBBLiu** [videojs/http-streaming#1140]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Can't play hls source .m3u8 files

```

<link href="//vjs.zencdn.net/7.10.2/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/7.10.2/video.min.js"></script>
<!--2.8.2-->
<script src="videojs-http-streaming.min.js"></script> 
<video id="html5_video"  
		class="html5_video video-js vjs-default-skin vjs-big-play-centered vjs-16-9 vjs-fill" 
		preload 
		autoplay 
		playsinline
		controls
	>
	  <source src="https://vod.streamingfast.net/hls-vod/video/OT3A0384.m3u8" 
		type="application/x-mpegURL">
	</video>
<script>
var player = videojs('html5_video');

</script>
```

## Sources
https://live.streamingfast.net/osmflivech1.m3u8

### Error output
Console.log :
video.min.js:12 VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!

### videojs-http-streaming version
<script src="videojs-http-streaming.min.js"></script> //2.8.2

### videojs version
Any version

### Browsers
Chrome , Edge,  Firefox

### Platforms
Win7 , Win10

### Other Plugins
none

### Other JavaScript
none

**Comment by gkatsev** [comment]
Seems to be playing fine for me via https://videojs-http-streaming.netlify.app/. Can you try your stream there?
Can you provide more info on when and how you're seeing an issue?

FYI, you don't need to include VHS separately, it's included in Video.js.
