### ISSUE TITLE
关于画质问题

### ISSUE THREAD

**Issue by haijee** [videojs/http-streaming#1143]
请问我如何检测画质切换完毕，以及最快的切换画质，清除掉缓存的上一个画质的视频

**Comment by gkatsev** [comment]
If you upgrade to Video.js 7.13 (which includes VHS 2.9), user initiated rendition changes always clear the buffer now. This includes going and exiting fullscreen.
If you want detailed information about which rendition is playing right now, check out [Segment Metadata](https://github.com/videojs/http-streaming#segment-metadata). Though, it's worth noting that this isn't available in Safari/native playback.
