### ISSUE TITLE
p2p ?

### ISSUE THREAD

**Issue by Phillipip** [videojs/http-streaming#1154]
Is there a working p2p solution for the current version?

**Comment by gkatsev** [comment]
Unfortunately, this isn't something that we support.
I've found https://github.com/Novage/p2p-media-loader which allows you to use p2p inside of Video.js, though you'll need to load hls.js or shaka instead of VHS.

**Comment by snowinszu** [comment]
Can you expose a loader like hls.js so we can do p2p on it? Thank you very much.

**Comment by snowinszu** [comment]
@Phillipip   The solution you may be interested: https://github.com/swarm-cloud/hls-p2p-engine/blob/main/demo/videojs-vhs.html

**Comment by vistream-dev** [comment]
I am looking for a solution that I can set up myself, not an advertisement for a commercial product.
