### ISSUE TITLE
dash VOD in Firefox: loading animation appears on ended

### ISSUE THREAD

**Issue by phloxic** [videojs/http-streaming#1156]
## Description
When playing a VOD dash stream created by gpac in Firefox (on Mac, did not test other platforms) the loading spinner appears when the video ends.
Minimal sample page [here](https://phloxic.productions/test/videojs/dash.html) using latest videojs 7.14.0

This happens with all profiles gpac offers.

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.
2 sample streams:
https://d12zt1n3pd4xhr.cloudfront.net/dev/lshtrailer-d2-nosub.mpd (full profile)
https://d12zt1n3pd4xhr.cloudfront.net/dev/lshtrailer-od-nosub.mpd (onDemand profile)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. In Firefox go to [sample page](https://phloxic.productions/test/videojs/dash.html) or try one of the streams on the [test page](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&sync-workers=false&liveui=false&llhls=false&url=https%3A%2F%2Fd12zt1n3pd4xhr.cloudfront.net%2Fdev%2Flshtrailer-d2-nosub.mpd&type=application%2Fdash%2Bxml&keysystems=&buffer-water=false&override-native=true&preload=auto&mirror-source=true)
2. Play or scrub until end
3. Loading spinner appears

### Expected
The loading spinner should not appear on ended, the player should not be in waiting state then.

### Error output
There is no error.

## Additional Information
Dirty workaround:
```
player.on('ended', function () {
  player.removeClass('vjs-waiting');
})
```

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
all I tried up to videojs-http-streaming 2.9.1

### videojs version
what version of videojs does this occur with?
tested latest over ca. year up to video.js 7.14.0

### Browsers
what browsers are affected? please include browser and version for each
* Firefox (Mac) tested over a long time, several versions up to 89.02.

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Mac OS X, tested over a long time, several versions up to 10.14.6.

### Other Plugins
are any other videojs plugins being used on the page?
* no

### Other JavaScript
are you using any other javascript libraries or frameworks on the page?
* no

**Comment by gkatsev** [comment]
Can confirm, weird. Wonder what the difference is.

**Comment by phloxic** [comment]
Just tried one of the streams without audio: [no problem](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&sync-workers=false&liveui=false&llhls=false&url=https%3A%2F%2Fd12zt1n3pd4xhr.cloudfront.net%2Fdev%2Flshtrailer-d2-noaudio.mpd&type=application%2Fdash%2Bxml&keysystems=&buffer-water=false&override-native=true&preload=auto&mirror-source=true).
I strongly suspect aac padding (my favorite evil ;-)); the audio track being slightly longer. The audio is AAC_HE, encoded by fdk, and it has relatively long delays. - vhs has no trouble with the HLS versions of the streams, at least not when they segmented by mediafilesegmenter.

FWIW, dash.js seems to be able to handle the ending of those streams, they also pass the dash-if conformance test.

**Comment by gkatsev** [comment]
> I strongly suspect aac padding

![oh-no](https://user-images.githubusercontent.com/535884/124342081-2dcabe00-db8f-11eb-9cb8-fda7d047933d.png)

**Comment by phloxic** [comment]
2 well-behaved examples with AAC_HEv1 encoded by afconvert ("iTunes" cli):
- [onDemand profile](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&sync-workers=false&liveui=false&llhls=false&url=https%3A%2F%2Fd12zt1n3pd4xhr.cloudfront.net%2Fdev%2Flshtrailer-afconv.mpd&type=application%2Fdash%2Bxml&keysystems=&buffer-water=false&override-native=true&preload=auto&mirror-source=true)
- [full profile](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&sync-workers=false&liveui=false&llhls=false&url=https%3A%2F%2Fd12zt1n3pd4xhr.cloudfront.net%2Fdev%2Flshtrailer-afc.mpd&type=application%2Fdash%2Bxml&keysystems=&buffer-water=false&override-native=true&preload=auto&mirror-source=true)

Well, that's me sorted ... until I turn a corner and bang my head against [this](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFAppenG/QTFFAppenG.html) yet again.

**Comment by gkatsev** [comment]
Looking at the order of events, the waiting event appears right before `ended`, so, I think having Video.js remove the spinner on ended makes sense.

**Comment by phloxic** [comment]
Certainly the most solid way to divert any blame from videojs ;-) ... I'm actually serious, after I experimented some more, cue can of worms, brittleness etc. Whereas so far I don't see an issue when simply removing the vjs-waiting class on ended explicitly (famous last words).
