### ISSUE TITLE
Video.js HLS streaming eternal loading on low bandwith

### ISSUE THREAD

**Issue by dieterwalckiers** [videojs/http-streaming#1158]
## Description
We're using video.js to stream hls videos (protected with an AES token).
This is working very well in almost all situations, but in our latest tests, we noticed a strange bug with low - bandwidth conditions.
This happens in video.js@7.13.3. It does not happen with an earlier version 7.9.7. We're pinning down that version now as a workaround.

What we're seeing is that some videos seem to keep loading eternally on low bandwith (Fast 3G setting in chrome).
This is the [reduced test case based on the starter template](https://jsbin.com/gajacepuda/edit?html,output).

## Sources
[Original video file](https://filebin.net/1paa2z7jxtfvh4mc)
[manifest file](https://manualtovideos-euwe.streaming.media.azure.net/bcf2ef1d-50ac-4b0c-80c6-24195d361e8a/ORIGINAL.ism/manifest(format=m3u8-aapl,encryption=cbc))
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI5OWU5YzVhNi04ZGE2LTRlZTctYmVhYi03OGEyMGYxZWQ4OWEiLCJleHAiOjE2MzQzODQxODQsIm5iZiI6MTYyNTgzMDI4NCwiaWF0IjoxNjI1ODMwNTg0LCJhdWQiOiJ1cm46YXVkaWVuY2UiLCJpc3MiOiJ1cm46aXNzdWVyIn0.dennD2eAbUEZ89WZkhh3kr3MXKWdjAy6O9_tMtsakAE

## Steps to reproduce

1. Open the [reduced test case based on the starter template](https://jsbin.com/gajacepuda/edit?html,output) in chrome
2. switch on network throttling on "Fast 3G" preset
3. Reload the page and click play

### Expected
The video starts playing after some buffering.

### Actual
The video keeps loading eternally

## Additional Information
I'm using v7.13.3 in my test case.
When changed it to 7.9.7, the video does play normally with "Fast 3G" throttling

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
No separate videojs-http-streaming package, we're using video.js >7, which includes it 

### videojs version
video.js 7.13.3

### Browsers
what browsers are affected? please include browser and version for each
Chrome 91.0.4472.114

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Tested on Ubuntu 20.04.1 LTS

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
No

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
No

**Comment by gkatsev** [comment]
One thing to try is setting `experimentalBufferBasedABR`, which should behave much better. It's a new ABR algorithm we've been working on. It's basically good to go, we're still experimenting with the buffer threshold values, which is why it hasn't been turned on by default yet.

**Comment by dieterwalckiers** [comment]
Thank you @gkatsev , this does make a difference.

**Comment by dieterwalckiers** [comment]
We're getting better results with this option. Thanks for the tip.

**Comment by gkatsev** [comment]
Good to hear!
