### ISSUE TITLE
Feature: Alternate renditons for video tracks

### ISSUE THREAD

**Issue by Llorito** [videojs/http-streaming#116]
Description
Adds support for alternate renditions video tracks. Analogous implementation to alternate audio renditions and text tracks.

The same was proposed in videojs-contrib-hls
https://github.com/videojs/videojs-contrib-hls/pull/1128

**Comment by Llorito** [comment]
Hey everyone... Do you know whether there's a plan to have this in a release soon?

Thanks

**Comment by gesinger** [comment]
Closing as a duplicate of https://github.com/videojs/http-streaming/issues/363
