### ISSUE TITLE
Switch/select between audio tracks in the .ts files (.ts file include video + 3 audio tracks)

### ISSUE THREAD

**Issue by AsafTAG** [videojs/http-streaming#1160]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Stream m3u8(not master playlist, the file contain only the ts files duration and order) to the browser
.m3u8 file for example:
  #EXTM3U
  #EXT-X-ALLOW-CACHE:YES
  #EXT-X-VERSION:3
  #EXT-X-MEDIA-SEQUENCE:2876165
  #EXT-X-TARGETDURATION:2
  #EXTINF:1.920,
  enc9206_1_2876162.ts
  #EXTINF:1.920,
  enc9206_1_2876163.ts
  #EXTINF:1.920,
  enc9206_1_2876164.ts
2. Video and "master" audio works fine
3. Cant switch between audio tracks(3 audio tracks are placed in each .ts file but no in m3u8)

### Expected
Please describe what you expected to happen that did not happen in the description.
I expected that the player will have under "audio tracks array" 3 audio tracks for each .ts file that is playing
If I look at the example file, that main file m3u8 has audio from separate files and mine main and only m3u8 file has the only the references to .ts files that include in them video + 3 audio tracks.

I would like to know if there is a solution to my problem and if not what is the best recommended way to solve it.
Thanks!

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z
latest

### videojs version
what version of videojs does this occur with?
video.js x.y.z
latest 

### Browsers
what browsers are affected? please include browser and version for each
* latest chrome 91.0.4472.114 

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Linux Ubuntu 20.04

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* No

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* No

**Comment by gkatsev** [comment]
Do you have a stream you can share? Also, I was wondering, have you tried this in Safari? Does it provide you the ability to switch between the audio streams embedded in the segments?
Though, it's unlikely that it's something that we address in the short term, though, I'm still not sure if it's something that we want to support.

**Comment by gkatsev** [comment]
Spoke to the other devs, and this isn't something that we can do. The work for this would be pretty significant. HLS has the alternate audio track capabilities, we'd expect you to use those rather than having multiple audio tracks inside a segment.
If you notice that Safari does handle this case, we can reconsider, though, even then, it won't be solved in the short term.
