### ISSUE TITLE
Renditions are getting re-enabled even after disabling them

### ISSUE THREAD

**Issue by KVPasupuleti** [videojs/http-streaming#1164]
## Description
We have removed the rendtions like 240 and 1080 from our list(240, 360, 480, 720, 1080) by disabling them as shown [here](https://github.com/videojs/http-streaming#vhsrepresentations) in the documentation.

Sometimes when the network is slow, 240 chunks are getting downloaded and after 5-7 chunks, the fallback is happening to 360.

## Steps to reproduce

1. Remove the 240p rendition programmatically from the playlist as shown in the documentation
2. Try changing the quality level using a quality level switcher plugin like `videojs-http-source-selector` randomly with a slow network
3. Observe the chunks that are getting downloaded in the network tab

You will find the 240p chunks getting downloaded for an instance and again falling back to 360p

### Expected
240 and 1080 levels should be completely removed and the video should be in a loading state if it couldn't even play the 360p rendition

### Additional Information
We have the `experimentalBufferBasedABR` enabled. This is happening when it is disabled too.

### videojs-http-streaming version
We are not using it as it is included in videoJS by default

### videojs version
video.js 7.13.3

### Browsers
Chrome 92

### Platforms
Linux

### Other Plugins
- videojs-http-source-selector - 1.1.6
- videojs-contrib-quality-levels - 2.1.0

### Other JavaScript
mobx - 5.15.0

**Comment by gkatsev** [comment]
We do end up using renditions that are turned off if the playlist fails, and we need to switch. We think a flag to force never using those turned off renditions make sense to us.
If you're interested in making a PR, that would be awesome. Otherwise, I've put it on our backlog.

**Comment by gkatsev** [comment]
It is also possible that there's a deeper bug, though. Since it seems like we should be ignoring disabled items in https://github.com/videojs/http-streaming/blob/main/src/playlist-selectors.js#L210-L215

@KVPasupuleti btw, is this HLS or DASH? Are you able to provide a source?

I think we'll want to investigate whether we have this bug first and then if there isn't a bug, we can add an option if necessary.
