### ISSUE TITLE
Partial download of m3u8

### ISSUE THREAD

**Issue by ivanshilo** [videojs/http-streaming#1170]
We want to create a live streaming that allows user seek back up to last 24h. Segment size is 3s. This gives 29k segments and all of them are menshioned in playlist m3u8 file. This makes the file to grow up to 2.5MB! And every 3s it will be reloaded in full by client to get a new segment name (last 2 rows).
Is there a way to make player to load only part of the file and not the whole one?

**Comment by gkatsev** [comment]
Assuming you're using HLS, HLS does provide a couple of mechanisms for it, though, unfortunately, not all of them are implemented right now. There's [variable substitution](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-08#section-4.3), which isn't implemented, and [delta playlist updates](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-08#section-6.2.5.1), which is behind an experimental flag as part of our low latency work.
One thing you can do which will likely cut down on the file size a lot is if you're using absolute URLs to switch to relative URLs.

**Comment by ivanshilo** [comment]
Thx for the update. I did some research and came to the same conclusions. Low latensy HLS is not broadly supported yet. I will minimize sequence name to the smallest possible name and we will have to inscrease segment size.

**Comment by gkatsev** [comment]
The delta playlist updates don't require LLHLS, just that we only implemented it as part of that. LLHLS is still flagged, but you can try it out. If you do, please let us know how that goes. The option is called `experimentalLLHLS`.

**Comment by ivanshilo** [comment]
As I understand delta playlist updates feature requires implementation on server side. I currently use ffmpeg with lhs muxer and asp.net core as a web-server. If I understand specification correctly, server has to remember each client state in order to provide individual delta updates. This would also include modifying ffmpeg created/updated playlist and generating unique playlist update per client.
Is it correct?

**Comment by gkatsev** [comment]
Yes, there needs to be backend support for it.
