### ISSUE TITLE
Metadata is not getting loaded

### ISSUE THREAD

**Issue by bhargavavarma** [videojs/http-streaming#1179]
## Description
Metadata is not getting loaded for the video. The video is staying indefinitely in the buffering state because of this reason.

To fix this, I kept the `PLAY` button even when it is buffering. When clicked on the play button, the metadata is getting loaded and the video is playing properly. 

This issue is happening specifically when I have the player in a resolution close to mobile width. 
There is no issue when I kept it in tablet resolution, and also in real mobile devices. 

## Steps to Reproduce

I, unfortunately, couldn't reproduce the issue with the `videoJS` demo or a code sandbox.  

Hence, I added these videos here. Please check and help me resolve this issue.

[Tablet width - metadata loading properly](https://drive.google.com/file/d/1OEYA3rSqWx-LgS8kBLeT5q-pgS9tBC_w/view?usp=sharing)
[Mobile width - metadata not getting loaded](https://drive.google.com/file/d/19mc6rHC_yXZWaZh84ywuGIBLHcnQSCzK/view?usp=sharing)

### Expected
The metadata should be loaded properly

### videojs-http-streaming version
videojs-http-streaming 2.9.1

### videojs version
video.js 7.13.3

### Browsers
Chrome 91

### Platforms
Ubuntu 18.04

### Other Plugins
videojs-http-source-selector 1.1.6
videojs-contrib-quality-levels 2.1.0

### Other JavaScript
"react": "^16.12.0"
"mobx": "5.15.0"
"mobx-react": "6.1.4"

**Comment by bhargavavarma** [comment]
@mister-ben @gesinger @gkatsev 

Please look into the issue and help me out

**Comment by gkatsev** [comment]
Unfortunately, this isn't something that we can help with without a simplified live test page.
It's worth noting that mobile UIs often default to preload=none, during which no metadata will get loaded before playback is requested. If you click play, do you end up getting a `loadedmetadata` event?
