### ISSUE TITLE
HLS: Problem with freezing/lag picture when switching to 1080p stream

### ISSUE THREAD

**Issue by aifeipeng** [videojs/http-streaming#1181]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
We are using hls. When switching to the highest quality stream there is a freeze of the video. We have tried the video out on hlsjs and on jwplayer. The freeze or lag do not occur on those which makes us believe there is something in the VHS code that causes this. Below is a link to js fiddle. Used your template to reproduce. 
https://jsfiddle.net/aifeipeng/r6mbnhk5/15/

## Sources
https://atg-eu.akamaized.net/atgse/prod/2021-08-09/Lopp_2021-08-09_5_8_20210809210156_500_20210809090156071.m3u8

I can provide more if needed

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. You need the screen to be big enough and the bandwith to be big enough so that you get the highest bitrate stream
2. After a few seconds there is a freeze in the video, but the time and audio keeps playing. i.e the the stream is not buffering

### Expected
Video should switch quality smoothly

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs version
video.js 7.14.3

### Browsers
what browsers are affected? please include browser and version for each
chrome
firefox
edge

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Forcing this stream to switch to 1080p, I see similar behavior with VHS and with HLS.js. The video freezes for a split second before playback continues.

**Comment by aifeipeng** [comment]
Not sure I follow, you're saying the stream is the problem? I guess it would be fine if it freezes when you force it but the problem is when you don't force it. When it switches on its own, that should be done smoothly?

**Comment by aifeipeng** [comment]
For those who might find the same problem. I found out that the real problem was that the stream, the stream worked fine on hls.js versions below 1.0.0 I used 0.14.3.  But the stream does not work well on VHS current version and hls.js 1.+ versions.

Closing the issue
