### ISSUE TITLE
ts cach issue

### ISSUE THREAD

**Issue by LX10x** [videojs/http-streaming#1183]
## Description

the vhs  store ts files downloaded after i refresh the page and run the video it runs the saved files not freshedones

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.import cdn vhs and videoJs
2.play the video
3.refresh the video 

## Results
the video must start from the begining 
### Expected
video start from the last time and there is a pre downloaded parts 

### Error output
no error in console and no xhr requests in network 

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
latest one
### videojs version
what version of videojs does this occur with?
video.js 7.11

### Browsers
chrome
*

### Platforms
windows

**Comment by gkatsev** [comment]
Have an example or even a video showing the problem? We don't cache segments ourselves and rely on the browser. We also don't store any types of start times.
How are you refreshing the video? reloading the page?

**Comment by LX10x** [comment]
i just played a video in vidoJS and watched like 5 minutes 
then reloaded the page 
i was expecting to load the video from begining but i have seen 5 minutes downloaded 
it was supposed to start from begining 
i solved the problem by 
making php page to serve the m3u8 file and ts files  i disabled cache from the php page 
now it works when i reload i start the videp from begining 0 minutes downloaded 
i dont wana cach video on the browser cuz it is gonna make the browser slow on android if iam watching too many videos

**Comment by LX10x** [comment]
> 
> 
> Have an example or even a video showing the problem? We don't cache segments ourselves and rely on the browser. We also don't store any types of start times.
> How are you refreshing the video? reloading the page?
i just played a video in vidoJS and watched like 5 minutes
then reloaded the page
i was expecting to load the video from begining but i have seen 5 minutes downloaded
it was supposed to start from begining
i solved the problem by
making php page to serve the m3u8 file and ts files i disabled cache from the php page
now it works when i reload i start the videp from begining 0 minutes downloaded
i dont wana cach video on the browser cuz it is gonna make the browser slow on android if iam watching too many videos

**Comment by gkatsev** [comment]
We don't actually cache anything in VHS nor do we invalidate the browser cache. If on a page refresh, we play back from the same place, it likely means that the backend is serving a manifest that starts 5 minutes in.
Anyway, glad you were able to solve this issue.
