### ISSUE TITLE
Issue with video.js playing AES encrypted video

### ISSUE THREAD

**Issue by r3dge** [videojs/http-streaming#1193]
## Description
Briefly describe the issue.
I'm trying to use video.js to play an encrypted HLS video. The AES 128 encryption has been done using FFMPEG and this method : [https://hlsbook.net/how-to-encrypt-hls-video-with-ffmpeg/](url)
The player is loading and appears in the browser but the video can not be played.

Server side i'm using Apache with Symphony 5. The server return a HTTP 200 status for the first ts file of the video. When i press the play button of the player seems to retry downloading. It get a 200 each time but the video is not played.

## Sources
```html
<video-js id="my_video_1" class="vjs-default-skin" controls preload="auto" width="640" height="268">
    <!--<source src="https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8" type="application/x-mpegURL">-->
<source src="http://192.168.56.1/enc/prog_index.m3u8" type="application/x-mpegURL">
<script src="https://unpkg.com/video.js/dist/video.js"></script>
<script src="https://unpkg.com/@videojs/http-streaming/dist/videojs-http-streaming.js"></script>
```
Update : i tried to play the same video without encryption and it works. The problem seems to be due to the encryption itself.

### Expected
The player should play the video.

### Error output
I get two warnings in the console :
- video.js:159 VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!
- VIDEOJS: WARN: Problem encountered with playlist 0-http://192.168.56.1/enc/prog_index.m3u8. Trying again since it is the only playlist.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
"@videojs/http-streaming": "^2.10.2",

### videojs version
what version of videojs does this occur with?
"video.js": "^7.15.4",

### Browsers
what browsers are affected? please include browser and version for each
Chrome Version 92.0.4515.159

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*
Client : Windows 10
Server side : Lubuntu 20.04, Apache 2 with Symfony 5

### Other Plugins
No other plugin

### Other JavaScript
No other javascript
*

**Comment by gkatsev** [comment]
Hey, is this still something that's an issue, or did you get it working? Unfortunately, without a sample stream, we can't help at all.
BTW, you don't need to include VHS since you're using latest Video.js 7.

**Comment by r3dge** [comment]
Hi,
It's still an issue as i didn't found any solution. I can send you the encrypted video if you would. Let me know.

**Comment by a24576946** [comment]
> 你好，因为 我没有找到任何解决方案，这仍然是一个问题你愿意，我可以把你的视频描述给你。让我知道。

I have the same problem as you. The m3u8 file cannot be decrypted correctly after the second encryption.This problem only appears on safari and ios, and if it is a non-secondary encrypted m3u8 file, it can be parsed and played correctly.Because we have encrypted the key again, we need videojs to provide a hook function for decrypting again.
