### ISSUE TITLE
background tab in browser - livestream stops playing, won't go live anymore

### ISSUE THREAD

**Issue by tzarebczan** [videojs/http-streaming#1196]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
We've been using video-js + http streaming for a while now on Odysee. A recent bug that I've seen happen and reported by others is where playback of a livestream stops if the stream is left in a background tab. This can happen anywhere from a few minutes to a 10+ after doing so. 

Clicking the live button makes it skip to the front, red live button shows, but video stays buffering. 

The network tab shows the index file updates, which continue to get new data - just no new data via ts files actually arrive. 

The only way to fix this is to refresh the entire page/player. Then it plays fine. 

Up until the latest videojs update which fixed some bugs around playlist files being blocked on re-access, we would get this during an active tab too. 

![image](https://user-images.githubusercontent.com/8120721/132541921-ce322bf8-c81a-43af-91bf-4d0d10719c7e.png)

## Sources
We can setup a test live stream for you to try, or try this one: https://odysee.com/@Danheim:4/fimbul-radio:2

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. start live stream
2. make another tab active
3. wait for stream to stop

### Expected
Stream continues, does not get stuck. If stuck, clicking live should fix it and not require a refresh. 

### Error output
no
## Additional Information
Please include any additional information necessary here. Including the following:
Our player repo: https://github.com/lbryio/odysee-livestream-player

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
    "node_modules/@videojs/http-streaming": {
      "version": "2.10.2",

### videojs version
what version of videojs does this occur with?
"node_modules/video.js": {
      "version": "7.15.4",

### Browsers
All 

### Platforms
All

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
About how long does it take for it to fail in the background? Also, is the stream muted or has audio when it's in the background?

**Comment by tzarebczan** [comment]
It can vary from a few minutes, to 20/30+. Sometimes works longer...maybe depends on what's happening in other tabs. 

Stream has audio enabled. Happens in both cases though.
