### ISSUE TITLE
LLHLS - playlist loader, querystring breaks uri

### ISSUE THREAD

**Issue by dva00jnd** [videojs/http-streaming#1198]
I think below line will break loading of playlist if uri already contain a "?".
https://github.com/videojs/http-streaming/blob/81600194030c22c283892e796d71700820478891/src/playlist-loader.js#L74

For me it ends up trying to load a playlist containing double "?" in uri, example below:
https://manifes.fastly.example.com/rendition.m3u8?cdn=fastly&expires=1653133440&live=1&skid=default&signature=ABC?_HLS_msn=8&_HLS_part=0

**Comment by gkatsev** [comment]
Yeah, this makes sense.
