### ISSUE TITLE
Consider an option to preload live

### ISSUE THREAD

**Issue by forbesjo** [videojs/http-streaming#120]
Right now the project provides no mechanism to preload live data before the first play, perhaps we should add a setting to allow this.
See https://github.com/videojs/videojs-contrib-hls/issues/1396

**Comment by gianthead97** [comment]
Hi @forbesjo, is this closed because of completition, or team decided to not support this option?

**Comment by gkatsev** [comment]
We do not currently have a plan to support this due to the complexities around live video and preloading.
