### ISSUE TITLE
Video JS HLS jumps back to previous segment during live stream

### ISSUE THREAD

**Issue by harvister** [videojs/http-streaming#1202]
## Description
I have [reproduced an error][1] with video js where playback will jump to the previous segment in an infinite loop, or jump back a few times, and then jump forward past all the content it missed during a live stream.  This example is audio-only stream, but it also occurs with other video streams as well.

Seems to only occur in Chromium browsers.  Also seems odd that vjs debug logs aren't working in Chromium browsers as well.

I have tested that the following players will play back this fine

- mpv
- vlc
- hls.js
- plyr
- gnome videos

If you can point me to an area in the source code where you think there could be an issue it would be much appreciated

## Sources

[Reproduced Error][1]

## Steps to reproduce

1. Click the link to the reproduced error
2. Go to the "Player stats" tab
3. Watch as the current time and segment jump backwards in an infinite loop

### Error output

No errors or warnings ever

### videojs version

tested with several versions including video.js 7.14.3

### videojs http-streaming version

v2.10.3

### Browsers

* affected
  * chrome linux Version 93.0.4577.82 (Official Build) (64-bit)
  * brave linux Version 1.29.80 Chromium: 93.0.4577.63 (Official Build) (64-bit)
  * chrome android
* not affected
  * firefox linux 91.0.2 (64-bit)
  * ios iphone/ipad with native playback

  [1]: https://v2-10-3--videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=false&url=https%3A%2F%2Fstatic.harvister.net%2Fbugs%2Fjump_back_audio%2Findex.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&override-native=true&preload=auto&mirror-source=true

**Comment by gkatsev** [comment]
Looks like https://github.com/videojs/http-streaming/pull/1195 fixes this issue as well.

**Comment by harvister** [comment]
v2.11.0 fixes the jump back / infinite looping issue, but there is a distinct audio crack where the jump back used to happen.  Not sure if anything can be done about this.

https://v2-11-0--videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=false&url=https%3A%2F%2Fstatic.harvister.net%2Fbugs%2Fjump_back_audio%2Findex.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&override-native=true&preload=auto&mirror-source=true
