### ISSUE TITLE
iOS - textTracks

### ISSUE THREAD

**Issue by enricovittorini** [videojs/http-streaming#1210]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
in my code:
the options for the player are:
 ```
       var options = {
            preload: 'auto',
            live: true,
            liveui: true,
            liveTracker: true,
            controls: false,
            muted: true,
            //enableLowInitialPlaylist: true,
            html5: {
                autoplay: true,
                vhs: {
                    overrideNative: true
                },
                nativeAudioTracks: false,
                nativeVideoTracks: false,
                nativeTextTracks: false
            },

        };
```

```
let tracks = player1.textTracks();
let str = tracks[0].activeCues[0].value.uri
```
if I alert "str" on iPad, the result is undefined. While it is working well on windows or android.

I think is the same issue as #214. any solution on this?

### Error output
no error

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
It should be able to work on ipad assuming you're on a recent enough version of ipados. However, it won't work on iphones as MSE, the API that we rely on, isn't available.
Though, just tried https://videojs-http-streaming.netlify.app/ on my ipad and I don't see segment-metadata show up under player stats tab panel. Though, that page isn't overriding the text tracks.

**Comment by enricovittorini** [comment]
thanks for your answer.
is there a way to get the current played segment on iOS?

**Comment by gkatsev** [comment]
So, I think if you set the mode of the track to 'hidden' as early as possible, it should work.
```js
const tracks = player.textTracks();
// assuming that segment-metadata is the first track, it could potentially not be
tracks[0].mode = 'hidden';
```
Afterwards, it should work.
