### ISSUE TITLE
Alternate audio issues should not cause a switch to default

### ISSUE THREAD

**Issue by andreasgan** [videojs/http-streaming#1223]
## Description
Audio selection gets lost when a network request fails. For multilingual content it makes more sense to have a stall than for the audio to switch.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Start a stream with multiple audio tracks. (e.g. https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8)
2. Make an audio request fail (e.g. turn off internet)
3. The audio selection gets changed (to the default).

### Expected
Expected the audio selection to stay the same.

### Error output
Problem encountered loading the alternate audio track

### Relevant code
https://github.com/videojs/http-streaming/blob/297e2c7a47aa60bc59a5e643031cf3e5f7e3632f/src/media-groups.js#L278

### videojs-http-streaming version
videojs-http-streaming 2.12.0

### videojs version
video.js 7.17.0

**Comment by gkatsev** [comment]
The current behavior may be fine and doesn't seem to go against what the spec says (or rather, doesn't say). Using bipbop, the two audio tracks have the same group ID and the same language, and the only thing that differentiate them is the name. I tried a different stream which had different audio tracks with different languages and when I blocked the currently played language, the stream eventually stalled once it ran out of buffer and didn't switch to an alternate rendition.
