### ISSUE TITLE
Chrome incognito iframe - DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by bitactive** [videojs/http-streaming#1237]
## Description
When using videojs+vhs as iframe embedded on another website, Chrome is unable to access localStorage from iframe in incognito mode throwing "Access denied":
```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

This is caused by updateVhsLocalStorage & getVhsLocalStorage tryin to access window.localStorage.

We should wrap code accessing window.localStorage with try/catch block.

## Sources
any

## Steps to reproduce
1. Create any videojs+vhs hls video
2. Embed it as iframe from another domain
3. Open it in Chrome incognito mode.

## Results
```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
### Expected
No error

## Additional Information
We should wrap code accessing window.localStorage with try/catch block.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.12.2

### videojs version
what version of videojs does this occur with?
video.js 7.17.3

### Browsers
Chrome Incognito mode

### Platforms
Windows 10

**Comment by gkatsev** [comment]
Storing and getting from localStorage should only be happening if `useBandwidthFromLocalStorage` is set to `true`. Do you happen to have it set?

**Comment by Mironshoh1603** [comment]
> [`_****_`](`url`)
