### ISSUE TITLE
Do I need to include the videojs-http-streaming.js <script> tag if I'm using video.js 7?

### ISSUE THREAD

**Issue by jaradc** [videojs/http-streaming#1243]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Context
The README for this project says:

> Included in video.js 7 by default

## Question
Does that mean I don't have to include the `videojs-http-streaming.js` script file in HTML?

Ex: Instead of this:

```
<script src="https://unpkg.com/video.js/dist/video.js"></script>
<script src="https://unpkg.com/@videojs/http-streaming/dist/videojs-http-streaming.js"></script>
```

I can just do this:

```
<script src="https://unpkg.com/video.js/dist/video.js"></script>
```

And Videojs HTTP Streaming is included in the video.js file?

Sorry in advance if this question is annoying.

**Comment by mister-ben** [comment]
Correct, http-streaming is already included in the regular video.js/video.min.js so don't add it again.
