### ISSUE TITLE
Mozilla error

### ISSUE THREAD

**Issue by PaulKsi** [videojs/http-streaming#1245]
Hello, All other browsers work just firefox endless spinning wheel? What might be the issue, tried adding type ="application still error remains?

HTTP “Content-Type” of “application/vnd.apple.mpegurl” is not supported. Load of media resource
myurl/video.m3u8 failed. index.html
All candidate resources failed to load. Media load paused.

**Comment by PaulKsi** [comment]
<video id="video" controls="true" preload="auto" class="video-js" muted data-setup='{}'>
        
        <source src="project/stream/video.m3u8">
        </source>

**Comment by mister-ben** [comment]
it's difficult to say without a complete minimal example. The error message is a bit of a red herring - that is Firefox's video element (correctly) saying it can't play the video before Video.js is initialised.

This is loading an HLS source correctly as a starting point: https://codepen.io/mister-ben/pen/bGomOwa?editors=1000
