### ISSUE TITLE
Access the ts (segment) HTTP response

### ISSUE THREAD

**Issue by e1adn** [videojs/http-streaming#1246]
Hi there, 

I am trying to find a way to access the ts (segment) HTTP response.
My backend returns a manifest and I get 200 for it and it looks great.
But the first segment is failed and has some data in the http response I want to access. 

I tried using : 
```js
    player.tech().on('usage', (e) => {
        console.log(e.name, e);
      });
```

But I do not see any data related. 

Also tried and listen to the 'cuechange' like in the READ.ME example. 
But since the first ts is failing the cue is empty, which makes sense.

Is there any way to access it ?

videojs-http-streaming 2.12.0 (come with video.js)
video.js 7.17.0

**Comment by engpakravan** [comment]
where is the answer ?
why this issue closed ?!

**Comment by gkatsev** [comment]
Unfortunately, we do not currently expose the requests or responses themselves.
