### ISSUE TITLE
LL-HLS live streaming can raise MEDIA_ERR_DECODE on change stream quality  

### ISSUE THREAD

**Issue by alessandroliveri** [videojs/http-streaming#1249]
## Description
During a Low-Latency HLS live streaming, switching the stream quality can raise a  MEDIA_ERR_DECODE with a resultant video freeze

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Enable LL HLS and play a live stream from [videojs-http-streaming.netlify.app](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Fbipbop-advanced%2Fbipbop_16x9_variant.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&override-native=true&preload=auto&mirror-source=true)
2. Switch video quality until the error is raised

## Results
Video freezes because of a MEDIA_ERR_DECODE

### Expected
Quality changes and video continue to play

### Error output
ERROR (CODE:3 MEDIA_ERR_DECODE), video append of XXXX failed for segment #0 in playlist 1-YYYY

## Additional Information
![image](https://user-images.githubusercontent.com/4834881/152771239-a821f1ab-b53e-4fce-8879-46cb1262a642.png)

### videojs version
what version of videojs does this occur with?
video.js 7.17.0

### Browsers
what browsers are affected? please include browser and version for each
* Tested on Chrome 98 and Firefox 96 and they raise the same issue

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* MacOS 12.0.1 Apple M1

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*  videojs-contrib-quality-levels 2.1.0
*  videojs-hls-quality-selector 1.1.4

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* React 17.0.2
* NextJS 12.0.9

**Comment by dygy** [comment]
Can we reopen it? :D i think it's more a Safari Mac OS issue with LL-HLS support, but still i guess we should somehow investigate it :D
