### ISSUE TITLE
Improving the wording of a warning. - VIDEOJS: WARN: Using hls options is deprecated. Use vhs instead.

### ISSUE THREAD

**Issue by JamieDawson** [videojs/http-streaming#1256]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

* I get this deprecated warning in the console:
VIDEOJS: WARN: Using hls options is deprecated. Use vhs instead.

This made me think I needed to call on the Getting Started code inside [this repo](https://github.com/videojs/http-streaming)

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Using HLS with videoJS
2. Checking the console and seeing the deprecation warning.

### Expected
To use HLS with no warnings.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:
This is the warning I got in the console:
VIDEOJS: WARN: Using hls options is deprecated. Use vhs instead.

## Additional Information
Please include any additional information necessary here. Including the following:
I was told by Gary Katsevman on the community Slack channel to make this issue so the wording can be improved.
https://videojs.slack.com/archives/C43LGP955/p1646171897832899

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.13.1

### videojs version
what version of videojs does this occur with?
video.js 2.13.1

### Browsers
what browsers are affected? please include browser and version for each
* Chrome, Version 98.0.4758.109 (Official Build) (x86_64)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* macOS Montery Version 12.1
* MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*No.

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* React

**Comment by matteocontrini** [comment]
Isn't this a bug? The warning is shown even if the `hls` option is not specified.

**Comment by gkatsev** [comment]
@matteocontrini can you provide a live minimal test case? Thanks!

**Comment by matteocontrini** [comment]
@gkatsev I then found out that it's the Mux Data plugin that makes use of that parameter even if I'm not using HLS. I'll report to them, there's probably no issue here.

**Comment by dee1cv** [comment]
@istng Hi, yes i am facing that issue could you please please me with this
