### ISSUE TITLE
Consider not downloading manifest when preload=none

### ISSUE THREAD

**Issue by forbesjo** [videojs/http-streaming#126]
https://github.com/videojs/videojs-contrib-hls/issues/955

**Comment by saPhil** [comment]
Has there been any further progress on this issue? I really need the manifest to not be downloaded until the user actually hits the play button.

**Comment by rudyryk** [comment]
Hmm... I experience even worse behavior. It contunues downloading `*.ts` chunks while paused regardless of `preload` value.

**Comment by crutch12** [comment]
Will this be ever resolved?

**Comment by danrossi** [comment]
Is there a way to stop trying to load the master playlist ? This problem causes an issue with livestreams that aren't publishing yet and causes an errorto be dispatched.

**Comment by Meridix** [comment]
We are also seeing the same behavior.  Only way to recover the player (even if user has not taken any action / has not hit play button) is to keep refreshing the entire page until the stream is actually live.

**Comment by gkatsev** [comment]
We'll be fixing it at some point. We plan on aligning behavior with safari meaning that preload=none won't load anything and preload=metadata will only load the manifests.

**Comment by gkatsev** [comment]
As a followup to https://github.com/videojs/http-streaming/pull/978/files#r515206061, we should delay when startABRTimer_ depending on the value of preload. No point in starting the timer if we haven't downloaded any segments yet.

**Comment by gkatsev** [comment]
> As a followup to https://github.com/videojs/http-streaming/pull/978/files#r515206061, we should delay when startABRTimer_ depending on the value of preload. No point in starting the timer if we haven't downloaded any segments yet.

I think this is solved by https://github.com/videojs/http-streaming/pull/1026
