### ISSUE TITLE
[Question] How to limit the m3u8 segments downloaded?

### ISSUE THREAD

**Issue by henriqueleite42** [videojs/http-streaming#1286]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description

I want to limit the download of the `.ts` files of a `.m3u8` video, like this:

1 - The user watches a piece of the video
2 - Some `.ts` files are downloaded (like 2 or 3 files)
3 - The download only continues after the user watches some of the `.ts` files
__3.1 - If the user pauses the video, the download stop

So, instead of downloading everything as fast as possible, download the files progressively as the user watches the video.

This is necessary to don't download segments that the user will not watch.

## Example

1 - The user opens the website and the video starts to load
2 - The `.m3u8` file and the playlist are downloaded
3 - The first 3 segments of the video are downloaded
4 - The user watches 2 of the segments
5 - 3 more segments are downloaded
6 - The user watches 1 segment and stops the video
7 - The download stops and no other segment is downloaded
8 - The user starts the video again and watches one more segment
9 - 3 more segments are downloaded

## May-be-related questions but with no solution

- [[HLS] How to temporarily stop buffering #5312](https://github.com/videojs/video.js/issues/5312)

## "Google searches" to (may) help others to find this question in the future

- videojs m3u8 prevent bandwidth waste
- videojs m3u8 only a few segments at time
- videojs m3u8 preload only a few segments
- videojs m3u8 preload only a few ts files
- videojs m3u8 preload ts files
- videojs m3u8 progressive ts files
- videojs m3u8 preload donwload
- videojs m3u8 delay
- videojs m3u8 add delay
- videojs m3u8 only user watches
- videojs delay loading
- videojs hls delay loading
- videojs hls save bandswitch
- videojs hls temporarily stop buffering
- videojs hls stop buffering

**Comment by gesinger** [comment]
Hey @henriqueleite42 , we don't have any built-in support for such a use-case, but if you need that behavior, you can change the config options in https://github.com/videojs/http-streaming/blob/5223427eac208e50af6285562767111c865d05ac/src/config.js#L2-L3

That should allow setting a max amount of forward buffer, which you can tie to your segment durations.

As for stopping loading entirely while paused, we don't have an API for it right now (and don't have the bandwidth to add it at the moment). If it's something you still need, and would like to work on a PR for it, let us know!

**Comment by henriqueleite42** [comment]
Hello @gesinger,

Sure, I would love to contribute to the project to add such features. How can I start? I'm thinking about making both these variables configurable by the client and maybe adding the feature to completely pause the loading while paused, but I think that it will not be necessary anymore.

And these `GOAL_BUFFER_LENGTH` and `MAX_GOAL_BUFFER_LENGTH` are based on seconds or bytes?

**Comment by gkatsev** [comment]
Exposing the `pauseLoading` on VHS makes sense to me. I looked at it previously and while that's fairly simple, we don't have a good `startLoading` method to continue loading.

**Comment by MrAnon-dev** [comment]
Hi there, 

I am in a similar situation to @henriqueleite42  and I would like put the videojs player on my site with the following logic:

- When the player is visible on browser viewport, play the video (m3u8 HLS live stream)
- When the player is outside the browser viewport, STOP the playback and dowloading chunks for saving bandwith. 

I control the visibility with IntersectionObserver API without any problem, however right now with pause(), the playback stops but chunks keep downloading.

Would be great what @gkatsev says, that pauseLoading startLoading and could be invoked anytime along with pause() and play()  ¿there is any chance to get this?

thanks you all!!
