### ISSUE TITLE
Really quick question onto DRM

### ISSUE THREAD

**Issue by venomone** [videojs/http-streaming#1290]
Hey folks,

I dropped out the default question template as this is very general and not a bug or so.

I use FFMPEG (Version 5.0.1 - Encrypted fmp4 not yet supported \n Could not write header for output file) to generate my HLS streams, The output I generate is in fragmented mp4 format (m4s files). Now, I would also like to encrypt my segments using clearkey protection. But for some reason, FFmpeg does not support this for fragmented mp4, only for ts files ... and ts files again incompatible with HEVC, so im kinda stuck.

Now my actual question:

Is VideoJS compatible with encrypted m4s segments? Im asking because the actuall segments encryption can also be done using OpenSSL I guess.

If Icheck here: https://github.com/videojs/http-streaming/blob/main/docs/supported-features.md and read the section: HLS Missing Features. It seems that SAMPLE-AES segment encryption is not supported. Is that the same as clearkey

Thanks in advance

**Comment by gkatsev** [comment]
Didn't realize that Edge still supported HEVC. Though, their support is dependent on hardware.

**Comment by Murmur** [comment]
See this [stackoverflow answer](https://stackoverflow.com/questions/33632240/how-to-encrypt-webm-or-mp4-file-using-clearkey-and-then-play-it/46897097#46897097). You can use ffmpeg to encode `non-encrypted video.mp4` and then mp4box to write encrypted segment files.
```
MP4Box.exe -crypt gpacdrm.xml temp-v1.mp4 -out ./drm/temp-v1.mp4
MP4Box.exe -crypt gpacdrm.xml temp-a1.mp4 -out ./drm/temp-a1.mp4
MP4Box.exe -dash 6000 -frag 6000 -mem-frags -rap -profile dashavc264:live -profile-ext urn:hbbtv:dash:profile:isoff-live:2012 -min-buffer 3000  -bs-switching no -sample-groups-traf -single-traf -subsegs-per-sidx 1 -segment-name $RepresentationID$_$Number$$Init=i$ -segment-timeline -out manifest.mpd temp-v1.mp4#trackID=1:id=v1:period=p0 temp-a1.mp4#trackID=1:id=a1:period=p0
```
