### ISSUE TITLE
useBandwidthFromLocalStorage is not persistent

### ISSUE THREAD

**Issue by mysuf** [videojs/http-streaming#1292]
## Description
When option `useBandwidthFromLocalStorage` is set to `true`, last setting is properly stored in storage everytime I change quality, but it gets ignored and reseted to initial adaptive setting when page is refreshed. I use videojs-contrib-quality-levels plugin. I tried to remove other options like `limitRenditionByPlayerDimensions`, because I didn't dig into your source code and doesnt know priorities, but it didnt help. Reseting happens without external influences (without plugins, calling any methods etc).

## Sources
```
        html5: {
          nativeAudioTracks: false,
          nativeVideoTracks: false,
          vhs: {
            overrideNative: true,
            limitRenditionByPlayerDimensions: true,
            useDevicePixelRatio: true,
            useBandwidthFromLocalStorage: true,
          },
        },
```
Plugin selects quality by setting poperty `enabled` on each level of videojs-contrib-quality-levels plugin plugin.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. play HLS video with multiple qualities
2. look into localStorage that initial bw is stored
3. change quality and check changes in storage
4. leave open storage table in dev tools and refresh the page
5. play same video and look how value changes

### Expected
It should store bandwidth in local storage only when it's stored first time or when USER selects quality.

### Error output
No errors

## Additional Information
Also I don't think that storing exact bps is best solution because it won't fit on different video even with similar resolution. I would use width or height, because people usually set quality based on single dimension value: f.e. 1080p (both => ratio also isn't best scaling cos 16:9, 16:7 etc but people dont care about it). And it should store also if it's adaptive setting (multiple qualities enabled), f.e. `{ 'width: 1920, auto: true }`

### videojs-http-streaming version
2.14.2

### videojs version
6.13

### Browsers
Chrome

### Platforms
Linux

### Other Plugins
videojs-contrib-quality-levels plugin

**Comment by gkatsev** [comment]
As explained in the docs, [`useBandwidthFromLocalStorage`](https://github.com/videojs/http-streaming#usebandwidthfromlocalstorage) is used for storing the estimated bandwidth and throughput into local storage. These values are then used on initial load to help get a better initial rendition selection.

This is separate from storing the user selected rendition and returning to that rendition later on.

Keeping the selected rendition for next time sounds like a good enhancement request, maybe for the videojs-contrib-quality-levels plugin.

**Comment by mysuf** [comment]
Thanks. Then its purpose is still mystery to me because "initial load" happens also on page refresh. The main feature of localStorage is persistency, but values from localStorage are clearly ignored even that quality with equal bandwidth/throughput is available(same video source) - it uses  automatic selection again. When I think about it, maybe it was caused by multiple hls videos on my page while useBandwithFromLocalStorage use one unified key "player-vhs" (or something like that) - maybe it would be better to use some form of id for each m3u8 source..

Anyway I created own localStorage management on top of quality-levels plugin as you suggested. It was few rows of code..nothing difficult.

**Comment by gkatsev** [comment]
It's there as a signal to help know what the user's estimated bandwidth is likely before VHS gets a chance to check for itself. It's similar to the [NetworkInformation](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation). It allows knowing that if the number is high, we can start directly at a high rendition and if the number is low, we can start at a low rendition. However, once data loading begins, we can have a more correct and more recent estimate from the downloaded segments, since we don't know when the localStorage value was last set.
Hope that this helped clarify what it's used for.
