### ISSUE TITLE
Unable to rewind to the beginning of live HLS after quality change

### ISSUE THREAD

**Issue by LiubomyrY** [videojs/http-streaming#1299]
## Description

For live HLS, after changing the video quality, part of the video becomes unavailable for seek. I found that this issue is connected to the seekable property. When the new quality is selected, seekable start time changes from 0 to the time we change quality. After changing the video quality to the previous value, everything work as expected (the seekable start time becomes 0). All segments from 0 to live edge are available in all playlists.

## Steps to reproduce
The problem is not always reproduced, tried a couple of times.
1. Load player with live HLS which is broadcasting more than 10 minutes.
2. Change quality
3. Rewind to the first minute

## Results
https://user-images.githubusercontent.com/52244384/180766872-bf44aa8a-a7a0-4d2b-91b4-02fb67d1f827.mp4

Player can't rewind to the first minute after quality change
### Expected
Player should rewind to the first minute after quality change

### Error output
There are no errors in the console.

### videojs-http-streaming version
2.14.2

### videojs version
7.19.2

### Browsers
- Chrome
- Safari
- Firefox

### Platforms
- Windows 10
- macOS 12 Monterey

### Other Plugins
- videojs-contrib-quality-levels 2.1.0

**Comment by LiubomyrY** [comment]
Here is example on JSBin https://jsbin.com/taluneqaka/1/edit?html,output
Unfortunately I cant provide stream link, but here is the video of issue. Steps to reproduce are the same

https://user-images.githubusercontent.com/52244384/181474547-93e67874-8534-4724-8e5c-916fe12bc608.mp4

**Comment by gkatsev** [comment]
Does the steam include all 10 minutes of content, or are there only a couple of segments in the manifest? If it's the latter, it isn't possible. If it's the former, it should work.

**Comment by LiubomyrY** [comment]
@gkatsev Stream include all segments for all playlists. I have logged selected playlist while issue reproduced and it contains all segments from 0 to the live edge

![b628e9b3-c58b-4d1f-9e57-ba90bccd7feb](https://user-images.githubusercontent.com/52244384/181718364-bc894d89-74d3-4d6d-8317-d20c15ec3828.png)

Here is attached hls files, they also contain all segments

[index.txt](https://github.com/videojs/http-streaming/files/9218089/index.txt)
[index_1.txt](https://github.com/videojs/http-streaming/files/9218093/index_1.txt)
[index_2.txt](https://github.com/videojs/http-streaming/files/9218096/index_2.txt)
[index_3.txt](https://github.com/videojs/http-streaming/files/9218097/index_3.txt)
[index_4.txt](https://github.com/videojs/http-streaming/files/9218098/index_4.txt)

**Comment by gkatsev** [comment]
Nothing stands about the manifests. Are you able to share your stream? It's not really possible to debug without a sample stream, unfortunately.

**Comment by LiubomyrY** [comment]
Hi, have you had a chance to take a look at this issue? Unfortunately given stream was stopped, I can't keep it running for a long time. Could you please leave comment here, when you will have time to take a look at it, so I can start the stream?
Also I want to mention that stream is running on AWS MediaLive, stored and shared from s3

**Comment by LiubomyrY** [comment]
The issue was resolved by adding the #EXT-X-PROGRAM-DATE-TIME tag to the manifest

**Comment by philipgiuliani** [comment]
Hi, we are having the same issue. As soon as our player switches playlist (automatically, most of the times at the beginning), the liveWindow gets very small.

At the beginning, the seekable looks like this: `[0, 31590]`
After some second, the next playlist gets loaded and it looks like this: `[31598.3, 32754]`

We can assure that the playlist always contains all the chunks in the response. We have no influence over the playlist (cannot add the EXT-X-PROGRAM-DATE-TIME).

I think the `expiry` is calculated incorrectly and all the old chunks get considered expired for some reason.

Probably there is some issue with the syncPoint calculation:
![Screenshot 2023-05-22 at 17 59 29](https://github.com/videojs/http-streaming/assets/5446019/9894a481-37d5-4688-87b0-cb1ff43c3ef4)

![Screenshot 2023-05-22 at 18 00 28](https://github.com/videojs/http-streaming/assets/5446019/d1ef745a-453d-4771-896b-dc631efeb547)

Let me know if you need any other logs or details.
Also, please reopen the issue.

**Comment by philipgiuliani** [comment]
We have removed the "Segment" method in the SyncController, so its just using the Playlist method now, and it's working fine. We are not sure what's the issue with the Segment-Method though.
