### ISSUE TITLE
How to change/overwrite audio track of hls file

### ISSUE THREAD

**Issue by Daxxxis** [videojs/http-streaming#1335]
## Description
I have m3u8 files with one video and multiple audio connected. Currently I have one audio track forced to be default with `DEFAULT=YES` option. The question is how to overwrite this and choose a different audio track as default after loading the player

## Sources
Example playlist (Czech track is the default one here):
```
#EXTM3U

1",NAME="Български",LANGUAGE="bg",AUTOSELECT=YES,DEFAULT=NO,URI="audio/bg/SH_bg.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="čeština",LANGUAGE="cs",AUTOSELECT=YES,DEFAULT=YES,URI="audio/cs/SH_cs.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="Deutsch",LANGUAGE="de",AUTOSELECT=YES,DEFAULT=NO,URI="audio/de/SH_de.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="English",LANGUAGE="en",AUTOSELECT=YES,DEFAULT=NO,URI="audio/en/SH_en.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="Español",LANGUAGE="es",AUTOSELECT=YES,DEFAULT=NO,URI="audio/es/SH_es.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="Français",LANGUAGE="fr",AUTOSELECT=YES,DEFAULT=NO,URI="audio/fr/SH_fr.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="Italiano",LANGUAGE="it",AUTOSELECT=YES,DEFAULT=NO,URI="audio/it/SH_it.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="日本語",LANGUAGE="ja",AUTOSELECT=YES,DEFAULT=NO,URI="audio/ja/SH_ja.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="Nederlands",LANGUAGE="nl",AUTOSELECT=YES,DEFAULT=NO,URI="audio/nl/SH_nl.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="polski",LANGUAGE="pl",AUTOSELECT=YES,DEFAULT=NO,URI="audio/pl/SH_pl.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=1758000,RESOLUTION=1920x1080,AUDIO="audio-1"
video/SH.m3u8
```

### videojs-http-streaming version
videojs-http-streaming 2.15.0

### videojs version
videojs 7.20.3

**Comment by gkatsev** [comment]
The audio tracks are exposed on via `player.audioTracks()`. They should be accessible after `loadedmetadata` has triggered.

**Comment by Daxxxis** [comment]
Yeah, they are visible
![image](https://user-images.githubusercontent.com/60961958/195913203-64903c12-e1ca-4a82-ab7c-73da6dfc7870.png)
What should I change to change the default one?

**Comment by gkatsev** [comment]
You can't really change the default one, but you could change to another track after it's loaded by setting `track.enabled = true`

**Comment by Daxxxis** [comment]
> You can't really change the default one, but you could change to another track after it's loaded by setting `track.enabled = true`
It keeps giving me info that is not defined, I tried to delay the call as much as possible
`Uncaught TypeError: Cannot set properties of undefined (setting 'enabled')`

**Comment by Daxxxis** [comment]
Solved
It was necessary to check readiness of the player
```
player.on('canplay', () => {
    //code
})
```
