### ISSUE TITLE
Support for h.264 videos on Chromium based browsers (jxBrowser)

### ISSUE THREAD

**Issue by ChristopherJohnson25** [videojs/http-streaming#1342]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
I am trying to get h.264 video to play on JxBrowser

## Steps to reproduce
Play h.264 video on open source chromium, observer error code #4

## Results
Video does not play
### Expected
Video should play, or is this is licensing issue?

### Error output
Code: 4

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
videojs-http-streaming 1.2.5

### Browsers
JxBrowser, Open Source Chromium
*

**Comment by misteroneill** [comment]
Unfortunately, JxBrowser is not something we support.

The error code you are receiving - 4 - is a standard HTML error saying that a source is not supported. It is likely that JxBrowser does not support h.264 video. Unfortunately, this isn't something that VHS or Video.js can resolve as it's a browser limitation.
