### ISSUE TITLE
playlist parse error

### ISSUE THREAD

**Issue by dargre** [videojs/http-streaming#1345]
Example playlist file exists, but it is just empty file, or the content of the playlist file is like:

#EXTM3U
#EXT-X-ERROR: Stream open failed
#EXT-X-ENDLIST

The player does not throw any error on playlist parse error. Hls.js does.
Is there any way to catch playlist parse error using VHS?

**Comment by alex-barstow** [comment]
`#EXT-X-ERROR` is a non-standard tag, so our recommendation would be to setup a custom parser to handle it. See this similar issue for a bit more discussion and links to the custom parser docs: https://github.com/videojs/http-streaming/issues/1019
