### ISSUE TITLE
Timed metadata not being triggered on iOS

### ISSUE THREAD

**Issue by berrutti** [videojs/http-streaming#1346]
## Description
Timed metadata is not being triggered on iOS.

## Steps to reproduce

1. Open this page on an iOS device: https://codepen.io/matiasmovingimage/pen/zYyBawK
2. Press the play button, play some seconds

### Expected
Open the same page on Chrome on desktop and you will see the console output below the player:

```
----Add track callback executed----
----Add track callback executed----
----Add track callback executed----
----Add track callback executed----
----Add track callback executed----
----Add track callback executed----
----Add track callback executed----
{"cues_":[{"frame":{"id":"TXXX","data":" *** THIS IS Timed MetaData @ -- 00:00:00.0 *** ","key":"TXXX","description":"","value":" *** THIS IS Timed MetaData @ -- 00:00:00.0 *** "},"value":{"id":"TXXX","data":" *** THIS IS Timed MetaData @ -- 00:00:00.0 *** ","key":"TXXX","description":"","value":" *** THIS IS Timed MetaData @ -- 00:00:00.0 *** "}}],"length_":1}
...
```

### Current
On iOS, only the first part is printed on this "console", the timed metadata information is not printed.
Active cues information is empty.

### Error output
No errors

### videojs-http-streaming version
Latest

### videojs version
Latest

### Browsers
Chrome, Safari

### Platforms
iOS (iPhone 13)

### Other Plugins
None

### Other JavaScript
React

**Comment by berrutti** [comment]
Hey @mister-ben 
Yes, the stream was down. I started it again. Will try to keep it running all the day today

**Comment by misteroneill** [comment]
As an open source project with limited resources, it's very unlikely we will be able to investigate issues reported the same day (or week, or month). Is there a way you could capture part of the stream that reproduces the issue?

Also, on iOS, it seems unlikely that VHS is even in use since that platform does not support MSE.

**Comment by berrutti** [comment]
Hey @mister-ben @misteroneill 
I changed a bit the issue, since I still don't have a Wowza recording I can share with you. 
In this case I used Apple's official HLS testing URLs to show an empty timed metadata cue.
Please let me know if this is useful.

Happy holidays.

**Comment by mister-ben** [comment]
On iOS the track's mode starts out `disabled`. If you set it to `hidden` then cues are parsed and `cuechange` events occur. `JSON.stringify()` can't parse a native `DataCue` however.
