### ISSUE TITLE
Is there a way to know the segment information of the video currently being played in hls live?

### ISSUE THREAD

**Issue by dnxodl1001** [videojs/http-streaming#1349]
Hello this is Steve.

Is there a way to know the segment information of the video currently being played in hls live?

Also, I would really appreciate it if you could tell me if I could catch the event of cue-out, cue-in, and discontinuity of the currently playing video.

**Comment by gkatsev** [comment]
Take a look at the segment metadata text track https://github.com/videojs/http-streaming#segment-metadata
It shows information about the currently playing segment.

**Comment by dnxodl1001** [comment]
Hello This is Steve.

Thank you for your kind reply.

I'm asking you again because I think it's right to use the contents you answered like this.

After using it like this, too many logs of the same data are taken as shown in the picture below.

I don't think this is how you use it, so I'd appreciate it if you could give me a simple guide!

Thank you.

![image](https://user-images.githubusercontent.com/117717284/203182816-403b1e62-7a8e-43ae-91ca-4e6aff58bf50.png)

![image](https://user-images.githubusercontent.com/117717284/203182828-86876ee1-ea5a-4ce4-a32b-529e345085b5.png)

**Comment by gkatsev** [comment]
You don't want to add the cuechange handler inside a progress event. You want to register it once on the loadedmetadata event instead. The progress event gets triggered a bunch when new data is loaded.

**Comment by dnxodl1001** [comment]
Thank you for your quick reply.
As you said, we proceeded with the loadmetadata event, and in this case, it occurred only once and did not occur after that.
What I want is to know only the current cements when the cue changes, so can we schedule another event and proceed?

I'd appreciate it if you could answer.

**Comment by victordidenko** [comment]
Stumbled upon this, that event `cuechange` doesn't get fired.
Looks like text track `segment-metadata` is disabled (`.mode == 'disabled'`), which is understandable, it should be visible on the screen, but this also stops tracking for this track.
After I manually call `.startTracking()` on a `segment-metadata` track, event `cuechange` started firing.
Looks like lack in the documentation, or a bug to me.

**Comment by victordidenko** [comment]
Strange though, that changing mode to `'hidden'` in a `'loadedmetadata'` event doesn't work — mode got changed back to `'disabled'` by player, don't know why. I can change it back to `'hidden'` in timeout after ≈ 70-100 ms, but this looks like bad ad hoc solution.

**Comment by misteroneill** [comment]
The `segment-metadata` track should be `hidden` by default, not `disabled`. You can see this on [the reference app](https://videojs-http-streaming.netlify.app/).
