### ISSUE TITLE
4K Stream Fails to Play on Tizen When Not Using AVPlay Native Player

### ISSUE THREAD

**Issue by turbidwater** [videojs/http-streaming#1354]
## Description
On a Tizen 4K TV, I can play a 4K asset with only 4K renditions when video.js is using the underlying native AVPlay player. However, when I turn native playback off, video.js throws the following error when trying to play the same asset:
`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.`

The setup is simple. 
```
const videoRef = useRef<HTMLVideoElement>(null);
const url = "https://cdn.bitmovin.com/content/demos/4k/38e843e0-1998-11e9-8a92-c734cd79b4dc/video_25000000.m3u8";
const videoJsOptions: any = {
    autoplay: false,
    controls: true,
    html5: {
      vhs: {
        overrideNative: true,
      },
      nativeAudioTracks: false,
      nativeVideoTracks: false,
      nativeTextTracks: false,
    },
    sources: [
      {
        src: url,
      },
    ],
  };
const player = new (videojs as any)(videoRef.current, videoJsOptions);
<video
        ref={videoRef}
        className="video-js vjs-big-play-centered"
        width={480}
      ></video>
```
With this set up, it will throw the error about unsupported content. If you comment out the html5 block of the config so it uses the native player, the content will play. Furthermore, using a 1080p rendition of the same asset will play: https://cdn.bitmovin.com/content/demos/4k/38e843e0-1998-11e9-8a92-c734cd79b4dc/video_5800000.m3u8. The manifest for the entire ABR asset is here: https://cdn.bitmovin.com/content/demos/4k/38e843e0-1998-11e9-8a92-c734cd79b4dc/manifest.m3u8

## Sources
4K: https://cdn.bitmovin.com/content/demos/4k/38e843e0-1998-11e9-8a92-c734cd79b4dc/video_25000000.m3u8
1080p: https://cdn.bitmovin.com/content/demos/4k/38e843e0-1998-11e9-8a92-c734cd79b4dc/video_5800000.m3u8
Full ABR asset: https://cdn.bitmovin.com/content/demos/4k/38e843e0-1998-11e9-8a92-c734cd79b4dc/manifest.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load a 4K only asset in video.js in a Tizen web app or the Samsung browser on a Tizen TV.
2. The asset will fail to play and throw an error when it attempts to preload the first few segments.

### Expected
I would expect playback of a 4K asset using the video.js MSE player

### Error output
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
videojs-http-streaming 2.14.3

### videojs version
what version of videojs does this occur with?
video.js 7.20.3

### Browsers
what browsers are affected? please include browser and version for each
* Tizen web app based on Chromium 76.0.3809.146
* Samsung Browser 4.0

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Tizen 6.0 (2021)

### Other Plugins
* None

### Other JavaScript
* React

**Comment by turbidwater** [comment]
This turns out to be an issue across MSE-based frameworks, so it's probably something with the underlying Tizen platform. The solution ended up being to use h.265/hevc content rather than h.264. Even though tizen says it supports the avc1/aac combo, it appears HEVC is necessary for non-AVPlay 4K content.

**Comment by mister-ben** [comment]
Thanks for reporting back your findings!
