### ISSUE TITLE
Airplay not working with overrideNative : true

### ISSUE THREAD

**Issue by damanV5** [videojs/http-streaming#1358]
I am using @silvermine/airplay library for casting. I am facing issue while connecting to airplay. It immediately disconnects if I am casting with overrideNative flag set to true. 

I have set the overrideNative:true as without this I am unable to get the 'vhs' inside the tech Object present in player instance, which is required to get the available rendition.

videojs version: 7.20.3
silvermine/airplay version: 1.1.0
Configuration:
```
html5: {
        vhs: {
          overrideNative: false
        },
```

**Comment by mister-ben** [comment]
I suspect Airplay itself doesn't support a video is played by media source extensions (including VHS) rather than natively.

**Comment by gkatsev** [comment]
airplay doesn't support MSE, however, an airplay plugin could handle it by say creating a new video element with the original m3u8 and passing the airplay request onto it, or swapping from MSE playback to native m3u8 playback.

**Comment by gkatsev** [comment]
The default is to not overrideNative on safari browsers. you can also set it to something like `!videojs.browser.IS_ANY_SAFARI`

**Comment by gkatsev** [comment]
Definitely possible for it to handle it, though, it's a workaround.

**Comment by damanV5** [comment]
Okay, Thankyou.
