### ISSUE TITLE
MP3/HLS initialization error (video.js v7.20.3)

### ISSUE THREAD

**Issue by gjactat** [videojs/http-streaming#1359]
## Description
Using video.js v7.20.3, MP3/HLS audio playback fails with an error (VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists).

The same stream is successfully played when I include the plugin "videojs-hlsjs-plugin.js". Which seems a bit strange because [HLS is fully supported without any additional plugin since v7](https://videojs.com/blog/video-js-7-is-here/).

## Sources

- Codepen where playback is OK : https://codepen.io/gjactat/pen/KKBWXRz
- Codepen where playback is NOT OK : https://codepen.io/gjactat/pen/ExpWoEV

These two Codepens only differs from the included set of javascript files (see menu settings > JS)

## Question

Do I still need to include "videojs-hlsjs-plugin.js" or maybe there is something wrong with the stream ?

**Comment by mister-ben** [comment]
Unfortunately HLS with MP3 audio is not supported.

**Comment by gjactat** [comment]
Thank you for your answers. For now, I will continue to include "videojs-hlsjs-plugin".
I'll keep an eye on the changelogs and test from time to time to see if it's still necessary.
