### ISSUE TITLE
VHS not trying to play highest resolution rendition despite sufficient bandwidth

### ISSUE THREAD

**Issue by clintonbosch** [videojs/http-streaming#1361]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Not sure if I am not understanding something but I have noticed when playing an HLS stream that the player does not (ever) change to the highest bandwidth rendition in the manifest despite having sufficient bandwidth >200mbps.
It is quite simple to reproduce using the provided hls stream below you can test the stream in a VHS player and then I tested it in another player (bitmovin) and I did play the highest rendition.

## Sources
If you use the following source https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 with the following renditions in the ABR ladder

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2149280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=1280x720,NAME="720"
url_0/193039199_mp4_h264_aac_hd_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=246440,CODECS="mp4a.40.5,avc1.42000d",RESOLUTION=320x184,NAME="240"
url_2/193039199_mp4_h264_aac_ld_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=460560,CODECS="mp4a.40.5,avc1.420016",RESOLUTION=512x288,NAME="380"
url_4/193039199_mp4_h264_aac_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=836280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=848x480,NAME="480"
url_6/193039199_mp4_h264_aac_hq_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6221600,CODECS="mp4a.40.2,avc1.640028",RESOLUTION=1920x1080,NAME="1080"
url_8/193039199_mp4_h264_aac_fhd_7.m3u8

## Steps to reproduce
Testing the abovementioned hls stream in VJS in https://codepen.io/DJ-PD/full/bGNwQYe and monitoring the network tab shows that I never get promoted to the fhd rendition. I my case I only ever see the hq_7 (480) rendition

However when testing the same stream in https://bitmovin.com/demos/stream-test?format=hls&manifest=https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8 and again watching the network tab I can see that I am watching the fhd_7 (1080) rendition

### Expected
Since I have a 200mbps connection I would have expected VHS to promote me watching experience automatically to the highest rendition in the ABR

## Additional Information
If I manually change the resolution using the quality selector plugin at the bottom right of the player then I am easily able to watch the 1080 rendition, but as soon as I change to auto again it reverts back to 480.

**Comment by phloxic** [comment]
Did you check in fullscreen? Seems to work fine when I go fullscreen with your sample on the [test page](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true) on a large enough display.

By default [limitRenditionByPlayerDimensions](https://github.com/videojs/http-streaming#limitrenditionbyplayerdimensions) is `true`, so you could set it to `false`, at least for checking.

**Comment by mister-ben** [comment]
To add to what @phloxic said, there's some info [here](https://github.com/videojs/http-streaming/blob/main/docs/bitrate-switching.md) on how the player size factors into the rendition selection.

**Comment by clintonbosch** [comment]
THANK YOU  both so much for clearing this up!!!
