### ISSUE TITLE
[CDN error ]Uncaught TypeError: Class constructor Component$1 cannot be invoked without 'new'   at new VhsHandler

### ISSUE THREAD

**Issue by zkkysqs** [videojs/http-streaming#1365]
## Description
My project used the same way as the [Demo](https://jsbin.com/gejugat/edit?html,output) did, it worked well before, but it failed now. Maybe something have been changed these days.

the erro: 
`Uncaught TypeError: Class constructor Component$1 cannot be invoked without 'new'   at new VhsHandler`

![image](https://user-images.githubusercontent.com/53967857/216009953-94bc1548-88a1-43da-83e7-ac264615c63d.png)

I need the videojs cdn  and http-streaming cdn to play .m3u8 video, please update the right cdn width right version link, thks.

By the way,  you will find nothing on [cdnjs.com](https://cdnjs.com/libraries?q=http-steaming) with `?q=http-steaming`, could it be uploaded to this cdn ?

### Expected
1.cdn url: videojs and http-streaming should be compatible with each other
2. upload  http-streaming to https://cdnjs.com/libraries

**Comment by zkkysqs** [comment]
solutions: 

`
<script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.21.1/video.min.js"></script><script src="https://unpkg.com/browse/@videojs/http-streaming@2.6.0/dist/videojs-http-streaming.min.js"></script>
`

**Comment by zkkysqs** [comment]
I has fixed my project, but the [Demo](https://jsbin.com/gejugat/edit?html,output) not

**Comment by mister-ben** [comment]
You should only be adding the http-streaming (VHS) script if using a version of Video.js less than 7, as version 7 upwards includes a version of VHS. Or in edge cases, if you need to combine a particular version of Video.js and VHS, in which case it would be the alt/core version of Video.js you'd need to use. That codepen example is unfortunately outdated.

Basically, just use the video.min.js and omit the VHS script.

**Comment by pmanyehthinkyes** [comment]
> 

Thank You!!!

**Comment by Baytars** [comment]
> solutions:
> 
> ```js
> <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.21.1/video.min.js"></script>
> 
> <script src="https://unpkg.com/browse/@videojs/http-streaming@2.6.0/dist/videojs-http-streaming.min.js"></script>
> ```

It's `https://unpkg.com/@videojs/http-streaming@2.6.0/dist/videojs-http-streaming.min.js`, not `https://unpkg.com/browse/@videojs/http-streaming@2.6.0/dist/videojs-http-streaming.min.js`. The difference is the string `/browse`, it will return a HTML page and rejected by the browser instead.
