### ISSUE TITLE
live example does not work on chrome

### ISSUE THREAD

**Issue by matti** [videojs/http-streaming#1378]
<img width="2055" alt="image" src="https://user-images.githubusercontent.com/3893/222683919-55dfc807-28aa-4f23-be96-6ccfc13d7fb7.png">

**Comment by matti** [comment]
works in Safari though

**Comment by amtins** [comment]
@matti try to remove this line

```
  <script src="https://unpkg.com/@videojs/http-streaming/dist/videojs-http-streaming.js"></script>
```
