### ISSUE TITLE
Why does emsg ID3 metadata only work if it's on a video track?

### ISSUE THREAD

**Issue by tari-hi** [videojs/http-streaming#1379]
## Description
As currently developed, the video track must be present to get the emsg ID3 metadata. If you check the development source, if the audio track contains emsg ID3 metadata, it will not be processed. Is there a reason for this development? Is there a plan to process emsg ID3 meta regardless of audio track and video track?

## Sources
https://github.com/videojs/http-streaming/blob/main/src/media-segment-request.js#L503

### videojs-http-streaming version
videojs-http-streaming 3.1.0

**Comment by adrums86** [comment]
@tari-hi Here's the pull request for the fix: https://github.com/videojs/http-streaming/pull/1385. Do you have any sample media available for verification?
