### ISSUE TITLE
Request sidx defined segments from DASH SegmentBase streams

### ISSUE THREAD

**Issue by sevagsim** [videojs/http-streaming#162]
The following test file cannot be played in the reference player:

https://dash.akamaized.net/dash264/TestCases/10a/1/iis_forest_short_poem_multi_lang_480p_single_adapt_aaclc_sidx.mpd

**Comment by forbesjo** [comment]
Looks like the segment list is not being generated correctly by our mpd parser

**Comment by omarroth** [comment]
For segment base streams only the initialization segment is provided by the manifest, which mpd-parser provides. It seems to me then that there is a problem in http-streaming with fetching the initialization segment and getting info about the rest of the media.
