### ISSUE TITLE
Support for Widevine HLS with SAMPLE-AES-CENC tag

### ISSUE THREAD

**Issue by forbesjo** [videojs/http-streaming#173]
This is a ticket for supporting for Widevine HLS.
Here's an example stream generated by Shaka https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8
Spec https://storage.googleapis.com/wvdocs/Widevine_DRM_HLS.pdf

**Comment by trungtran0689** [comment]
Hello,
Any update for this?

**Comment by gkatsev** [comment]
This is supported now via the changes introduced via https://github.com/videojs/http-streaming/pull/629 and https://github.com/videojs/m3u8-parser/pull/88 which was released as part of 1.11 of VHS.
