### ISSUE TITLE
Install problem.

### ISSUE THREAD

**Issue by erald** [videojs/http-streaming#191]
## Description
having problems to install this module or build.

## Steps to reproduce
npm install --save @videojs/http-streaming
npm ERR! addLocal Could not install videojs/http-streaming
npm ERR! Error: ENOENT, stat 'videojs/http-streaming'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-696.30.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "--save" "@videojs/http-streaming"
npm ERR! cwd /root/node_modules/videojs
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! path videojs/http-streaming
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/node_modules/videojs/npm-debug.log
npm ERR! not ok code 0

When using the build option after cloning 
npm i
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "@videojs/http-streaming"
npm ERR!     at ensureValidName (/usr/lib/node_modules/normalize-package-data/lib/fixer.js:281:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/node_modules/normalize-package-data/lib/fixer.js:196:5)
npm ERR!     at /usr/lib/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/node_modules/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/lib/node_modules/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/node_modules/read-package-json/read-json.js:299:40
npm ERR!     at fs.js:272:14
npm ERR!     at /usr/lib/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-696.30.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "i"
npm ERR! cwd /downloads/http-streaming
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /downloads/http-streaming/npm-debug.log
npm ERR! not ok code 0

### videojs version
what version of videojs does this occur with?
video.js latest

**Comment by gesinger** [comment]
Hey @erald , it looks like you're using pretty old versions of node and npm. Would you be able to upgrade and try again?

**Comment by erald** [comment]
That was it. seems eel had an old version of nodejs.. :(

now it is working thanks saved me a lot of time

**Comment by gkatsev** [comment]
If you use `nvm`, a lot of our projects use [`.nvmrc` files](https://github.com/videojs/http-streaming/blob/master/.nvmrc) to state which node version to use, then you can run `nvm use` and it'll switch to the version in the `.nvmrc` file.
