### ISSUE TITLE
Does This Player Support DRM

### ISSUE THREAD

**Issue by vitaliy-shahanyants** [videojs/http-streaming#197]
## Description
Hello everyone, I have Widevine encrypted stream. I can't find any documentation on DRM support for this API.

In the videojs we use "keySystemOptions" property to push our DRM keys to the player.

Is there function or a property I can send my keys to, or perhaps is there an external library I can load to support DRM functionality.

Looking forward to your answer.

Thank you

**Comment by gesinger** [comment]
Hey @vitaliy-shahanyants , we built https://github.com/videojs/videojs-contrib-eme for exactly this reason! Please let us know if you have any trouble with it. Hope this helps.
