### ISSUE TITLE
player.textTracks() empty in iOS

### ISSUE THREAD

**Issue by Hayko-1** [videojs/http-streaming#214]
player.textTracks() empty in iOS
this worked in videojs v6 and videojs-contrib-hls, not working now

**Comment by forbesjo** [comment]
On iOS this library is not in use so we do not control how the text tracks are populated. Do you have example pages where this is working and is not working for comparison?

**Comment by Hayko-1** [comment]
@forbesjo [https://jsbin.com/xuyoxopiju/edit?html,console,output](https://jsbin.com/xuyoxopiju/edit?html,console,output)

**Comment by Hayko-1** [comment]
@forbesjo maybe you can help me finding other way how to get the current segment name (activeCue.value.uri) that is playing?

**Comment by forbesjo** [comment]
We are unable to get the segment information in iOS and populate that track because the platform doesn't support MSE and instead we defer to the browser's native HLS support.
