### ISSUE TITLE
cuechange listener triggered incorrectly

### ISSUE THREAD

**Issue by izzangalaxybyte** [videojs/http-streaming#218]
## Description
When the first time the cuechange listener is invoked, it is called at the extact time of injection. When the second one is recieved, cuechange is triggered twice. once at an incorrect time then the second at the correct time.

Code:
var trackElements = player.textTracks();
track.addEventListener("cuechange", function () {
//stuff to do when cuechange is called
}

### Expected
There should be another listener for cueexit which is triggered at the correct time.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.2.4

### videojs version
what version of videojs does this occur with?
video.js 7.2.2

### Browsers
what browsers are affected? please include browser and version for each
all browsers

### Platforms
what platforms are affected? please include operating system and version or device and version for each
all platforms

**Comment by gkatsev** [comment]
`cuechange` works as is defined in the HTML specification where it is triggered whenever a cue becomes active or inactive. Meaning, for a given cue, you'll get two `cuechange` events: once when the cues enters, and once when the cue exists.
On cuechange, you should ask the text track for the activeCues and then handle things depending on whether the cue you want is currently active or not.

**Comment by gesinger** [comment]
Thanks for answering @gkatsev !
