### ISSUE TITLE
If Livestream is disconnected and re-connected from streaming server, stream resumes in player after long delay 

### ISSUE THREAD

**Issue by allah1hesundus123456** [videojs/http-streaming#223]
**Description**
If Livestream is disconnected i-e input for streaming server (e.g Wowza) stops for 6-7 minutes, player starts buffering.
 1. When Livestream is connected/resumed, browser network tab shows m3u8 file calls with status code 200 but stream playback resumes in player after 16-30 mins 
 2. Player does not show buffering symbol

Player should resume playback without delay. Can I use any function to detect that stream is again available after disconnection and another function to resume the stream?
Buffering symbol should be displayed until playback is resumed

**Sources**
Any Livestream will work.

**Steps to reproduce**

1. Start Livestream 
2. Stop input of streaming server for 6-7 mins
3. Start/resume input of streaming server 

 **Results Expected**
1. Stream should resume without delay
2. Buffering symbol should be displayed until playback is resumed

**Error output**
1. Stream starts after 16-30 mins
2. Buffering symbol does not appear

**Additional Information**

videojs-http-streaming version
videojs-http-streaming 1.2.4

videojs version
video.js 7.2.2

**Browsers**
what browsers are affected?
1. all browsers
2. Windows Chrome and MAC Firefox

**Platforms**
Desktop Windows, MAC, Android tablets and phones, IPad and IPhone

**Comment by forbesjo** [comment]
We'll see if we can reproduce this with one of our test live streams. It may take us a bit before we take a look at this

**Comment by nicklive** [comment]
Hi, guys!
I have a similar issue with my video streams with latest video.js, plese check out issue, that I openned at mux.js: https://github.com/videojs/mux.js/issues/223
My workaround is to downgrade to 7.1.0 where mux.js without this bug. 
Can you confirm that my issue related to this?

**Comment by forbesjo** [comment]
We believe this has been fixed with one of our previous updates, closing.
