### ISSUE TITLE
Cue Exit does not trigger for id3 metadata tracks

### ISSUE THREAD

**Issue by sundus190** [videojs/http-streaming#230]
**Description**
Cue Exit event does not dispatch for cues in metadata tracks.

I am using it as:

videoContent = videojs('contentElement');
videoContent.ready(function () {
  videoContent.textTracks().addEventListener('addtrack', function (addTrackEvent) {
  var trackElements = videoContent.textTracks(); 
  var track = trackElements[0];
  track.mode = 'hidden';
  track.oncuechange = function () {
  if (track.cues.length <= 0) return;
  var cue = track.cues[0];
  cue.onexit = function (e) {
  console.log("cueexit", e);
      };
    };
   }, false);
  });

Cue Change triggers but Cue Exit does not. please let me know what I have missed? CueChange is triggered for cue enter and cue exit events but I want to listen to cue exit events only as I am working with id3 metadata Tracks.

**Sources**
Any Livestream with metadata Tracks will work.

**Steps to reproduce**
Start Livestream.
Inject id3 metadata
CueChange works but Cue Exit is never dispatched

**Results Expected**
Cue Exit should be triggered

**Error output**
Cue Exit event does not dispatch for cues in metadata tracks.

**Additional Information**
videojs-http-streaming version
videojs-http-streaming 1.2.4

videojs version
video.js 7.2.2

**Browsers**
all browsers

**Platforms**
Desktop Windows, MAC, Android tablets and phones, IPad and IPhone

**Comment by gesinger** [comment]
@gkatsev , I saw you mentioned that we have two `cuechange` events for each cue (one when it starts, and one when it ends) at https://github.com/videojs/http-streaming/issues/218#issuecomment-418486102 . I also saw that the w3c spec has `enter` and `exit` events. Is it just that browsers don't have support for these, and instead rely on `cuechange` alone?

**Comment by sundus190** [comment]
I am testing in firefox browser of iphone 6s, cue change is triggered before time. i-e if metadata is injected at some point in stream, cuechange is triggered 4-8secs before stream reaches that(injected metadata) time in player. This issue does not occur always. But it occurs quite oftenly.
Issue is present if I use
    videojs.options.hls.overrideNative = true;
    videojs.options.html5.nativeAudioTracks =false;
    videojs.options.html5.nativeVideoTracks =false;

or I do not set any options.
Please let me know where I am mistaken or I have missed something.

**Comment by gkatsev** [comment]
What is the start and end time for the cue? If you have an example, that would be even better.
You should be getting two cuechange events for each cue. Once when the cue becomes active and once when the cue becomes inactive.

**Comment by sundus190** [comment]
Thanks for your quick response. I am actually stuck in this issue. I noticed same behavior in Chrome browser of iphone. Should I use 
videojs.options.hls.overrideNative = true;
videojs.options.html5.nativeAudioTracks =false;
videojs.options.html5.nativeVideoTracks =false;
or I dont need to use these options.
In src/js/tracks/text-track.js inside function addCue(originalCue), if I print(console.log) originalCue start and endtime for cue is same. It is id3 timed metadata TXXX. In function activeCues: { ... if (cue.startTime <= ct && cue.endTime >= ct) {
if I print (console.log) cue its start time remains same but end time is large value/exponential value e.g 1.79865389e+308.

**Comment by sundus190** [comment]
I am using native texttracks in safari of iphone 6s and videojs emulated texttracks in windows chrome. Cue start time is same in both browsers. In chrome cuechange is triggered at time but in safari cuechange is triggered before time. This issue is mostly visible when stream is playing with 1-2 min latency in safari of iphone. how can I fix this issue?
How videojs uses native texttracks? Where can I view this code? I want to know how videojs decides active cues for native texttracks?

**Comment by sundus190** [comment]
I am not setting options so videojs will use default texttracks. I dont see any logs from src/js/tracks/text-track.js so it seems as native textttracks are used
