### ISSUE TITLE
7.2.0 to 7.2.4 playback does not restart with loop

### ISSUE THREAD

**Issue by Everlag** [videojs/http-streaming#231]
## Description
Video fails to play after its reaches the end. This also breaks looping.
Briefly describe the issue.

Repro:
http://jsbin.com/kamavaduru/1/edit?html,output

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
1. Start video
1. Let video end(seeking to near end is fine); play button should change to replay

### Expected
Video continues playback at start

### Error output
Spinner appears and does not go away

## Additional Information
A related issue where playback could not be manually restarted by clicking `play` was solved in 1.2.5
https://github.com/videojs/video.js/issues/5436

### videojs-http-streaming version
videojs-http-streaming 1.2.5 (Pinned version for video.js 7.2.3; latest as of 9/14/2018)

### videojs version
7.2.3

### Browsers
* chrome
Others may be affected but chrome is used for baseline sanity checking

### Platforms
* Ubuntu 18.04
* Windows 10

### Other Plugins
None

### Other JavaScript
None(yes in production, no in repro above)

**Comment by gesinger** [comment]
Thanks for posting. We recently changed some logic around listening for seeking events, and it looks like that caused this issue. We'll take a look into it.

**Comment by Everlag** [comment]
Any news on this issue?

**Comment by kalieye** [comment]
if anyone is interested i developed a little workaround (it's hacky but it seems to work) which i'm going to use until an official patch (i will also try to work on something better but i have little hope :)

my fork is here: https://github.com/kalieye/video.js

basically i added this code to the remainingTimeDisplay function in player.js plus a endCalled variable to avoid multiple calls to the same handler, i have not tested the solution extensively so i don't know the repercussions with other formats etc but it works for my case and might be helpful for others

```
    rT = Math.floor(this.duration()) - Math.floor(this.currentTime());
    if (rT == 0 && !this.endCalled) {
      this.endCalled = true;
      this.handleTechEnded_();
    }
```

**Comment by mister-ben** [comment]
This fixes the issue, but relies on the `seeking` event. Given #161 was about "not relying on unreliable seek events", is this viable?

 https://github.com/videojs/http-streaming/compare/master...mister-ben:fix-loop

**Comment by gkatsev** [comment]
It is possible that we may need your piece of code in VHS @mister-ben. While seeking events are unreliable, I can't think of any other way of handling this specific use-case. Plus, even with #161, we can use middleware for user seeking and seek events for loop and other edge cases that can't be covered by middleware.
