### ISSUE TITLE
Microsoft Smooth Streaming (MSS) Support

### ISSUE THREAD

**Issue by goatandsheep** [videojs/http-streaming#241]
I need to support Microsoft Smooth Streaming (MSS) with my project. I don't have to use this package, but I've had better success with it within my project than using `videojs-contrib-hls` and `videojs-contrib-dash` together. I'm open to making pull requests if that is necessary.

**Comment by gkatsev** [comment]
I'm not sure we want to have MSS support built-in. However, as we discussed in slack, making the parser be pluggable sounds like a good idea. Then instead of baking in each type of parser, as long as the parser outputs what VHS expects, it can be used to stream.
Would be good to make a "formal" spec of the parser output.

**Comment by goatandsheep** [comment]
Can we just fork [videojs/mpd-parser](https://github.com/videojs/mpd-parser) and then replace the parser with [mss-parser from dash.js](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/mss/parser/MssParser.js)?

**Comment by goatandsheep** [comment]
https://github.com/goatandsheep/mss-parser

**Comment by hrehman200** [comment]
Has someone any idea how can I utilise this mss-parser to actually play Microsoft's Smooth streams ?

**Comment by goatandsheep** [comment]
@hrehman200 I stopped working on it as it was deprioritized on our team. If you want to work on it I'd be happy to add you as a collaborator

**Comment by hrehman200** [comment]
@goatandsheep I mean after this parser is complete, what are the steps to integrate it in videojs so that videojs can play the Smooth stream.

**Comment by goatandsheep** [comment]
@hrehman200 my intention was to use the same api as the mpd parser of the dash videos player

**Comment by gkatsev** [comment]
If you can create a parser that outputs the same type of object as mpd-parser (and m3u8-parser) you can provide it to Video.js/VHS as a source object. See https://github.com/videojs/http-streaming#object-as-source.

Unfortunately, we don't have the bandwidth to add anything else to support this at this time.
