### ISSUE TITLE
Fails to load/play azure streaming url

### ISSUE THREAD

**Issue by manjudr** [videojs/http-streaming#244]
## Description
Unable to play the azure streaming video urls 
Will this support to play the azure streaming urls?

Sample URL:  

1. http://sunbirdspikemedia-inct.streaming.media.azure.net/afcc5a99-d0c4-4ef5-9dfe-dc403a1269fb/learn-colors-with-numbers-in-kid.ism/manifest(format=m3u8-aapl-v3)

2. http://sunbirdspikemedia-inct.streaming.media.azure.net/afcc5a99-d0c4-4ef5-9dfe-dc403a1269fb/learn-colors-with-numbers-in-kid.ism/manifest(format=m3u8-aapl)

### Error output
<img width="1280" alt="screen shot 2018-10-03 at 6 30 43 pm" src="https://user-images.githubusercontent.com/16288575/46411871-7af97700-c73a-11e8-8e96-90ae91752b4a.png">

**Comment by bcdarius** [comment]
It looks like you're loading the stream over http while the player in your jsbin is loaded over https. Most browsers will block http resources as mixed content. If you intend to serve the player on secure pages you'll need to switch the stream url to https. 

The second issue — not sure if this was copy&paste mistake — you provided HLS streams as examples but in your jsbin you're actually loading MS Smooth Streaming asset with `application/x-mpegURL`. This type will work only with HLS. MSS protocol is, unfortunately, not supported in VHS, at this time. 

For HLS streams, however, you just need to change the stream url to use https https://jsbin.com/lofilanihe/edit?html,output

**Comment by manjudr** [comment]
@bcdarius  Thank you so much for your response :-)

So you are saying  `MS  Smooth Streaming` url is not supported by `videojs http-streaming` am i right?

**Sample Smooth Streaming URL:** http://sunbirdspikemedia-inct.streaming.media.azure.net/afcc5a99-d0c4-4ef5-9dfe-dc403a1269fb/learn-colors-with-numbers-in-kid.ism/manifest 

But I have mentioned the two streaming url's in the description. The first url is working fine after changing to `https`.  But the second format type url is not loading  the video even after changing to `https`. 

URL Link: https://sunbirdspikemedia-inct.streaming.media.azure.net/afcc5a99-d0c4-4ef5-9dfe-dc403a1269fb/learn-colors-with-numbers-in-kid.ism/manifest(format=m3u8-aapl)

Am I doing something wrong?

**Comment by bcdarius** [comment]
I seem to be getting the same issue with your second stream, too. Segments are being downloaded but no playback. 

The only difference I observed between these streams is the HLS version — the first one is v3 while the other one is v4. Looks like the same issue as #177.
