### ISSUE TITLE
Flash fallback setup

### ISSUE THREAD

**Issue by jankrueger** [videojs/http-streaming#246]
## Description
I try to setup this plugin to work with the flash fallback as documented in the troubleshooting section. 
After pageload there a no errors on the console and the player is displayed without poster image. 
A click on the play button does not start the playback. 
https://jsbin.com/nezehixeqo/edit?html,output (jsbin is unable to load the swf file because of its sandbox mode. But you can run the code in a test environment and get the same result).
Is there any documentation for the usage together with videojs-flashls-source-handler? 

## Steps to reproduce
Run code of this jsbin (https://jsbin.com/nezehixeqo/edit?html,output). 

### Expected
Video should play in flash fallback. 

### Error output
No errors. The video playback never starts. 

### videojs-http-streaming version
videojs-http-streaming 1.2.6

### videojs version
video.js 6.12.1

### videojs-flash version
videojs-flash 2.1.2

### videojs-flashls-source-handler version
videojs-flashls-source-handler 1.4.4

### Browsers
what browsers are affected? please include browser and version for each
* Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Mac, Ubuntu

**Comment by gkatsev** [comment]
Are you testing just in jsbin? JSBin's output panel is a sandboxed iframe and will never run flash. If you open the output panel in a separate window I can see it ask to run the flash plugin, though, it gets blocked by default because that's the new default settings in Chrome. If I change the setting I can get flash to work using your example (here's a clone https://output.jsbin.com/yezapevazo/1)

**Comment by jankrueger** [comment]
Ok, I see why the JSBin wasn't running the flash fallback. 
Do you also see the playback stuttering? Thats what i experience on Chrome running the flash tech. If i run it in html5 mode it runs just fine. 
We are trying to get it to run on IE 11, thats why we need flash..

**Comment by gkatsev** [comment]
Yeah, I do see it stutter a bit with advanced bipbop in chrome. Are you trying to make it work with IE11 on Win7?

**Comment by jankrueger** [comment]
Actually I have only tested it on Chrome and Firefox but will test IE on 8.1 and windows 7.
Is the stuttering caused by the bipbop content in any way?

**Comment by gkatsev** [comment]
Supposedly chrome's flash isn't very good. Also, yeah, that bipbop url is pretty complicated.

**Comment by jankrueger** [comment]
Ok, chrome won't play via flash.
Is there anything we can do contentwise to prevent browsers from stuttering?

**Comment by forbesjo** [comment]
The stuttering should be isolated to the bipbop test source

**Comment by jankrueger** [comment]
I think our problems were caused by a mismatch between the version of videojs-flashls-source-handler and the .swf we used in our webpack build. After videojs-flashls-source-handler released 1.4.5 we were able to use its .swf file.

**Comment by gkatsev** [comment]
Glad you figured it out!
