### ISSUE TITLE
Video and audio does not match after some time passed.(On chrome)

### ISSUE THREAD

**Issue by dovelive** [videojs/http-streaming#250]
Hi.
I am using videojs for playing specific hls dvr stream.(videojs 7.2.3 and http-streaming 1.2.5)

Here is the url.
https://p14080-stv-live.sslcs.cdngc.net/stockvoice/abr-streamnt/playlist_dvr.m3u8
(That stream is only available on 8:00 to 22:00 on JST(+9 hours than UTC).

After start to play about 20 minutes, video and audio does not match.

And I also tested that stream on https://videojs.github.io/http-streaming/.
On that page, after playing about 1 hours later, page become unresponsive.
Error is only occurs on google chrome.(not safari)

So would you like to check that error and fix it?

**Comment by gesinger** [comment]
Hey @dovelive , we'll have to look into the content desync issue, but for the unresponsive page after an hour, are you backgrounding at all? We've noticed issues on Chrome when backgrounding players (particularly with volume off, if that is the case here).

**Comment by dovelive** [comment]
> but for the unresponsive page after an hour, are you backgrounding at all? We've noticed issues on Chrome when backgrounding players (particularly with volume off, if that is the case here).

Hi. @gesinger  Thank you for contacting.
I think that chrome was on background.
So if you think so, then that is okay.
Please resolve the desync error first.
