### ISSUE TITLE
*.ts files are downloaded continously even when video is stopped

### ISSUE THREAD

**Issue by rudyryk** [videojs/http-streaming#251]
## Description

I have simple HLS live stream. It's played as expected. But when paused I can see in developer console that new *.ts files are still being fetched.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Start live HSL stream

2. Connect to it
```
<video id="video" class="video-js vjs-fluid vjs-big-play-centered"
  aspectRatio="16:9" poster="{{ video.preview_url }}">
  <source src="{{ video.stream_url }}" type="application/x-mpegURL">
</video>
  <script type="text/javascript">
    videojs('video', {
      controls: true,
      autoplay: false,
      preload: 'none',
    });
</script>
```

3. Open debug console and watch network traffic

### Expected
I'd expect video is not downloaded when not played.

### Error output
No errors in the output.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.3.0

### videojs version
what version of videojs does this occur with?
video.js 7.2.4

### Browsers
what browsers are affected? please include browser and version for each
Mac OS Safari Version 12.0 (13606.2.11) 
Mac OS Goole Chrome Version 69.0.3497.100 (Official Build) (64-bit)

### Platforms
Mac OS High Sierra 10.13.6

### Other Plugins
No other plugins.

### Other JavaScript
No other JavaScript.

**Comment by gesinger** [comment]
Hey @rudyryk , we haven't seen this behavior before. Would you be able to create a [reduced test case](https://css-tricks.com/reduced-test-cases/) using our [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin including the source you are using? Thanks.

**Comment by rudyryk** [comment]
Hi @gesinger, I'll try - just not sure where to get permanent live HLS. I'll check whether it is reproducible with with pre-recorded HLS first.

**Comment by gesinger** [comment]
For live playback we do keep requesting the manifest while paused, as it allows us to stay in sync for when we resume playback. That is expected behavior. We haven't seen .ts files continually being requested (past reaching the goal buffer length) though.

**Comment by omasback** [comment]
This is still happening. See here: https://www.nuevodevel.com/nuevo/showcase/live

I'll open a new issue
