### ISSUE TITLE
Dash live streaming stops playing after a few seconds

### ISSUE THREAD

**Issue by amtins** [videojs/http-streaming#256]
## Description
Dash live streaming stops playing after a few seconds

## Sources
Livestreams url updated
~~https://srg2-accountdigitalinnovation-euwe.streaming.media.azure.net/3f17705e-954c-449f-b2f9-21786485668b/269fa71b-c34c-467a-ab3e-908cd37c640b.ism/manifest(format=mpd-time-csf)~~

https://wowzaec2demo.streamlock.net/live/bigbuckbunny/manifest_mpm4sav_mvtime.mpd

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open https://amtins.github.io/videojs-dash-live-streaming/
2. Click play
3. Wait until it stops

### Expected

Should works as [videojs-contrib-dash](http://videojs.github.io/videojs-contrib-dash/)

Livestreams url updated
Url to test : ~~https://srg2-accountdigitalinnovation-euwe.streaming.media.azure.net/3f17705e-954c-449f-b2f9-21786485668b/269fa71b-c34c-467a-ab3e-908cd37c640b.ism/manifest(format=mpd-time-csf)~~

https://wowzaec2demo.streamlock.net/live/bigbuckbunny/manifest_mpm4sav_mvtime.mpd

## Additional Information
The given stream is a live stream with DVR. The issue stays the same with or without DVR.

### videojs-http-streaming version
videojs-http-streaming 1.2.6/1.5.0

### videojs version
video.js 7.2.4/7.4.0

### Browsers
All

### Platforms
All

**Comment by albertoronu** [comment]
We're having the same issue. Our platform has been using video.js since version 6 to load Facebook DASH preview video and we can't make it work. Upgrading to latest version available v7.3.0. doesn't help neither. 

Video plays for few seconds and then stops triggering the "waiting" event. Putting the same live video on other players that support DASH works though. Please provide some guidance ASAP.

Thanks!

**Comment by albertoronu** [comment]
@gkatsev @heff could you provide some guidance here? 

This is being urgent for our platform. We have been using videojs for the last year without issues but then DASH started having issues without doing any change, and updating to latest version of videojs 6.12.1 + dashjs 2.9.2 or upgrading to v 7.3.0 is not working at all. 

Stream starts playing but thenstops after few seconds and can't  resume.

**Comment by bansalvks** [comment]
I am also facing some issues like
https://github.com/videojs/http-streaming/issues/260

**Comment by amtins** [comment]
I updated the ticket to the latest version of video.js. I also fixed the livestreams URL as the previous one is no longer available.

**Comment by Nachompiras** [comment]
Some fix for this bug?... I am also facing the same issue. :(

**Comment by ldayananda** [comment]
I also observed with reference streams:

- https://livesim.dashif.org/livesim/segtimeline_1/testpic_2s/Manifest.mpd (gets stuck around `currentTime = 301`
  - refreshes MPD but does not continue requesting segments
- https://livesim.dashif.org/livesim/mup_30/testpic_2s/Manifest.mpd 
  - this has minimumUpdatePeriod of 30s so takes longer to get stuck
  - refreshes MPD but does not continue requesting segments

Observed with latest version on 1.9.0 with Video.js 7.4.0 on https://videojs.github.io/http-streaming/.

I did not quite get enough time to pin down the cause of this, but it looks like the minimumUpdatePeriod re-requests the MPD and updates that reference but does not trigger any media playlist changes. The SegmentLoader then seems to either be looking at older data or trying to only request the last segment and bailing out. That said, I'm not 100% clear on why this is happening.

**Comment by Kogoruhn** [comment]
Same problem with dynamic .mpd file (videojs 7.4.1)
[Manifest (1).txt](https://github.com/videojs/http-streaming/files/2884775/Manifest.1.txt)

**Comment by SanatSharma** [comment]
Facing similar problems with videojs 7.6.6

**Comment by gkatsev** [comment]
We've updated our README with this as a known issue (https://github.com/videojs/http-streaming#dash-assets-with-time-interpolation-and-segmenttimelines-with-no-t), unfortunately, it will take a while before we are able to address this issue.

**Comment by michaelmassee** [comment]
Confirmed, waiting to be Fixed.

**Comment by Verrrr** [comment]
Also having similar problem. Waiting for the fix.

**Comment by michaelmassee** [comment]
i switched to Clapper - > Shaka Player. Works Perfect

https://github.com/clappr/dash-shaka-playback

**Comment by mrvini** [comment]
are there any updates on this issue?

**Comment by gkatsev** [comment]
Not really. We still don't support stream with $Time$. We did have an issue we found with other live DASH that we're fixing here https://github.com/videojs/http-streaming/pull/1065.

**Comment by BucherTomas** [comment]
@gkatsev Does this issue concern truly live streams only? The comment https://github.com/videojs/http-streaming#dash-assets-with-time-interpolation-and-segmenttimelines-with-no-t does not say.

 I've tried with a couple of VoD assets with latest video.js and they appear to be working just fine even though they fall into the same category by using `SegmentTimeline`, `$Time$` template and `d` atttribute.

We're contemplating updating to video.js 7 with http streaming and we'd like to know if it's affecting VoD assets as well from your point of view. If not, it might be beneficial to update the comment in known issues.

**Comment by gkatsev** [comment]
We've generally seen VOD work fine, though, I haven't seen VOD using $Time$. Live DASH is definitely where most of our issues lie.

**Comment by gkatsev** [comment]
I believe https://github.com/videojs/http-streaming/pull/1231 fixes a lot of issues with Live DASH. Specifically, I can confirm that https://wowzaec2demo.streamlock.net/live/bigbuckbunny/manifest_mpm4sav_mvtime.mpd works now. 
We'll have a new release of VHS and Video.js with it soon.

Also, I see that `$Time$` is actually working now with #1231, but I think that's more incidental. It still logs lots of warnings in the console in when `$Time$` is used.

**Comment by gkatsev** [comment]
I believe this is now fixed in the latest Video.js/VHS release of 7.18.0 for Video.js and 2.13.1 for VHS.

**Comment by amtins** [comment]
@gkatsev I think so too, I did a quick test and it seems to work like a charm, thank you that's awesome 🚀 👍
[Release note v2.13.0](https://github.com/videojs/http-streaming/releases/tag/v2.13.0)
