### ISSUE TITLE
DOMException: "The quota has been exceeded." on Firefox only

### ISSUE THREAD

**Issue by Nodja** [videojs/http-streaming#258]
## Description
HLS video segments over a certain size (20MB?) cause a DOMException: "The quota has been exceeded." to occur on Firefox. Works fine on chrome and edge.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load https://jsbin.com/cekitaxace/edit?html,output

### Expected
Video should play

### Error output
VIDEOJS: ERROR: (CODE:-3 undefined) The quota has been exceeded. Object { code: -3, type: "APPEND_BUFFER_ERR", message: "The quota has been exceeded.", originalError: DOMException } video.js:128:5

### videojs-http-streaming version
1.3.0

### videojs version
video.js 7.2.3 

### Browsers
* Firefox 62.0.3

### Platforms
* Windows 10

**Comment by forbesjo** [comment]
This looks similar to https://github.com/videojs/http-streaming/issues/192, we're working on a fix for this.
