### ISSUE TITLE
Unable to play dash with widevine drm

### ISSUE THREAD

**Issue by bansalvks** [videojs/http-streaming#260]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Unable to play Dash with Widevine DRM

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
```
    <video-js id="my_video_1" class="vjs-default-skin" controls preload="auto" width="640" height="268"> </video-js>

    <link href="//vjs.zencdn.net/7.2/video-js.min.css" rel="stylesheet">
    <script src="//vjs.zencdn.net/7.2/video.min.js"></script>
    <script src="https://unpkg.com/@videojs/http-streaming@1.3.0/dist/videojs-http-streaming.js"></script>
    <script src="./node_modules/videojs-contrib-eme/dist/videojs-contrib-eme.js"></script>

    <script>
        var player = videojs('my_video_1');
        player.eme();
        player.src({
            src: 'manifest.mpd',
            type: 'application/dash+xml',
            keySystems: {
                'com.widevine.alpha': '<url>'
            }
        });
    </script>
```

### Expected
The stream should have been played

### Error output
VIDEOJS: ERROR: failed to get and set license TypeError: Failed to execute 'update' on 'MediaKeySession': Rejected with system code (13)

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.3.0

### videojs version
what version of videojs does this occur with?
video.js 7.2

### Browsers
what browsers are affected? please include browser and version for each
* chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* no

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* no

**Comment by forbesjo** [comment]
Would you be able to provide an example video for us to debug? If the source can't be shared with the public please post in the video.js slack and we can help you there

**Comment by vksbansal** [comment]
> Would you be able to provide an example video for us to debug? If the source can't be shared with the public please post in the video.js slack and we can help you there

@forbesjo Pardon me for a late reply.

As the token has a very short life span it would be use less to provide the source. If it is possible for you to provide me a **time(with timezone)** with your **slack Id**, I will send you the source at that particular time.

**Comment by Kogoruhn** [comment]
@vksbansal 
temporary solution, works for me:
downgrade video.js to 6.12.1, install videojs-contrib-dash (dash included eme service), see dash manual.

**Comment by vksbansal** [comment]
@Kogoruhn many thanks for the response.

Yes I have tried it and its working. However I will have to include 2 more libs for this ```videojs-contrib-dash and dash.js``` which obviously increasing the size of page.

Is it not possible for ```videojs-http-streaming (VHS)``` to add .dash (dash-if) support?

**Comment by danrossi** [comment]
There is little to no documentation how to initialise this. It is extremely complicated and makes it difficult to configure like so. Any ideas ? This odd separate call to "eme" returns with a null pointer. 

 var player = videojs('player', {
                   
                    sources: [
                      
                         {
                            type:"application/dash+xml", src: "//videos.electroteque.org/dash/bbb/bbb.mpd", 
                            keySystems: {
                              "com.widevine.alpha": {
                                url: '//widevine-dash.ezdrm.com/proxy?pX=39010C&uid=demo&pass=demo'
                              },
                              "com.microsoft.playready": {
                                url: '//playready.ezdrm.com/cency/preauth.aspx?pX=DE2442&uid=demo&pass=demo'
                              }
                            }
                         },
                    ]
                });

**Comment by danrossi** [comment]
I'm working on a feature that needs to reset the source after playing a different source. the keysystem config is there. But for some reason it hangs. No playback

```
player.src(player.currentSources());
```

**Comment by danrossi** [comment]
never mind sorry this works

```
 if (player.eme) {
                    player.eme.activeSrc = null;
 }
 player.src(player.currentSources());
```

**Comment by vksbansal** [comment]
A warm good morning to you @Kogoruhn and @forbesjo 
I am taking follow up regarding this issue. it has been 16 days since the ticket has marked as a bug. Just need to confirm if this issue will be fixed in the coming release?

many thanks,
vikas bansal

**Comment by danrossi** [comment]
I have a fresh checkout of the eme plugin, with the sources of video.js. It is working with that wierd configuration requirement above.

**Comment by gesinger** [comment]
"system code (13)" is sometimes seen when the license is invalid. Are you able to check you server's response to ensure it's returning just a license (and not JSON or some other response)?

**Comment by luiscerqueira** [comment]
Hi @gesinger ,

I am currently experiencing this issue,
My license server returns a json response containing the license.
So, trying to overcome this poblem, I have implemented a getLicense logic to fetch the license and access the json object to get the license.
The license comes as a string, but the plugin requests an ArrayBuffer; so what I am doing is encoding the license string using the TextEncoder API.

Even doing this, i got the:
VIDEOJS: ERROR: failed to get and set license TypeError: Failed to execute 'update' on 'MediaKeySession': Rejected with system code (13)

Any thoughts of what could be the problem?

Here is the code i am doing:
```
getLicense: function(emeOptions, keyMessage, callback) {
        // request license
        fetch('http://localhost:8080/license-widevine/', { 
          method: "POST", 
          headers: {
            "Content-type": "application/octet-stream"
          },
          body: keyMessage
        })
        .then(response => {
          if(!response.ok)
            throw response;
          return response
        })
        .then(response => response.json())
        .then(data => {
          callback(null, new TextEncoder().encode(data.license));
        })
        .catch(err => {
          callback(err);
        });
      } 
```

**Comment by nehaboob** [comment]
@luiscerqueira - did you solve this problem ? we are facing the same issue.

**Comment by sanjuc** [comment]
yeah, we are also facing the same issue.

**Comment by gkatsev** [comment]
Unfortunately, due to the nature of DRM, it's almost impossible for us to help out with a live test page. Widevine does work with DASH in Video.js. See https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=false&url=https%3A%2F%2Fstorage.googleapis.com%2Fshaka-demo-assets%2Fangel-one-widevine%2Fdash.mpd&type=application%2Fdash%2Bxml&keysystems=%7B%0A%20%20%22com.widevine.alpha%22%3A%20%22https%3A%2F%2Fcwip-shaka-proxy.appspot.com%2Fno_auth%22%0A%7D&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&override-native=true&preload=auto&mirror-source=true for an example.
Also, make sure you're on a recent version of Video.js and videojs-contrib-eme.

If you're still facing an issue, please open a new issue with as much detail as possible. If you aren't able to share your test page publicly, you can find someone to help out privately on our slack (https://videojs-slack.herokuapp.com/).
