### ISSUE TITLE
How to stop a live stream?

### ISSUE THREAD

**Issue by m98** [videojs/http-streaming#264]
## Description
I'm using videojs/http-streaming to stream live video, but when I close the player, I want player to stop. But when I see the network tab, I see HTTP requests are issuing which means the player is yet receiving next seconds of the live video; Even when I click on pause button of the player, I see there are still HTTP requests getting (I guess) more seconds of the live video.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue (I use Angular 6)
- There is a videojs player (used `video` tag, not `videojs` tag)
- I open the player container (using `ngIf="true"`), and automatically video plays
- I close the video (using `ngIf="false"`) and video closes and does not play
- Yet I see HTTP requests on the network tab of the developer console

### videojs version
what version of videojs does this occur with?
video.js 7

### Browsers
Latest Chrome

### Platforms
Linux / Fedora

### Other Plugins
`videojs-seek-buttons` and `videojs-hotkeys` and `overlay`

### Other JavaScript
Angular

**Comment by m98** [comment]
Yes, I kept reading documents and found that there is a way to dispose
player, and it worked as expected

Thank you

**Comment by gesinger** [comment]
Thanks for the update @m98 .
