### ISSUE TITLE
MPEG DASH, HLS, MP4 source order

### ISSUE THREAD

**Issue by edwinbradford** [videojs/http-streaming#284]
Does video.js 7.x still load video sources in the order in which they are listed in the `<source>` tags as it did in 6.x and earlier?

    <source src="media.mpd" type="application/dash+xml">
    <source src="media.m3u8" type="application/x-mpegURL">
    <source src="media.mp4" type="video/mp4">

So in the above example DASH would be tried before HLS before MP4. I ask because there is virtually no mention of DASH in the http-streaming documentation and the emphasis seems to be on HLS now.

How can I log which format is being played? I tried adding `videojs.log.level();` to the end of my player initialization but it doesn't log anything to the Chrome console.

      var player = videojs('videoJSElement', {
        'autoplay': false,
        'controls': true,
        'loop': false,
        'muted': false,
        'preload': 'auto',
      });
      videojs.log.level();

**Comment by forbesjo** [comment]
You can see which source is loaded into the player with `player.currentSource()`

**Comment by edwinbradford** [comment]
Thanks, it works and I was also able to get general logging working with `videojs.log.level('debug');`
