### ISSUE TITLE
Unable to play m3u8?xxxxxxxxx=xxxxxxx file

### ISSUE THREAD

**Issue by ishaqani** [videojs/http-streaming#299]
I am unable to play following m3u8 file

http://221.132.113.234:9981/stream/channelid/1434021820.m3u8?ticket=1013954CD654BBE4E1DC8B1838C5B6CF895F85A7&profile=pass

Please try at your end and advise what is the solution.

I have chrome updated browser. Above link is working well with VLC Player and MX player on android and computer.

**Comment by mrocajr** [comment]
This file does not appear to be an HLS manifest. Although the extension would imply it is, the content contains binary data and does not conform to the HLS spec.

**Comment by gkatsev** [comment]
The content-type in the header is also `video/mp2t`. We don't support playing back mp2t directly, only via an HLS manifest. This seems like full stream and I'm not sure we support playing that either. I think we only handle segmented TS currently.

**Comment by forbesjo** [comment]
Looks like your stream manifest isn't resolving, is it still live?
