### ISSUE TITLE
Video interruped and show message that 'The media playback was aborted due to a corruption problem or because the media did not support your browser.' in video.js

### ISSUE THREAD

**Issue by mskim8522** [videojs/http-streaming#301]
## Description
_If you play a certain hls stream in the latest version of Chrome, it prints an error message and stops._

## Steps to reproduce
1.  Access https://videojs.github.io/http-streaming/ 
2. Change videoUrl to 'https://56656e6440699.streamlock.net/live/C001.sub.stream/playlist.m3u8'
  (This URL is open during testing.)
3. Click Play

## Results
After playback starts, the following message will be displayed after a few seconds.

> The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:
> The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

## Additional Information
Please include any additional information necessary here. Including the following:
Turns Chrome browser's hardware acceleration off and plays normally.

### Browsers
* Chrome 70.0.3538.102 ( windows 10)

### Platforms
* Windows 10

**Comment by forbesjo** [comment]
Is your test stream still live? I'm not able to load it in any player

**Comment by 0smir** [comment]
Hello! 


.video-js  {
    object-fit: fill;
}

https://bugs.chromium.org/p/chromium/issues/detail?id=282484

**Comment by mskim8522** [comment]
> Is your test stream still live? I'm not able to load it in any player

Sorry, my test url is not alive now because I have a problem.
When the problem is solved, I will revive it.
Thank you.

**Comment by mskim8522** [comment]
> Is your test stream still live? I'm not able to load it in any player

@forbesjo My test stream is live. please check it.
