### ISSUE TITLE
Support for EXT-X-START in HLS

### ISSUE THREAD

**Issue by jimmycallin** [videojs/http-streaming#310]
Hi!

I noticed that video.js doesn't seem to respect EXT-X-START as set in my HLS manifest, e.g:

`#EXT-X-START:TIME-OFFSET=0.7,PRECISE=YES`

I also noticed there is an abandonded(?) PR by @masterful in videojs-contrib-hls: https://github.com/videojs/videojs-contrib-hls/pull/1299

Is this indeed something that this library doesn't currently support? If possible, I would very much appreciate if it could be a part of your roadmap.

**Comment by masterful** [comment]
👋 hi @jimmycallin - I believe I updated the PR as requested - but I never did figure out what was causing the tests to fail... I can revisit the PR once I understand what's failing 🤷‍♂️

**Comment by jimmycallin** [comment]
I would like if this wasn't closed.

**Comment by jimmycallin** [comment]
Still interested

**Comment by meikidd** [comment]
interested +1

**Comment by Hayko-1** [comment]
interested +1

**Comment by shay-sundaysky** [comment]
+1

**Comment by gkatsev** [comment]
Oops, yeah, we should have support for this.

**Comment by saurabhkhandelwal** [comment]
Guys any idea when this might go live, would be of great help. Thanks in advance.

**Comment by vegetablesalad** [comment]
Really need this. Otherwise have to parse m3u8 file and skip in code.

**Comment by saurabhkhandelwal** [comment]
@vegetablesalad I did a hack for this, implemented another field in the API in which I get the stream URL as an offset. and then on video meta load I just call this currentTime(offset).

**Comment by sicksid** [comment]
guys this seems to be supported already but I could be wrong, if i run: `player.tech().vhs.selectPlaylist()` I do se the `EXT-X-START params that we are settings being parsed`

![Screen Shot 2021-08-10 at 13 31 18](https://user-images.githubusercontent.com/7379966/128915791-86a83708-86f2-4e56-8546-fa0698784c81.png)
![Screen Shot 2021-08-10 at 13 30 35](https://user-images.githubusercontent.com/7379966/128915795-24c646e7-84b6-4cf8-9556-c0490a1a25bf.png)

**Comment by gkatsev** [comment]
While it gets parsed, I'm pretty sure we don't currently use it at all.

**Comment by sicksid** [comment]
> While it gets parsed, I'm pretty sure we don't currently use it at all.

@gkatsev thanks for answering so fast then ill just do the same thing as @saurabhkhandelwal

**Comment by You2499** [comment]
Any update on this?

**Comment by blokfyuh** [comment]
+1

**Comment by mister-ben** [comment]
This was released in http-streaming v3.3.0, in Video.js 8.4.0+

https://github.com/videojs/http-streaming/blob/main/CHANGELOG.md#330-2023-05-03
