### ISSUE TITLE
Do you have any plan to support flv streaming

### ISSUE THREAD

**Issue by yunnysunny** [videojs/http-streaming#314]
## Description
I found that http-streaming has not supported flv streaming yet, do you have any plan to do this?

**Comment by forbesjo** [comment]
We do not, with the transition from the videojs-contrib-hls project to http-streaming we have dropped Flash support to focus on MSE. If you need Flash support we recommend using the flashls source handler https://github.com/videojs/http-streaming#flash-support

**Comment by yunnysunny** [comment]
What I mean is just dropping the usage of flash and parsing flv stream with javascript.

**Comment by Eronana** [comment]
Agree with @yunnysunny, it seems mux.js already support flv https://github.com/videojs/mux.js/tree/master/lib/flv
So we can directly use it when received a flv segment.
@forbesjo, what do you think of this?
