### ISSUE TITLE
Improved HLS playlist selection algorithms

### ISSUE THREAD

**Issue by arski** [videojs/http-streaming#319]
Hi there, do you support, or are you aware of some advanced HLS playlist selection algorithm implementations for http-streaming? Something like https://people.cs.umass.edu/~ramesh/Site/HOME_files/Bola.pdf which is implemented for dash.js e.g. https://github.com/Dash-Industry-Forum/dash.js/wiki/BOLA-status

**Comment by gkatsev** [comment]
I want to add in here that we would be interested in looking at something like BOLA long-term but are unlikely to have the bandwidth (pun intended) in the near future as we have higher priorities (like SIDX and Live DASH and LHLS).

**Comment by arski** [comment]
uuh thats interesting! still nice
