### ISSUE TITLE
beforeRequest doesnt fire on iPhone Safari

### ISSUE THREAD

**Issue by samueleastdev** [videojs/http-streaming#333]
## Description
We are using beforeRequest to send some headers to our api its works fine on desktop but not on mobile from my tests it doesn't seem to fire.

## Steps to reproduce
1. Open this demo here: https://output.jsbin.com/cayiqof/11 note that in the console it will say "beforeRequest did fire" from the console.log
2. Open the same link on an iPhone device (Not Safari on a desktop with user agent set to iPhone a real device)
3. Connected your phone via USB click the developer tab in Safari you should see your device.
![screenshot 2019-01-05 at 16 29 23](https://user-images.githubusercontent.com/1894778/50726574-313c7600-1107-11e9-9791-32e3d335a84f.png)
4. You can now refresh on your phone and inspect element you will see that the console.log does not fire.
![screenshot 2019-01-05 at 16 31 21](https://user-images.githubusercontent.com/1894778/50726589-63e66e80-1107-11e9-845f-5c06a6fa3cbe.png)

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.7.0

### videojs version
what version of videojs does this occur with?
video.js 7.4.1

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
Mobile devices

**Comment by forbesjo** [comment]
videojs-http-streaming is not used on iPhone Safari, that browser does not have MSE so we're unable to control the requests and load segment data.

**Comment by ShawnRong** [comment]
Any update on this issue? Facing the same problem on iOS device

**Comment by gkatsev** [comment]
iPhones do not support MSE and therefore VHS cannot run there. On iPad with iPadOS 13 and newer does have MSE and so you could use override native to force VHS to run there but we haven't done much testing with safari and don't recommend it.

**Comment by ShawnRong** [comment]
> iPhones do not support MSE and therefore VHS cannot run there. On iPad with iPadOS 13 and newer does have MSE and so you could use override native to force VHS to run there but we haven't done much testing with safari and don't recommend it.

Thanks for reply. Is there have any hook method (like beforeRequest) for VHS to append some request header options while requesting every video fragments ? Because in my project, I need to get the header token to check if the request have permission to get the fragment encrypt key. 
The requirement is same as @samueleastdev 's description.

> Hi @forbesjo
> 
> Thanks for the feedback about Media Source Extensions (MSE) not being supported.
> 
> I am curious what other people are doing to implement proxy authentication in the manifest seems a great way to protect content without a full DRM solution giving you full control over who to authenticate based on header tokens passed in the beforeRequest call.
> 
> ```
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-TARGETDURATION:4
> #EXT-X-MEDIA-SEQUENCE:1
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXT-X-KEY:METHOD=AES-128,URI="https://example.com/proxy/token",IV=0x00000000000000000000000000000001
> #EXTINF:3,
> master_Ott_Hls_Ts_Avc_Aac_16x9_1920x1080p_30Hz_8500Kbps_00001.ts
> #EXT-X-KEY:METHOD=AES-128,URI="https://example.com/proxy/token",IV=0x00000000000000000000000000000002
> #EXTINF:3,
> master_Ott_Hls_Ts_Avc_Aac_16x9_1920x1080p_30Hz_8500Kbps_00002.ts
> #EXT-X-KEY:METHOD=AES-128,URI="https://example.com/proxy/token",IV=0x00000000000000000000000000000003
> #EXTINF:3,
> ```
> 
> At the moment it will only work on desktop unless someone else can give me some more information on another possible solution?
> 
> Thanks ;)

**Comment by gkatsev** [comment]
> Is there have any hook method (like beforeRequest) for VHS to append some request header options while requesting each video fragments

Not for iPhones and for older iPad.
