### ISSUE TITLE
Building HLS playlist in the javascript client

### ISSUE THREAD

**Issue by nemesis567** [videojs/http-streaming#335]
I have many M3U8 files. I want to load them and join them into one big stream I'll be appending segments to. I'd like this to be contained in the client. Is it possible to use a blob or file object and use that as the playlist URL?

**Comment by forbesjo** [comment]
This project currently doesn't have an API for sending the contents of an M3U8, I would advise either using a playlist plugin like https://github.com/brightcove/videojs-playlist or run some sort of server process that merges your files into a valid M3U8 you can send to the player.
