### ISSUE TITLE
If only `#EXT-X-ENDLIST` is added to a playlist, the update isn't seen

### ISSUE THREAD

**Issue by hpate-omicron** [videojs/http-streaming#345]
## Description
I saw an issue where intermittently it would not recognize that a live stream had ended, it would stall on the last frame and show the loading indicator, but not progress further.  In the console you would see multiple instances of this message, and it would keep re-requesting the `m3u8` file periodically.
```
video.js:498 VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the final playlist.
video.js:498 VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the final playlist.
video.js:498 VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the final playlist.
```

## Sources
Sorry, I don't have a public source to share.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

This is a test that only updates the `endList` property when calling `updateMaster`.  On the current head of `master` it will fail.

1. Add this test to `tests/playlist-loader.test.js`
```js
QUnit.test('updateMaster updates master when endList changes', function(assert) {
  const playlist = {
    endList: false,
    mediaSequence: 0,
    attributes: {
      BANDWIDTH: 9
    },
    uri: 'playlist-0-uri',
    resolvedUri: urlTo('playlist-0-uri'),
    segments: [{
      duration: 10,
      uri: 'segment-0-uri',
      resolvedUri: urlTo('segment-0-uri')
    }]
  };

  const master = {
    playlists: [playlist]
  };

  const media = Object.assign({}, playlist, {
    endList: true
  });

  assert.deepEqual(
    updateMaster(master, media),
    {
      playlists: [{
        endList: true,
        mediaSequence: 0,
        attributes: {
          BANDWIDTH: 9
        },
        uri: 'playlist-0-uri',
        resolvedUri: urlTo('playlist-0-uri'),
        segments: [{
          duration: 10,
          uri: 'segment-0-uri',
          resolvedUri: urlTo('segment-0-uri')
        }]
      }]
    },
    'updates master when endList changes');
});
```
2. Run tests

### Expected
Playlist should update when `endList` changes

### Error output
You will see this message repeated in the console when this happens
```
video.js:498 VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the final playlist.
```

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls x.y.z

### videojs version
what version of videojs does this occur with?
video.js 5.14.1
video.js 7.0.0 as well (still in https://github.com/videojs/http-streaming/blob/master/src/playlist-loader.js#L97)

### Browsers
what browsers are affected? please include browser and version for each
All

### Platforms
what platforms are affected? please include operating system and version or device and version for each
All

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
No

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
No

**Comment by forbesjo** [comment]
Fixed with #373
