### ISSUE TITLE
Audio only toggle (disable video but continue playing the audio stream)

### ISSUE THREAD

**Issue by namor** [videojs/http-streaming#346]
## Description
Is there a way to programatically disable the video stream while continuing to play the selected audio stream for HLS streams?

### Expected
Clicking on a audio only toggle would allow me to disable the video stream (maybe replace with an image) but allow the audio to continue running to save bandwidth while driving

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.14.0

### videojs version
what version of videojs does this occur with?
video.js 5.6.0

**Comment by forbesjo** [comment]
We don't have an easy way to switch to an audio only rendition. If your content does use audio only last in its ladder then you can use the bandwidth property to force the lowest rendition to start
