### ISSUE TITLE
Some m3u8 videos are stuck when played repeatedly after the first time

### ISSUE THREAD

**Issue by old-bin** [videojs/http-streaming#348]
## Description
I find my m3u8 videos are stuck when played repeatedly, but they play normal for the first time! 
I tried playing video with safari and firefox, but did not discover this problem. Only have problems in chrome!
I tried playing video on ipone7's safari with native video tag，but did not discover this problem.

## Sources
experiment URL : http://videojs.github.io/videojs-contrib-hls/
experiment source:  http://n1-q.mafengwo.net/s11/M00/D4/FE/wKgBEFrQXCmAOPHmAAAB4fZtONI06.m3u8

### Browsers
chrome 65.0.3325.181

**Comment by old-bin** [comment]
> The issue is still there. I do not know why the dev team is not responding to this issue... Please help.
> 
> @old-bin @blitheinsz @SuYuWei have you found any work around?

No, I have given up.

**Comment by old-bin** [comment]
@blitheinsz   No, I have given up videojs !

**Comment by jrocha** [comment]
@old-bin I'm at this point now. Are you using another player? Which one?

**Comment by sunzongzheng** [comment]
Any update?

**Comment by mraiguo** [comment]
Any update?

**Comment by mraiguo** [comment]
This commit solves the problem https://github.com/videojs/http-streaming/commit/446cb101dd4acca2dc9d2d56fb97b18ca31d1d3a
