### ISSUE TITLE
Prevent downloading encrypted content with Firefox video download helper extension

### ISSUE THREAD

**Issue by samueleastdev** [videojs/http-streaming#357]
Hi All,

We have spent quite a bit of time trying to provide the best possible security by encoding our media through AWS with AES 128 bit encryption this has worked great for a long time but like everything on the web we have been shown that this can be easily downloaded using the following plugin.

https://addons.mozilla.org/en-GB/firefox/addon/video-downloadhelper/

Simply install the extension in Firefox and then install the companion app and click download and covert 

We have set up an example below.
http://output.jsbin.com/fabefit/1/

Can anyone suggest any way to prevent this I totally understand that its pretty much impossible to prevent videos from being stolen simply using screengrab software will do the job and nothing can prevent this but it would be good to prevent simple downloads from extensions make it as hard as possible?

We recently viewed a post here: https://github.com/videojs/videojs-contrib-hls/issues/1337 about possibly obfuscating the requests.

Maybe we are missing a step that can prevent this any info would be appreciated?

Thanks

**Comment by joaokrabbe** [comment]
Could anyone prevent downloading encrypted content with Firefox video download helper extension? I've looked for several streaming services, but none with a solution to it. Currently I am using streaming with flash player, but I have several communication problems in some students due to firewall restrictions.

**Comment by canhnm** [comment]
> Could anyone prevent downloading encrypted content with Firefox video download helper extension? I've looked for several streaming services, but none with a solution to it. Currently I am using streaming with flash player, but I have several communication problems in some students due to firewall restrictions.

Are you using AES encryption with the key embedded together with m3u8 file? I have already been working on this and my solution is remove the key there, extend my player code to handle the key instead!

**Comment by joaokrabbe** [comment]
> > Could anyone prevent downloading encrypted content with Firefox video download helper extension? I've looked for several streaming services, but none with a solution to it. Currently I am using streaming with flash player, but I have several communication problems in some students due to firewall restrictions.
> 
> Are you using AES encryption with the key embedded together with m3u8 file? I have already been working on this and my solution is remove the key there, extend my player code to handle the key instead!

No, I took some examples from the posts above and am trying to figure out how to block the download. Could you share an example of what you mentioned if it doesn't bother you?
I would appreciate it very much.

**Comment by canhnm** [comment]
> > > Could anyone prevent downloading encrypted content with Firefox video download helper extension? I've looked for several streaming services, but none with a solution to it. Currently I am using streaming with flash player, but I have several communication problems in some students due to firewall restrictions.
> > 
> > 
> > Are you using AES encryption with the key embedded together with m3u8 file? I have already been working on this and my solution is remove the key there, extend my player code to handle the key instead!
> 
> No, I took some examples from the posts above and am trying to figure out how to block the download. Could you share an example of what you mentioned if it doesn't bother you?
> I would appreciate it very much.

Oh so your problem is the Firefox will automatically download your media once user access the page? Or you want to prevent user to not able to decrypt downloaded media?

My case is not about downloadable, it's about decryption!
Sure I can share you some information PM me please as it's not comfortable to public production one!

**Comment by rossanakarina** [comment]
has anyone managed it?
