### ISSUE TITLE
Problem with Android Chrome

### ISSUE THREAD

**Issue by newnewcoder** [videojs/http-streaming#361]
## Description

I hava a file `video.m3u8` which contained some `.ts` file url, and I save the `video.m3u8` as `video` without file name extension.

I used this code `<source src="/video/video" type="application/x-mpegURL">` to play HLS video,
It worked successfully on Chorme desktop, but not on Android Chrome.

When I turned `video` back to `video.m3u8` and add `.m3u8` to source tag's src like `<source src="/video/video.m3u8" type="application/x-mpegURL">`, it worked fine on both desktop and Android Chrome. 

In order to find what went wrong, I used [Google Chrome Remote Debug](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) to remote observe on Android Chrome console. There is no error log. Does anyone knows why?

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

~~~html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Test</title>
      <link href="http://vjs.zencdn.net/6.2.8/video-js.css" rel="stylesheet">
   </head>
   <body>
      <video id="player" class="video-js vjs-default-skin" controls preload>
         <!-- <source src="/video/video.m3u8" type="application/x-mpegURL"> -->
         <source src="/video/video" type="application/x-mpegURL">
      </video>
      <script src="http://vjs.zencdn.net/6.2.8/video.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.12.2/videojs-contrib-hls.min.js"></script>
      <script>
          var player = videojs('player');
          player.play();
     </script>
   </body>
</html>
~~~

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
videojs-contrib-hls 5.12.2

### videojs version
what version of videojs does this occur with?
video.js 6.2.8

### Browsers
what browsers are affected? please include browser and version for each
* Android Chrome 62.0.3202.84 (not working)
* Mac Chrome 62.0.3202.94 (working)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Android 7.0
* Mac 10.12.6

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by halilozel1903** [comment]
> There are a couple of types of issue being conflated here.
> 
> It's important to understand that by default videojs-contrib-hls (VCH) defers to the browser to play HLS natively, if it's detected it has that capability. If you use VCH's [`overrideNative` option](https://github.com/videojs/videojs-contrib-hls/blob/master/README.md#overridenative), VCH will step in and play HLS with Media Source Extensions (MSE) where available.
> 
> 1. **Desktop Chrome vs Android Chrome:** Problems like #1308 are with Android's native playback. These issues are hard to debug because the HLS playback is in a separate process that can't be inspected with Chrome's remote debugging tools. It also uses a different user agent and sends no referrer header so can break with some CDN security configurations. Fun. Using `overrideNative` will often get around the issue, since then HLS will then be played the same way as on desktop Chrome, by VCH with MSE.
> 2. **Desktop Chrome vs desktop Chrome "emulating" Android:** VCH does not play HLS as described in #1305. Chrome's "emulation" mode _does not_ add functionality like native HLS playback. VCH none the less thinks the browser can play HLS because of Video.js's HTML5 tech's crude patch of the canPlayType method where the user agent is Android. (Android's old "stock browser" incorrectly reports that it can't play HLS but can, which led to issues with no playback where HLS is available). We can and should change the HTML5 tech to not patch with Android Chrome as it reports correctly. Using `overrideNative` would also allow VCH to play HLS on desktop Chrome "emulating" Android.
> 
> There's a catch: resolving the second issue so HLS is played on desktop Chrome "emulating" Android with VCH/MSE _will not help_ in debugging the first class of issue with Android's _native_ HLS playback. You won't be looking at the same thing. Again using `overrideNative` on Android Chrome might be the best way to obviate that problem.

Hello, I can't get the content back and forth when I use videoJS in Android app. Why is this caused? Is the solution to this on the Android side or the VideoJS side? Help me please :)
