### ISSUE TITLE
cause of Cannot read property 'segments' of undefined 

### ISSUE THREAD

**Issue by andyli9449** [videojs/http-streaming#364]
## Description
Briefly describe the issue.
some m3u8 can not play and console print "Cannot read property 'segments' of undefined "
if your PAT of ts have NIT ,it will cause videojs-contrib-hls analysis PMT failed。

## Sources
15102:   parseType(data.subarray(i + 4, i + 8));

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
Sample PAT :
 47 40 00 14 00 00 B0 11 00 00 C1 00 00 00 00 E0 1F 00 01 E1 00 23 5A AB 82                    
                                                                       | NIT           |   PMT      |     CRC       |      

### Expected
console print :Cannot read property 'segments' of undefined 

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
 * videojs-contrib-hls
 * @version 5.12.2

### videojs version
what version of videojs does this occur with?
Video.js 6.4.0

### Browsers
what browsers are affected? please include browser and version for each
*
chorme

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by chadlwm** [comment]
So, what's the solution?

**Comment by bawat** [comment]
I'm still looking for a solution to this

**Comment by xiangwencheng1994** [comment]
me to....

**Comment by gkatsev** [comment]
Anyone have a sample stream they can share that exhibits this behavior?

**Comment by Anil-matcha** [comment]
Hi @gkatsev . I am facing the same issue with https://vadoohls.peervadoo.com/am_25a0bf5f-56f1-44cc-915c-38d7dfff37a1/videos/ZfJDFc4oXwnY52VWiZ4C5tw3AUKTV0p2/HLS/ZfJDFc4oXwnY52VWiZ4C5tw3AUKTV0p2.m3u8

Can you kindly help

**Comment by gkatsev** [comment]
@video-archivist-bot save gAg1jp

**Comment by gkatsev** [comment]
@Anil-matcha hey, are you able to re-share your stream? Thanks.

**Comment by Anil-matcha** [comment]
Hi @gkatsev . The issue got resolved when I changed the url which was weird. The problem was occurring when the current domain url is different from the domain where the m3u8 file is stored. I changed the domain of the m3u8 file to store on same domain as my website and it started working fine

**Comment by gkatsev** [comment]
Ah, cool. We do have an option for that [handleManifestRedirects](https://github.com/videojs/http-streaming#handlemanifestredirects). It's not on by default because we still support IE11.

**Comment by gkatsev** [comment]
Given how old the issue is, I'm going to close this. If you're still seeing this issue, please check your stream as it may not be valid HLS. Or maybe you need to enable [handleManifestRedirects](https://github.com/videojs/http-streaming#handlemanifestredirects).
If it's still not working, please open a new issue with a live stream. Thanks.

**Comment by kevin-onepiece** [comment]
My problem got solved by changing codec from h265 to h264.

**Comment by caionakai** [comment]
@kevin-onepiece thanks
