### ISSUE TITLE
 Cannot read property 'segments' of undefined

### ISSUE THREAD

**Issue by Toninie** [videojs/http-streaming#365]
## Description
Similar with this [issue](https://github.com/videojs/videojs-contrib-hls/issues/815),some m3u8 source cannot play and throw an error,but it work in VLC and mobile browser.

## Sources
I download a little part of source and make a test demo, please check the attachment
[hls.zip](https://github.com/videojs/videojs-contrib-hls/files/1274385/hls.zip)

### Expected
Confirm why the source cannot play,is it unspported by this plugin,or lack of something necessary? 

### Error output
Uncaught TypeError: Cannot read property 'segments' of undefined

### videojs-contrib-hls version
videojs-contrib-hls 5.10.1

### videojs version
video.js 6.2.5

### Browsers
*Chrome  59.0.3071.115

### Platforms
*Windows 10

**Comment by forbesjo** [comment]
Looks similar to https://github.com/videojs/http-streaming/issues/364, closing in favor of that issue
