### ISSUE TITLE
While doing HLS AES 128 playback, the player request key file for every chunk.

### ISSUE THREAD

**Issue by riubin** [videojs/http-streaming#367]
## Description
I have the same question as this post:
https://github.com/videojs/videojs-contrib-hls/issues/776

I want to control the key file request by php server script that only the valid user can get the AES key file. so I can not set cache expires of the key file.Therefor the php server been to very hevy. I had tried to modify mediaSegmentRequest function for check key.resovledUri and store the key value,but failed.
Is there any other way to fixed the proplem?
Thanks a lot!

### videojs-contrib-hls version
videojs-contrib-hls 5.5.3

### videojs version
video.js 5.19

**Comment by blacktrash** [comment]
Seems related to #140

**Comment by gkatsev** [comment]
While we believe appropriate cache-control headers are the optimal solution, we've added an option to not re-request the key on every segment (#446). It is out in version 1.10.0.

**Comment by hasinhayder** [comment]
Just add this to your options and it will be cached :)

```html
html5: {
    vhs: {
      cacheEncryptionKeys: true
    }
  }
```

notice the **vhs**, not hls :)

**Comment by z4yed** [comment]
Thanks. @hasinhayder That's exacly what I needed.
