### ISSUE TITLE
If down to last un-blacklisted playlist, and it errors, clear the blacklist for other playlists

### ISSUE THREAD

**Issue by gesinger** [videojs/http-streaming#369]
## Description
Right now, if we are down to our last playlist, we don't blacklist it. However, if there are other playlists that are currently blacklisted, we have to wait up to 5 minutes for their blacklists to clear. We should instead clear the blacklist/shorten the blacklist duration for the other playlists, and retry the best available playlist after a delay.

**Comment by forbesjo** [comment]
Port over the above PR
