### ISSUE TITLE
Video corruption playing certain HLS streams in http-streaming 1.2.5+

### ISSUE THREAD

**Issue by jsanford8** [videojs/http-streaming#395]
## Description
Regression - VHS 1.2.5 (which was pulled into Video.js 7.2.3) introduced an issue where certain videos can result in corrupted playback in the first segment of video, but _only_ on Chrome (i.e. not Firefox).

See reproduction steps below, but this has been tracked down to the change within this PR: https://github.com/videojs/http-streaming/pull/204. Again, more detials found below, but the quick summary appears to be that the call to sync the VHS time to the player time when pressing play right at the beginning of an asset causes some form of corruption in the source buffer in Chrome.

## Sources
This source should reproduce the issue at all times: https://s3.amazonaws.com/mux-justin-test/vjs-issue/manifest.m3u8.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load the above source into a videojs player that is version 7.2.3 or newer, in Chrome
2. Press play
3. Observe the video stalling during the first segment, while the audio continues to play

You can observe this here: https://50qr24o08l.codesandbox.io/

You can also see that here (on version 7.2.2) this does not occur by default: https://zxjv7pro3l.codesandbox.io/

That said, you can make this happen on 7.2.2 by pressing the "Play Special" button below the player in the example above, which makes the following javascript call:

```javascript
player.play().then(() => player.vhs.setCurrentTime(player.currentTime()));
```

This code is what was added in https://github.com/videojs/http-streaming/pull/204.

### Expected
Playback of the video and audio in Chrome

### Error output
No errors are showin in the console, but you can clearly see the video hang.

This does not occur in Firefox.

## Additional Information
From our investigation so far, this appears to have something to do with finding whether there is a buffered range for the current time, and if there is not, then it "resets" everything from the segment loader. In this particular case, the video has a DTS offset from the first frame of video to the first frame of audio, which, when fed to the source buffer on Chrome, results in the start timestamp of the first bufferedRange to be outside of the "fudge factor" used here: https://github.com/videojs/http-streaming/blob/master/src/ranges.js#L11.

In particular, in Chrome for this video, you see the following:

```javascript
player.buffered().start(0)
-> 0.066729
```

What this means is that when the call to `player.vjs.setCurrentTime(player.currentTime())` is made, `player.currentTime()` returns 0, and then the call to [find the buffered range for that timestamp](https://github.com/videojs/http-streaming/blob/master/src/master-playlist-controller.js#L811) ends up saying there is no buffered range for this time. This then goes on to [reset the segment loaders](https://github.com/videojs/http-streaming/blob/master/src/master-playlist-controller.js#L834), which appears to cause the corruption within the source buffer for the player element.

It's important to note that this works just fine on Firefox (and other browsers), and the video _also_ plays perfectly fine on Chrome prior to version 7.2.2.

I initially started looking into how to fix this, with something along the lines of messing with the fudge factor, but that will not necessarily fix this all the time. In addition, I'm not sure that reverting this will not re-introduce the issue that this PR was intended to fix initially. Happy to provide more help or suggested PRs if that would be useful, but at this point I thought it worth while to raise the issue.

### videojs-http-streaming version
videojs-http-streaming version 1.2.5 or newer

### videojs version
videojs version 7.2.3 or newer

### Browsers
Chrome (all versions seem to be affected, but specifically 71.0.3578.98 was tested most recently)
No other browsers seem to be affected

### Platforms
Mac OSX was used for testing.

### Other Plugins
N/A

### Other JavaScript
No libraries or frameworks other than video.js

**Comment by magikstm** [comment]
I can reproduce this issue in Chrome 71.0.3578.98 on Windows 7 x64.
As well as in Chrome 72.0.3626.96 on Windows 7 x64.

No issue in Firefox 65.0 on Windows 7 x64.

**Comment by jsanford8** [comment]
Just bumping this issue, as there has been no progress on it, and it appears this issue still exists in the latest videojs + vhs version (video.js 7.4.1)

**Comment by jsanford8** [comment]
This issue still occurs, in video.js 7.5.4 (whatever is currently the latest on unpkg). Please do not close this.

**Comment by jsanford8** [comment]
Bumping this one more time... any idea what's going on here?

**Comment by squarebracket** [comment]
@jsanford8 any chance you could open up the CORS restrictions?

By corruption do you mean a video freeze?

**Comment by jsanford8** [comment]
Yup, that's exactly what I see; the video freezes after about .5-1 seconds, and then resumes without issue after 5 seconds (in the second segment).

What CORS issues are you seeing? I'm don't see any CORS errors in that page, and it should be pretty open to CORS requests.

**Comment by squarebracket** [comment]
Thanks for the confirmation.

Chrome fails for me saying there is no Access-Control-Allow-Origin header, and in the network tab I indeed see no CORS header for https://s3.amazonaws.com/mux-justin-test/vjs-issue/manifest.m3u8.

**Comment by jsanford8** [comment]
Hmm, what version of Chrome are you using? Chrome 74.0.3729.169 on OSX doesn't show those same issues for me.

**Comment by jsanford8** [comment]
Also just to make sure you and I are looking at the same thing; are you looking at https://50qr24o08l.codesandbox.io/?

**Comment by squarebracket** [comment]
No, I'm talking about trying to play the asset from my dev player. The codesandbox works fine; I guess Amazon has it whitelisted or something.

**Comment by jsanford8** [comment]
Is your dev player running from localhost? I believe that should work as well, but I can try to check tomorrow.

**Comment by jsanford8** [comment]
The CORS config for that S3 bucket is

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
</CORSRule>
</CORSConfiguration>
```

If you know of a different config I should put on it, let me know and I'll do that!

**Comment by squarebracket** [comment]
Ah, I make a "pre-flight" HEAD request in my player wrapper, that's probably what's breaking it. If it's not too much trouble to add it to the allowed methods, that'd be super.

**Comment by jsanford8** [comment]
I should be able to add that first thing tomorrow

**Comment by squarebracket** [comment]
Great! Thanks.

**Comment by jsanford8** [comment]
@squarebracket - HEAD should work in a CORS request now. Let me know if anything else needs to be added!

**Comment by jsanford8** [comment]
bumping this, as it is still an issue in 7.6.0 of video.js.

**Comment by jsanford8** [comment]
I'm sorry, not sure why this was closed, this is _still_ an issue in latest VJS.

**Comment by jsanford8** [comment]
Seems to be fixed by #613 and/or #607

**Comment by jsanford8** [comment]
@gkatsev - any word on when 1.10.6 will be formally released with this fix in it (and when that might make it into video.js)?

**Comment by gkatsev** [comment]
Hey, sorry for not realizing earlier. VHS 1.10.6 is in Video.js 7.6.4 and 7.6.5. I can see that the original manifest is working in chrome in https://videojs.github.io/http-streaming/

@jsanford8 can you try out Video.js 7.6.5 and see if things are working for you?

**Comment by jsanford8** [comment]
@gkatsev looks good, thanks! Seems to be resolved now!
