### ISSUE TITLE
Seeking in HLS live stream.

### ISSUE THREAD

**Issue by Kshitij-agrawal2010** [videojs/http-streaming#423]
## Description
I am trying to use this with an HLS stream of a sliding window of 6 hours. But the seek bar only shows live. Is there some way I can get the seekbar?

## videojs version
video.js 7.4.1

### Browsers
what browsers are affected? please include browser and version for each
* Chrome 72

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* WIndows 10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* videojs-framebyframe: 1.0.1

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* I am using videojs in angular 4.

**Comment by gkatsev** [comment]
Check out the new liveui option in Video.js: https://docs.videojs.com/tutorial-live.html
