### ISSUE TITLE
Live streaming stop after 5 or 10 seconds because cache on navigator is active

### ISSUE THREAD

**Issue by JoeXavi** [videojs/http-streaming#436]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description: i am try to reproduce a livestreming over chrome desktop win 10 but stop afeter 5 or 10 seconds
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.<?php 
header("Cache-Control: no-cache, must-revalidate"); // HTTP/1.1
header("Expires: Sat, 1 Jul 2000 05:00:00 GMT"); // Fecha en el pasad

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Reproductor de video - Publimotos</title>
<link href="https://vjs.zencdn.net/7.4.1/video-js.css" rel="stylesheet">
<link rel="stylesheet" href="css/vsg-skin.css"/>

 
 
  <style type="text/css">
    body{
      max-width: 100%;
      overflow: hidden;
    }
    .videocontent{
      margin:auto;
      max-width: 100%;
    }
  </style>

</head>

<body>
<div class="wrapper">
  <div class="videocontent">
  <video id="my_video_1" class="video-js vjs-default-skin vjs-16-9 vjs-big-play-centered" controls preload="auto" width="640" height="264" poster="poster.jpg" controlsList="nodownload" >
    
    <source src="<?php if ($carpeta <>'') echo $carpeta; else echo 'live'; ?>/h264_master.m3u8" type="application/x-mpegURL"/>
  
    </p>
  </video>
</div>
</div>
  <script src="js/platform.js"></script>
  <script src="https://vjs.zencdn.net/7.4.1/video.js"></script>
 

  <script>

  
    var player = videojs('my_video_1',{
      html5: {
        hls:{
          enableLowInitialPlaylist:true,

          },
        nativeControlsForTouch:true,  
        //nativeAudioTracks: false,
        //nativeVideoTracks: false,
        controls: true,
        autoplay: false,
        fluid:true,
        preload: 'auto'
  }

    });

  
</script>
</body>
</html>

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. i am sure that is the cache http on navigators because i disable and play normally, however how disable on all client´s navigators
2.
3.

### Expected: play live streaming normally
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here: The first error show: VIDEOJS: WARN: Problem encountered with the current HLS playlist. Playlist no longer updating. Switching to another playlist.
After: VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the final playlist.

## Additional Information
Please include any additional information necessary here. Including the following: i try play the livestreaming normally, but stop after 5 or 10 seconds, howaver, i play the livestreaming and disable the cache in any navigator and the livestreaming reproduce easy normally

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version:  7.4.1
what version of videojs does this occur with?
video.js x.y.z

### Browsers: Firefox, Opera, Chrome on desktop
what browsers are affected? please include browser and version for each
*

### Platforms: i try on win10
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by Nyceane** [comment]
how is this closed?

**Comment by gkatsev** [comment]
Live streams do work in our player. I would recommend updating beyond Video.js 7.4, which was released almost 2 years ago.
Also, we have a new version of our playback engine coming out soon that further fixes many issues. For example https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=true&partial=false&url=https%3A%2F%2Flive.unified-streaming.com%2Fscte35%2Fscte35.isml%2F.m3u8&type=application%2Fx-mpegurl&keysystems=

Unfortunately, without a reproducible stream, there isn't much we can do to help.
