### ISSUE TITLE
[Query] Live Player Controls

### ISSUE THREAD

**Issue by vksbansal** [videojs/http-streaming#443]
Hi The Amazing team of Videojs VHS,

I am building a live stream player that is DVR enabled.

Following are my queries:

1. How to get the DRV(recorded content length)
2. How to get the live window to show a user if its watching live or not.

Many thanks for your help

Your Fan,
Vikas Bansal

**Comment by mister-ben** [comment]
Check out a couple of recent additions to Video.js - a liveTracker API, including `liveWindow()`, and a new live UI with DVR controls.

Both are detailed at https://docs.videojs.com/tutorial-live.html

**Comment by vksbansal** [comment]
@mister-ben  many thanks for your response
