### ISSUE TITLE
On First Seek on Live Stream (DVR enabled) segment gets cancled and seek fails

### ISSUE THREAD

**Issue by vksbansal** [videojs/http-streaming#450]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.
This is reproducible on all DVR enabled live streams.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

On First seek the segment gets cancelled and seek fails and video remains playing from the same end where it was.

<img width="715" alt="Screenshot 2019-04-01 at 3 48 32 PM" src="https://user-images.githubusercontent.com/43640008/55321848-4f143f80-5498-11e9-8e7e-79515ee8f040.png">

screen recording is attached
[seek-cancled.mov.zip](https://github.com/videojs/http-streaming/files/3028885/seek-cancled.mov.zip)

Secreen recoding gif (for clear video please download gif)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43640008/55322003-b205d680-5498-11e9-9e80-ca4097c2c130.gif)

Following is the code that is executed on seek click:

**player.currentTime(seekPoint)**

Please note that this happens with only first seek, subsequent (after clicks) it works fine.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
    "video.js": "^7.4.1",
    "@videojs/http-streaming": "^1.9.0",

### Browsers
what browsers are affected? please include browser and version for each
* all

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* osx

**Comment by vksbansal** [comment]
Hi @mister-ben, could you please help me with this... many many thanks :)

**Comment by vksbansal** [comment]
I am to reproduce the issue 100 present

steps:

pause live video player.pause()
seek to some point player.currentTime(seekPoint);
play the video player.play()
video will start to play from the live location, not from the seek point.
Please help, please.... its a major bug.

Hope you will pay attention

Many thanks,
Vikas Bansal

**Comment by vksbansal** [comment]
hi team,

please respond to this ticket.. please help

**Comment by vksbansal** [comment]
Please resolve this issue. do not mark is stale, its a major issue

**Comment by gkatsev** [comment]
There is a fix that is related to this as part of video.js 7.6 (https://github.com/videojs/video.js/pull/6062), can someone verify and see whether their stuff is fixed with it?

**Comment by vksbansal** [comment]
Thanks @gkatsev it seems to be solved. many thanks

**Comment by gkatsev** [comment]
Awesome, glad to hear it. We'll try to do better and circling back to issues like this next time.
