### ISSUE TITLE
Sidx is activated for playlists which have no sidx

### ISSUE THREAD

**Issue by couchcrew-thomas** [videojs/http-streaming#457]
## Description
The DASH LIVE stream stalls after the first segment was played. The player continues loading the manifest in an endless loop. It works fine on Shaka and DASH.js players.
Test case: https://jsbin.com/yaribiqipu/edit?html,output

## Sources
DASH LIVE: https://demo-dash-live.zahs.tv/sd/manifest.mpd

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load the stream
2. Start playback
3. Wait for the first segment to finish

### Expected
The live stream continues to play after the first segment.

### Error output
There are no console errors.

## Additional Information
Shaka player and DASH.js player can play the stream just fine.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 

### videojs version
what version of videojs does this occur with?
video.js 7.4.1

### Browsers
all latest browsers

### Other Plugins
none, just video.js with built in VHS.

### Other JavaScript
none

**Comment by vksbansal** [comment]
I am to reproduce the issue 100 present

steps:

1. pause live video **player.pause()**
2. seek to some point **player.currentTime(seekPoint);**
3. play the video **player.play()**
4. video will start to play from the live location, not from the seek point.

Please help, please.... its a major bug.

Hope you will pay attention

Many thanks,
Vikas Bansal

**Comment by squarebracket** [comment]
Something seems to be going wrong here when parsing the playlist, as it thinks it should be using sidx but then gets tripped up by the lack of sidxInfo.
