### ISSUE TITLE
Discontinuity in DTS leads to infinite buffering

### ISSUE THREAD

**Issue by stevendesu** [videojs/http-streaming#465]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

When a DTS discontinuity exists in the video (or at least, in the first video packet of the first TS file), it causes VideoJS to try and buffer the entire video - eventually running out of RAM or triggering a quota error

![Screen Shot 2019-04-11 at 3 12 39 PM](https://user-images.githubusercontent.com/1384974/55984800-47108880-5c6c-11e9-9384-def93beacd13.png)

Reduced test case:
https://jsbin.com/vokisimaco/

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

Reproduces the issue 100% of the time:
https://vcloud.blueframetech.com/file/hls/58102.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play the video above

### Expected
The video should play (it plays in QuickTime and HLS.js)

### Error output
The video fails to play and eventually crashes the browser or gives a "quota exceeded" error

## Additional Information
Please include any additional information necessary here. Including the following:
As mentioned, there is a discontinuity in the DTS values of the first video packet:

```
$ > ffprobe -v 0 -select_streams v -show_entries packet=dts https://di2g5yar1p6ph.cloudfront.net/1n3324e9l/passthru.hls/media-u1se044lq_1.ts | head -n 20
[PACKET]
dts=8589932882
[SIDE_DATA]
[/SIDE_DATA]
[/PACKET]
[PACKET]
dts=1260
[SIDE_DATA]
[/SIDE_DATA]
[/PACKET]
[PACKET]
dts=4320
[SIDE_DATA]
[/SIDE_DATA]
[/PACKET]
[PACKET]
dts=7290
[SIDE_DATA]
[/SIDE_DATA]
[/PACKET]
```

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.5.1

### videojs version
what version of videojs does this occur with?
video.js 7.4.1

### Browsers
what browsers are affected? please include browser and version for each
* Firefox 66.0.2
* Chrome 73.0.3683.103
* Probably all others

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Mac OS X 10.14.4
* Windows 10
* Probably all others

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
None

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
None

**Comment by mjneil** [comment]
Hi @stevendesu the player should be able to handle timestamp rollover, so this sounds like it might be a bug. I'm getting a CORS error for the `https://di2g5yar1p6ph.cloudfront.net/1n3324e9l/passthru.hls/index.m3u8` playlist. Could you update that to allow CORS?

**Comment by stevendesu** [comment]
@mjneil CORS should already be configured. Here's what I see in the network tab when I try to load the resource from https://www.google.com (simply typing `fetch` into the dev tools)

![cors](https://user-images.githubusercontent.com/1384974/56066803-f02bb180-5d46-11e9-94b2-4c93a80fab44.jpg)

What browser are you using, or what domain are you trying to access it from? I can double-check that there are no explicitly rejected referrers (like "localhost")

Worst-case scenario you should be able to cURL the M3U8 and upload it anywhere

**Comment by misteroneill** [comment]
This is likely identical to an issue we recently encountered at Brightcove.

We believe the cause is the transmuxer tracking timestamp rollovers independently; so, if the video and audio tracks have different DTS values where one rolls over and one does not, the audio gets thrown out, which puts the player in a buffering state waiting for the audio.

We have plans to address this in the near-to-mid term, but are waiting on other work first. Anyone who is interested is welcome to take a stab at it!
