### ISSUE TITLE
Safari: video hls stops after quality level change

### ISSUE THREAD

**Issue by Alexsandr** [videojs/http-streaming#501]
## Description
When the hls video quality level changes in safaris, sometimes the video pauses. The video starts playing if you change the playback time. The console displays errors.

Example: https://jsfiddle.net/exception777/xsucrz1m/32/

![Screenshot 1](https://user-images.githubusercontent.com/966534/57387284-dfe8e400-71d7-11e9-9c1b-a9ac12a5a135.png)
![Screenshot 2](https://user-images.githubusercontent.com/966534/57387285-dfe8e400-71d7-11e9-9231-2897ffd44648.png)

## Sources
Actual for any hls video 
Example: https://jsfiddle.net/exception777/xsucrz1m/32/

## Steps to reproduce
1. Change video quality in custom menu
2. Repeat if the video plays on

### Expected
After changing the quality of the video, it should continue to play.

### Error output
VIDEOJS: - "WARN:" - "Failed to set media source duration"

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
videojs-http-streaming 1.10.1

### videojs version
video.js 7.5.4

### Browsers
Safari 12

### Platforms
Mac Mojave

### Other Plugins
None

### Other JavaScript
None

**Comment by squarebracket** [comment]
Though we do plan to better support MSE on desktop Safari in the future, as you can see from the [compatibility section](https://github.com/videojs/http-streaming/#compatibility) only native support for Safari is considered stable at this time. If you're having trouble with MSE in Safari, you should use its native HLS support.

**Comment by Alexsandr** [comment]
Oк, thanks for your reply.
