### ISSUE TITLE
Please bump mux.js version to fix missing PTS/DTS crash on keyframes

### ISSUE THREAD

**Issue by cmacq2** [videojs/http-streaming#503]
## Description
As of `mux.js` 5.1.2 a particular crash is fixed when the first keyframe of a TS segment does not contain PTS/DTS information in the PES: https://github.com/videojs/mux.js/issues/250 However, videojs/http-streaming _pins_ the mux.js dependency to 5.1.1 currently. In order to benefit from the bug fix the version should be bumped to at least 5.1.2.

Once a new version of `@videojs/http-streaming` is available that fixes this, the `video.js` project should be updated likewise to bump _its_ pinned dependency on `@videojs/http-streaming` from 1.10.1 to at least the fixed version.

### videojs version
`@videojs/http-streaming`: versions up to current (1.10.1)
`video.js`: versions up to current (7.5.4)

### Browsers
All: this is a bug caused by missing error checking in mux.js prior to 5.1.1. 

### Platforms
All: this is a bug caused by missing error checking in mux.js prior to 5.1.1.

**Comment by gkatsev** [comment]
Thanks for the reminder, I closed the greenkeeper PR previously because I thought it only included the license related change. The update is merged in but we're not quite ready to make a VHS release yet, there are a couple of pending PRs that we want to get in (#469, #500, #502)
