### ISSUE TITLE
[BUG] getting green partition in video when setting overrideNative to true

### ISSUE THREAD

**Issue by vksbansal** [videojs/http-streaming#516]
## Description
Briefly describe the issue.
When playing a .m3u8 stream in safari and setting overrideNative to true then we are getting a side block with green colour (screenshot attached) this is happening all the streams that are provided XYZ channels
<img width="934" alt="Screenshot 2019-05-15 at 5 49 06 PM" src="https://user-images.githubusercontent.com/43640008/57775400-8eda7200-773a-11e9-99ca-4ddc39b30139.png">

## Sources
I can provide in a private email or slack

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. simply put the stream URL in src and play

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
1.10.2

### videojs version
what version of videojs does this occur with?
7.5.4

### Browsers
what browsers are affected? please include browser and version for each
OSX Safari

### Platforms
what platforms are affected? please include operating system and version or device and version for each
OSX

**Comment by squarebracket** [comment]
As you can see from the [compatibility section](https://github.com/videojs/http-streaming/#compatibility), only native support for Safari is available at this time.

**Comment by sabbulprimefocus** [comment]
I am facing also the same problem in the safari browser while using video js. please, anyone can suggest me.
