### ISSUE TITLE
Unable to get cueTags (Tag ID3)

### ISSUE THREAD

**Issue by Dardaxe** [videojs/http-streaming#521]
## Description
Hello,
I'm trying to implement **useCueTags** options to retrieve **segment Metadata** on a Video.js player.

I'm using official documentation (https://github.com/videojs/http-streaming#segment-metadata) on empty Video.js integration, but it seems player.getTracks() is always empty.

Here is an exemple:
https://jsbin.com/gugifanefo/edit?html,console,output

## Steps to reproduce
1. Set option **useCueTags** to true in player source
2. Try to get tracks with **player.textTracks()**
3. Property **length** is always empty (eg. player.textTracks().length)

### Expected
A track with ID3 tag and segment Metadata.

### Error output
No tracks added by option cueTags.

### videojs-http-streaming version
videojs-http-streaming 1.10.2

### videojs version
videojs 7.5.4

### Browsers
Tested on Firefox and Chrome (latest versions)

### Platforms
Windows 10 and Ubuntu 18.04

### Other Plugins
None

### Other JavaScript
None

**Comment by gkatsev** [comment]
The segments track isn't available instantly upon player creation, you'll want to listen to `addtrack` on the track list or at least `loadedmetadata` to wait for it to be available.
I've tweaked your example to work: https://jsbin.com/fuxavimove/edit?html,console,output

**Comment by Dardaxe** [comment]
Thanks for your help @gkatsev it works perfectly with HLS streaming and textTracks.

However I tried to retrieve current video segment metadata on a Dash stream and it seems that textTracks is empty : 
https://jsbin.com/wuniwazevi/edit?html,console,output

I want to retrieve metadata of the current video track to access video codec information using Dash container.

**Comment by gkatsev** [comment]
That's because you're playing it back using contrib-dash. If you use VHS as well, you should get it.
