### ISSUE TITLE
Is there an event that will let us know whether index has loaded (independently of playback)?

### ISSUE THREAD

**Issue by jayarjo** [videojs/http-streaming#537]
Just a question, 'cause I cannot find an answer anywhere...

Is there an event that will tell us if source has been successfully loaded?

I used to rely on `loadedmetadata`, but Chromes [autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) basically makes it useless, 'cause with disabled autoplay `loadedmetadata` doesn't seem to fire at all. I guess it requires playback to start to fire.

So I need to load the source, then seek to the specific point in a chunk and only after that launch the playback (or leave it paused, but prepared). If I attempt to seek, before the index has finished to load, seek doesn't have the full seekable range yet. Is there any event that will fire independently from playback and let me know if index has been loaded?

I'm asking 'cause I see index being requested and loaded, independently of playback. It's just that there's  no dedicated event that will notify us about the fact. With autoplay policy enabled I think it is a required event to have.

**Comment by jayarjo** [comment]
Text snippet [here](https://github.com/videojs/http-streaming#loadedmetadata) says:

> **loadedmetadata**
> Fired after the first segment is downloaded for a playlist. This will not happen until playback if video.js's `metadata` setting is `none`

First of all there seems to be no `metadata` setting in video.js. I believe it's about `preload` setting that can take value of one of: `auto`, `metadata` or `none`. And form what I see changing `preload` setting doesn't affect firing of `loadedmetadata` in any way - `loadedmetadata` still doesn't fire, if playback is not started.

**Comment by jayarjo** [comment]
Some further activity.

**Comment by gkatsev** [comment]
Thanks for your patience, it does seem like there may be a bug here. I'll investigate what should happen.

**Comment by gkatsev** [comment]
Actually, just spent some more time investigating and I think it's working as expected. Got confused for a second because my test stream was a live stream, and we don't preload anything then, so, the event won't get triggered until playback starts.
What type of stream are you loading? Have a live reduced test case I can take a look at?
