### ISSUE TITLE
Audio codec dont supported mp4a.40.34

### ISSUE THREAD

**Issue by ctaity** [videojs/http-streaming#543]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Audio codec dont supported

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
encode a video HLS with: mp4a.40.34

### Expected
Reproduce video.

### Error output
Uncaught DOMException: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('audio/mp4;codecs=" mp4a.40.34"') is unsupported.

### videojs-http-streaming version
videojs-http-streaming bundle with videojs 7.5.4

### videojs version
what version of videojs does this occur with?
videojs 7.5.4

### Browsers
Crhome, Firefox

### Platforms
All

**Comment by ctaity** [comment]
Yes with hls.js works. Hls.js put undefined audio codec. And let the mediasource fallback

**Comment by himalreddy** [comment]
what is the solution to this issue for the persons who are using the only VideoJS7.6.5?

**Comment by Baytars** [comment]
It seems browser specific. In Firefox my m3u8 source does not play in Video.js but plays in HLS.js, and in Microsoft Edge the same m3u8 source plays!
