### ISSUE TITLE
player.videoWidth()/player.videoHeight() are wrong in older WebKit

### ISSUE THREAD

**Issue by jayarjo** [videojs/http-streaming#552]
Here's a meta of the HLS stream as I receive it. 

```
#EXTM3U
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,RESOLUTION=1024x576,FRAME-RATE=25.000,CODECS="avc1.4d001f,mp4a.40.2",AVERAGE-BANDWIDTH=1259858,BANDWIDTH=1574822
tracks-v1a1/mono.m3u8?...
```

Notice that RESOLUTION is equal to 1024x576. However `player.videoWidth()/player.videoHeight()` report it as 720x576. This doesn't happen in the latest Chrome, however does - in legacy Safari unning on older Tizen TVs. User-agent: `Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/2.4.0 TV Safari/538.1`.

Doesn't VHS extract RESOLUTION from the stream to be available through `videoWidth/videoHeight` methods?

**Comment by jayarjo** [comment]
Where does video.js player take it's initial width/height from?

**Comment by gkatsev** [comment]
These methods call out to the video element's width and height properties https://html.spec.whatwg.org/multipage/embedded-content-other.html#dom-dim-width.
I would assume that this means that these older devices or tizen tv's are incorrect in their reporting of the size of the video.

**Comment by jayarjo** [comment]
Width and height of the `video` DOM element are reported properly by `width()/height()` methods, it's only the dimensions of the picture that are skewed inside the `video` element. It is clear how video.js retrieves the width and height of the DOM element, but where does it get the dimensions of the video picture from? And I wonder if VHS is trying anything in addition to that? Or simply goes with whatever it gets from video.js?
