### ISSUE TITLE
Different behavior between iOS and Android/Desktop when stream segments are not immediately available

### ISSUE THREAD

**Issue by Schweinekalt** [videojs/http-streaming#554]
## Description
Briefly describe the issue.

The player on iOS is the only one that cannot handle segments that are not immediately reachable. 

Behavior Android/Desktop:
If a stream segment is not reachable, the player pauses and a loading icon appears. If the missing segment becomes reachable, the player continues playing.

Behavior iOS:
If a stream segment is not reachable, the player continues to play, but with a black screen. The player ignores the missing part. Player remains black even after passing the gap.

Is it possible to match the behavior of the iOS player to the behavior of the other players?

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Take a stream that consists of several parts, e.g.: part1.ts, part2.ts, part3.ts
2. Remove part2.ts from the folder.
3. Start the player.
4 (Android/Desktop player). Player plays up to the gap, stops, and shows a loading icon.
If you move part2.ts back to the folder, Android/Desktop player will immediately continue playing without complaint.
4 (iOS player). Player plays up to the gap, turns black and seemingly continues playing (timeline keeps progressing). Player remains black even after passing the gap.
If you move part2.ts back to the folder, the player will not register that the missing segment has become available.

### Expected
Please describe what you expected to happen that did not happen in the description.

I expected the iOS player to stop at the missing segment and wait for it to become available, just like on all the other platforms.

### Error output
* No errors are displayed.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
* videojs-http-streaming 1.10.3

### videojs version
what version of videojs does this occur with?
* videojs  7.5.5.

### Browsers
what browsers are affected? please include browser and version for each
* Mobile-Safari all versions

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* iOS all versions

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* no

### Other JavaScript
* no

**Comment by mister-ben** [comment]
Unfortunatelty you can't influence the playback behaviour on iOS, as it's always native playback.

**Comment by zzzzzero000** [comment]
part2.ts被删除后，请求报错，请问怎么样才能拦截到这个报错啊
