### ISSUE TITLE
DASH doesn't follow <Location>

### ISSUE THREAD

**Issue by TomHetmer** [videojs/http-streaming#557]
## Description
DASH playlist are loaded from the same (invalid) location instead of following <Location> redirects in the manifest.
## Sources
http://1425889403.rsc.cdn77.org/ls-45420-1/rewind-60.mpd

## Steps to reproduce
Have a DASH manifest that always contains ie.
`<Location>https://xxx/rewind-60.mpd?resume=1514764800:1561118402.431117</Location>`
The location changes for each request.
Video.js keeps using the main URL and fails to load any new segments.

### Expected
Video.js will load the mpd from the updated URL every time.

### videojs-http-streaming version
videojs-http-streaming 1.9.3

### videojs version
video.js 7.5.5

**Comment by nzt4567** [comment]
Hi, this happens to us as well, any chance on taking a look at this please? We wanted to switch to video.js from shaka in our new projects but this currently seems to be a dealbreaker 😢
