### ISSUE TITLE
HLS `MEDIA_ERR_SRC_NOT_SUPPORTED` only on Chrome

### ISSUE THREAD

**Issue by yurtaev** [videojs/http-streaming#592]
```
VIDEOJS: ERROR: DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

VIDEOJS: ERROR: DOMException: Failed to set the 'duration' property on 'MediaSource': The MediaSource's readyState is not 'open'.
```

Maybe related:

- https://github.com/videojs/http-streaming/issues/143
- https://github.com/videojs/mux.js/issues/136
- MSE workaround for Chrome https://github.com/videojs/mux.js/blob/master/lib/mp4/transmuxer.js#L308

Demo:

- https://videojs.github.io/http-streaming/
- source https://s3-eu-west-1.amazonaws.com/yurtaev.link/public/test/index.m3u8
- works on hls.js https://hls-js.netlify.com/demo/?src=https%3A%2F%2Fs3-eu-west-1.amazonaws.com%2Fyurtaev.link%2Fpublic%2Ftest%2Findex.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsImVuYWJsZVdvcmtlciI6dHJ1ZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xLCJ3aWRldmluZUxpY2Vuc2VVcmwiOiIifQ==

Logs `chrome://media-internals/`:

```
render_id: 2081
player_id: 67
origin_url: https://videojs.github.io/
frame_url: https://videojs.github.io/http-streaming/
frame_title: VideoJS HTTP Streaming
surface_layer_mode: kAlways
url: blob:https://videojs.github.io/282ac476-05b9-4a77-80e4-2b8c52d57d5f
info: ChunkDemuxer: buffering by PTS
pipeline_state: kStopped
found_video_stream: true
video_codec_name: h264
error: Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=inf
pipeline_error: CHUNK_DEMUXER_ERROR_APPEND_FAILED
duration: 48
```

Have you any idea?

**Comment by EyMaddis** [comment]
I have the same problem with a dash playlist that worked on [dash.js example sites](https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html), and also the [older version](https://videojs.github.io/videojs-contrib-dash/), but with the latest version that uses video.js 7:
https://videojs.github.io/videojs-contrib-dash/

**Comment by EyMaddis** [comment]
This is still relevant

**Comment by mithlesh-kumar** [comment]
any solution?

**Comment by canhnm** [comment]
Any update?

**Comment by Oo121oO** [comment]
render_id: 2658
player_id: 58
origin_url: file:///
kFrameUrl: file:///Users/xxxx/Desktop/index.html
kFrameTitle: xxxx===m3u8===xxxx
url: blob:null/31cce274-fc30-4395-a5c4-684382b11e1b
kTextTracks: 
info: ChunkDemuxer
pipeline_state: kStopped
error: Append: stream parsing failed. Data size=20526 append_window_start=0 append_window_end=inf
pipeline_error: CHUNK_DEMUXER_ERROR_APPEND_FAILED
duration: 609.687

same problem～～@ver7.10.2
