### ISSUE TITLE
Use http-streaming with videojs 7

### ISSUE THREAD

**Issue by teoeter** [videojs/http-streaming#602]
I need fmp4 support(edge), so in the version 1.11-alpha.1 it's implemented. 
My question is how to use http-streaming with the latest versions of videojs that have it integrated ?
Do I have to revert to version 6 ?

**Comment by mister-ben** [comment]
There's video.core.min.js which doesn't have VHS. We still need to document that properly (videojs/video.js/issues/5932)

**Comment by gkatsev** [comment]
fmp4 support should be available in the stable version of VHS. I would *strongly* advise against using the alpha release in production.
