### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by flaviohenriquecbc** [videojs/http-streaming#651]
## Description
For some files, I'm receiving the error below:

```
Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at Object.sidx [as parseSidx] (videojs-http-streaming.js:16034)
    at videojs-http-streaming.js:16737
    at Object.callback (videojs-http-streaming.js:2927)
    at cbOnce (video.core.js:8418)
    at XMLHttpRequest.loadFunc (video.core.js:8492)
```

I hosted on my website an example (not working):
- https://www.gymondo.com/tmp/videojs/videojs-http-streaming.html
- https://www.gymondo.com/tmp/videojs/videojs-http-streaming-2.html

I tried another player and it works properly:
- https://www.gymondo.com/tmp/videojs/videojs-dash.html
- https://www.gymondo.com/tmp/videojs/videojs-dash-2.html

## Sources
I have the same code in two places:
- https://www.gymondo.com/tmp/videojs/videojs-http-streaming.html
- https://jsbin.com/yubapigonu/1/edit?html,output (Needs to disable CORS of the browser)
- This also works https://videojs.github.io/videojs-contrib-dash/ (needs to disable CORS of the browser and change the Video URL to https://amd-gymondo-adaptive-videos.akamaized.net/resources/3140/20190711093728/mpeg-dash/manifest_en_music.mpd)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Check website: https://www.gymondo.com/tmp/videojs/videojs-http-streaming.html

### Expected
The video should play

### Error output
This is the error received:

<img width="572" alt="error-videojs" src="https://user-images.githubusercontent.com/1553609/64275418-c6696600-cf45-11e9-9b87-d49a483b819c.png">

## Additional Information
None

### videojs-http-streaming version
@videojs/http-streaming@1.10.5

### videojs version
video.js@7.6.4/dist/alt/video.core.js

### Browsers
All browsers

### Platforms
Any

### Other Plugins
No

### Other JavaScript
None

**Comment by gkatsev** [comment]
Seems like the index range for the audio segments is 12 bytes short. So, instead of a range of `832-2327` it should be `832-2339`. This makes it work in our player, additionally, it seems to remove all the errors I notice in the dashjs example.
We'll investigate whether we can be more defensive and make it work but ideally the mpd would be updated with the correct range. It's unlikely that we'll have a change for this shortly as most team members are about to be going on break for the next couple of weeks.

**Comment by vahidahmad** [comment]
I get the same exact error!

**Comment by vishalkalola1** [comment]
I also get same error.
