### ISSUE TITLE
support hls_playlist_length;

### ISSUE THREAD

**Issue by ingen2** [videojs/http-streaming#652]
Hi
I set `hls_playlist_length 30m;`  on my hls server , but did not change on player.
But jwplayer support this feature of hls:
my hls url :
`https://tv.razavi.ir/hls/tv_3.m3u8`
jwplayer test:
`https://developer.jwplayer.com/tools/stream-tester/`

screenshot:
![Screenshot_20190906_185330](https://user-images.githubusercontent.com/8234033/64435530-e6c92a00-d0d7-11e9-9745-5024a37678eb.png)

**Comment by gkatsev** [comment]
I'm not exactly sure what you're asking for. Are you asking to be able to seek in the stream? If so, take a look at this doc: https://docs.videojs.com/tutorial-live.html#the-new-user-interface. We previously didn't have a UI for it, but we added one recently.

**Comment by mister-ben** [comment]
I get DVR controls with that stream. If you don't, make sure you're using an up to date version of Video.js - the live UI was added in 7.4.
