### ISSUE TITLE
Not supportted for http m3u8 streaming?

### ISSUE THREAD

**Issue by nisabuan** [videojs/http-streaming#662]
## Description
Can not play http link streaming example : http://ott.tvri.co.id/Content/HLS/Live/Channel(TVRINasional)/index.m3u8

## Sources
http://ott.tvri.co.id/Content/HLS/Live/Channel(TVRINasional)/index.m3u8

## Steps to reproduce

1. trying in localhost (fail)
2. with server https (fail)
3. with server http (fail)

### Expected
-

### Error output
The media could not be loaded, either because the server or network failed or because the format is not supported.

### videojs-http-streaming version
latest

### videojs version
latest
### Browsers
chrome, firefox,edge

### Platforms
win 10

### Other Plugins
no

### Other JavaScript
no

**Comment by gkatsev** [comment]
Looks like that stream doesn't have CORS headers which we require for playback. See [hosting considerations](https://github.com/videojs/http-streaming#hosting-considerations).
