### ISSUE TITLE
Allow player to skip bad segments

### ISSUE THREAD

**Issue by tvbegovic** [videojs/http-streaming#668]
## Description
When player encounters bad ts segment, it hangs. It should skip them and find the first correct segment.

## Sources
m3u8 list: 
https://accessb.streamsink.com/hls-africa/tv1/GetVODClip.m3u8?date=2019-09-08&start=12:00:00&end=13:00:00

## Steps to reproduce
1. Open the codepen https://codepen.io/tvbegovic/pen/ExxYyLN
2. Click on play button in Video
3. The video hangs after 5-6 seconds and no recovery

## Results
busy indicator in video player. No playback.

### Expected
Player skipping bad segment or stopping as some other players do, e.g. https://castr.io/hlsplayer

### Error output
No errors in console.

### videojs-http-streaming version
video.js 7.6.5 (http-streaming integrated)
### videojs version
video.js 7.6.5

### Browsers
Chrome, Brave, any browser in fact

### Platforms
Windows 10

### Other Plugins
No

### Other JavaScript
No, in codepen on the link above there are no other libraries.

**Comment by jtoy** [comment]
dead?

**Comment by Dokterfrits** [comment]
How to handle this? Any solution available?
