### ISSUE TITLE
Expose the playlist selector functions implemented on this library.

### ISSUE THREAD

**Issue by salqueng** [videojs/http-streaming#676]
##  Description
http-streaming provides the way to implement custom playlist switch algorithms. (ex. `player.hls.selectPlaylist`)
Also, this library contains various playlist select algorithms on `playlist-selectors.js`.  
ex)
`movingAverageBandwidthSelector` - algorithm based on moving average. more responsive to current playback bandwidth.
`simpleSelector` - good start point for building custom algorithms.

However, those selector algorithms are not exposed (except few ones), so developers cannot use already implemented algorithms, without recompiling or copy-and-pasting. 

### Suggestion
Add `PlaylistSelectors` key / value to Hls object on `videojs-http-streaming.js`.

```javascript
import PlaylistSelectors from "./playlist-selectors";

/* codes */

const Hls = {
  /* other exposes */
  // similar to exposing Playlist / PlaylistLoader
  PlaylistSelectors
};

/* codes */
/* Hls object is exported,
   so users can use selector algorithms via Hls.PlaylistSelectors */
```

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.10.x / 1.11.x

### videojs version
what version of videojs does this occur with?
video.js 7.6.x

**Comment by gkatsev** [comment]
It would be nice to expose them but at the same time it'll make it more complicated because we potentially couldn't then tweak the methods as people relying on it could then break.
