### ISSUE TITLE
Qualities not loading and addqualitylevel event not triggered

### ISSUE THREAD

**Issue by jascaldeira** [videojs/http-streaming#677]
## Description
Hello,
If i open the player, in a new tab WITHOUT FOCUSING IT (middle mouse button open for example), and let some time pass (so all javascript may run), the quality levels are not loaded and addqualitylevel event is not even triggered... if you do the same but focusing the window, all runs good.

## Steps to reproduce

1. Open a video page with m3u8 source on a new tab
2. Wait a couple of seconds
3. Go see it (no qualities loaded)

### Expected
Qualities Loaded

### videojs-http-streaming version
videojs-http-streaming 1.9.3

### videojs version
video.js 7.6.5 (im sure that this happens since 7.1.0 or older)

### Browsers
Only tested with Chrome

### Platforms
Only tested with windows 10

### Other Plugins
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Does it load the qualities when you then switch to the tab?
I know that Chrome basically disallows videos from loading in the background so if it ends up loading properly when you focus the tab it is then working as expected as it is a browser limitation.

**Comment by jascaldeira** [comment]
Hello @gkatsev ,
Sadly, no it doesn't... In this use case, the qualities never load up.

**Comment by gkatsev** [comment]
Interesting. Does the video end up playing? Or is just completely broken?
I guess we'll have to investigate.

**Comment by jascaldeira** [comment]
hello @gkatsev , sorry for the delay in the answer.
Yes. the video end up playing. I just cant change his quality.

**Comment by gkatsev** [comment]
Fixed as part of #707, release soon.
