### ISSUE TITLE
HLS does not play in Chrome desktop

### ISSUE THREAD

**Issue by Sivitas** [videojs/http-streaming#679]
## Description
We noticed that our hls files with a single 1080p stream fails to play in videojs on chrome desktop only. No errors, just forever loading

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. test hls: https://streams.unreel.me/stream.ismd/manifest.m3u8?stream=FD/_aLPVievTIrNAOOoAhO8rprNTV-TqAw_Rsi78_n1Y/pgm-01-agenda-verde-ok
2. load using [http-streaming](https://videojs.github.io/http-streaming/) in Chrome on desktop

### Expected
Should play

### Actual
Does not play, loads forever

### Error output
None

## Additional Information
Works when using Chrome mobile, Safari mobile/desktop, and other streaming services like [jwplayer](https://developer.jwplayer.com/tools/stream-tester/)
#### videojs
latest
#### browsers
chrome: 77.0.3865.120
#### OSes
MacOs Mojave 10.14.6

**Comment by matthewwilson** [comment]
We are seeing this issue as well. Some videos play if preload is set to "none" but that stops other videos from playing which play when preload is "auto" or "metadata"

**Comment by gkatsev** [comment]
That's a weird one. Not exactly sure the root cause but I did notice that Safari took a really long time for me for it to load and actually play back. In Chrome, VHS seems to think there's only one media playlist and it only tries to load the audio-only rendition. This likely causes issues as we probably try to create a video and audio buffer and then chrome just waits forever.

**Comment by ZHAJOR** [comment]
I'm having the same issue with one of my feed.
I want to add a behavior really weird, if you play (so just trying to load), double click to go full screen, wait a bit, then exit full screen, click on picture-in-picture, then click on the play button, sometimes it's loading, then we can exit the picture-in-picture and it's playing as usual.
My steps above are not 100% but I was able to reproduce ~33%.

Here it's stuck:
```
VIDEOJS: DEBUG: VHS: SegmentLoader[main] > appending [5] of [0, 1275] from playlist [0] [25.025000000000002 => 29.996633333333335] in timeline [0] video.min.js:12:695
VIDEOJS: DEBUG: VHS: SourceUpdater[main][video/mp2t; codecs="avc1.4d400d, mp4a.40.2"] > buffered [**1.046395** => 30.038395] video.min.js:12:695
VIDEOJS: DEBUG: VHS: SegmentLoader[main] > APPENDING -> READY video.min.js:12:695
VIDEOJS: DEBUG: VHS: SyncController > syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]
```
Just after clicking on play from the picture-in-picture:
```
VIDEOJS: DEBUG: VHS: PlaybackWatcher > Stopped at 0, setting timer for 1.046395, seeking to 1.046395 video.min.js:12:695
VIDEOJS: DEBUG: VHS: PlaybackWatcher > cancelTimer_ video.min.js:12:695
VIDEOJS: DEBUG: VHS: PlaybackWatcher > skipTheGap_: currentTime: 0 scheduled currentTime: 0 nextRange start: 1.046395
```

Usually the initial buffered is more something like this:
`VIDEOJS: DEBUG: VHS: SourceUpdater[main][video/mp2t; codecs="avc1.4d400d, mp4a.40.2"] > buffered [**0.066733** => 4.961395]`

Tested on Firefox 72/Ubuntu.
