### ISSUE TITLE
Getting less audio tracks compare to hls.js plugin.

### ISSUE THREAD

**Issue by murtaz53** [videojs/http-streaming#684]
## Description
I am using below hls source with this plugin. when I get audio tracks using this plugin, I am getting 2 tracks. but If I use hls.js plugin **(https://github.com/video-dev/hls.js)**, I am getting 4 tracks, 2 more tracks with different audio groups. So how can I get all 4 tracks with this plugin?

## Sources
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

## Steps to reproduce

1. open **https://video-dev.github.io/hls.js/demo/** and enter **https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8** in url.
2.  when you click *Audio-tracks* button at bottom, you will find 4 audio tracks, as per below screenshot

![image](https://user-images.githubusercontent.com/42437702/68918142-06916400-0793-11ea-84ca-fe4629af6d9e.png)

3. you can switch audio tracks group by clicking on tracks (i.e hls.audioTrack = 1)

##  Results
when we use http-streaming plugin, we are getting only 2 audio tracks, as per below screenshot

![image](https://user-images.githubusercontent.com/42437702/68918129-f083a380-0792-11ea-8c22-f1c413dcbdb2.png)

### Expected
so how can we get all audio tracks or change current audio group using this plugin.

**Comment by murtaz53** [comment]
@forbesjo : can you help please?

**Comment by murtaz53** [comment]
> ## Description
> I am using below hls source with this plugin. when I get audio tracks using this plugin, I am getting 2 tracks. but If I use hls.js plugin **(https://github.com/video-dev/hls.js)**, I am getting 4 tracks, 2 more tracks with different audio groups. So how can I get all 4 tracks with this plugin?
> 
> ## Sources
> https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
> 
> ## Steps to reproduce
> 1. open **https://video-dev.github.io/hls.js/demo/** and enter **https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8** in url.
> 2. when you click _Audio-tracks_ button at bottom, you will find 4 audio tracks, as per below screenshot
> 
> ![image](https://user-images.githubusercontent.com/42437702/68918142-06916400-0793-11ea-84ca-fe4629af6d9e.png)
> 
> 1. you can switch audio tracks group by clicking on tracks (i.e hls.audioTrack = 1)
> 
> ## Results
> when we use http-streaming plugin, we are getting only 2 audio tracks, as per below screenshot
> 
> ![image](https://user-images.githubusercontent.com/42437702/68918129-f083a380-0792-11ea-8c22-f1c413dcbdb2.png)
> 
> ### Expected
> so how can we get all audio tracks or change current audio group using this plugin.



> ## Description
> I am using below hls source with this plugin. when I get audio tracks using this plugin, I am getting 2 tracks. but If I use hls.js plugin **(https://github.com/video-dev/hls.js)**, I am getting 4 tracks, 2 more tracks with different audio groups. So how can I get all 4 tracks with this plugin?
> 
> ## Sources
> https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
> 
> ## Steps to reproduce
> 1. open **https://video-dev.github.io/hls.js/demo/** and enter **https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8** in url.
> 2. when you click _Audio-tracks_ button at bottom, you will find 4 audio tracks, as per below screenshot
> 
> ![image](https://user-images.githubusercontent.com/42437702/68918142-06916400-0793-11ea-84ca-fe4629af6d9e.png)
> 
> 1. you can switch audio tracks group by clicking on tracks (i.e hls.audioTrack = 1)
> 
> ## Results
> when we use http-streaming plugin, we are getting only 2 audio tracks, as per below screenshot
> 
> ![image](https://user-images.githubusercontent.com/42437702/68918129-f083a380-0792-11ea-8c22-f1c413dcbdb2.png)
> 
> ### Expected
> so how can we get all audio tracks or change current audio group using this plugin.

**Comment by gkatsev** [comment]
Looks like the hls.js example page is showing all the available audio tracks regardless of what the manifest is specifying.
In the manifest, there are four audio tracks, but they are grouped into two groups stereo and surround with an English and a dubbing track. Then, each video track specifying which of these groups is to be used with it. In the audio tracks menu we only show the audio tracks that the manifest has specified should be used with the currently playing video track. Introspecting VHS, I can see that it does show that there are four audio tracks.
To an end user, specifying all 4 audio tracks would be confusing, so, we only display the ones that should be available based on the information provided in the manifest.

Thanks, hope that helps understand the difference.
