### ISSUE TITLE
Chrome “Aw, Snap!”, on windows, live stream m3u8, memory leak, used ~4gb, spent 3 hours

### ISSUE THREAD

**Issue by gyerts** [videojs/http-streaming#687]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

## Description
I found memory leaks ON WINDOWS when using videojs-http-streaming library which is integrated by default into the newest videojs library. Demo of library you can find here on official site https://videojs.github.io/http-streaming/

This question also asked here on stackoverflow https://stackoverflow.com/questions/58978088/videojs-http-streaming-chrome-aw-snap-windows-live-stream-memory-leak/58978342#58978342

## Sources
https://videojs.github.io/http-streaming/

## Steps to reproduce
1. Run Windows 10
2. Open Chrome 78.0.3904
3. Open link https://videojs.github.io/http-streaming/
4. wait 3 hours until browser tab crash

### Expected
Memory remains the same, as on linux OS

### Error output
memory always grows, and in 3 hours, memory size is ~4gb and browser tab crashes "Aw, snap"

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.10.3

### videojs version
video.js 7.6.0

### Browsers
what browsers are affected? please include browser and version for each
* Chrome 78.0.3904

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Windows 10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* "videojs-contrib-quality-levels": "^2.0.9"

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* "animated-scroll-to": "^1.2.2",
      "axios": "^0.19.0",
      "classnames": "^2.2.6",
      "connected-react-router": "^6.4.0",
      "currency-formatter": "^1.5.4",
      "fullscreen-polyfill": "^1.0.2",
      "gulp": "^4.0.2",
      "gulp-rename": "^1.4.0",
      "history": "^4.9.0",
      "intro.js": "^2.9.3",
      "intro.js-react": "^0.2.0",
      "jquery": "^3.4.1",
      "jquery-smooth-scroll": "^2.2.0",
      "jsonschema": "^1.2.4",
      "luxon": "^1.17.2",
      "memoize-one": "^5.1.1",
      "qs": "^6.7.0",
      "react": "^16.8.6",
      "react-act": "^1.0.1",
      "react-dom": "^16.8.6",
      "react-facebook-login": "^4.1.1",
      "react-google-login": "^5.0.5",
      "react-helmet": "^5.2.1",
      "react-hot-loader": "^4.12.6",
      "react-keyboard-event-handler": "^1.5.1",
      "react-load-image": "^0.1.7",
      "react-loadable": "^5.5.0",
      "react-paginate": "^6.3.0",
      "react-perfect-scrollbar": "^1.5.3",
      "react-player-controls": "^1.1.0",
      "react-redux": "^7.1.0",
      "react-router-dom": "^5.0.1",
      "react-scripts": "3.0.1",
      "react-simple-keyboard": "^2.0.4",
      "react-video-seek-slider": "^2.1.2",
      "react-virtualized-auto-sizer": "^1.0.2",
      "react-visibility-sensor": "^5.1.1",
      "react-window": "^1.8.5",
      "react-window-infinite-loader": "^1.0.4",
      "redux": "^4.0.1",
      "redux-act": "^1.7.6",
      "redux-devtools-extension": "^2.13.8",
      "redux-thunk": "^2.3.0",
      "validate.js": "^0.13.1",
      "video.js": "^7.6.0",
      "videojs-contrib-quality-levels": "^2.0.9"

**Comment by zsilbi** [comment]
@gyerts: https://github.com/videojs/m3u8-parser/issues/164
