### ISSUE TITLE
Document supported codecs / formats

### ISSUE THREAD

**Issue by thenewguy** [videojs/http-streaming#689]
There are starting to be many possible codecs and formats available for http streaming compared to the original h264 & aac-lc audio muxed together in a transport stream.

Please document the supported combinations.  For example, is Opus in fmp4 supported?  Is vp9 in fmp4 supported?  Per issue #144 it isn't as simple as "does the browser support this?"

A simple table on the README would be  huge help.

**Comment by Meridix** [comment]
Keep open

**Comment by popler** [comment]
Hi, is something change in mp3 audio support? Do you have any plans to support this codec in HLS?

**Comment by gkatsev** [comment]
Yeah, it's probably worth putting it in.

mp3 support is something we'd like to do but we don't have the bandwidth to do it ourselves right now.

**Comment by Meridix** [comment]
keep open

**Comment by mister-ben** [comment]
https://github.com/videojs/http-streaming/blob/master/docs/supported-features.md was recently added.

**Comment by gkatsev** [comment]
I would call that document the resolution for this. Though, it needs some updates (like addition of HEVC and removal of sample-aes).
