### ISSUE TITLE
Can I play encrypted VOD  by videojs-flash?

### ISSUE THREAD

**Issue by saifeiLee** [videojs/http-streaming#690]
Can I play encrypted VOD , Such as AES128 encrypted HLS, by videojs-flash? I am looking for a way to accomplish DRM on IE10. Or could you please give me some advice? Thank you so much!!!

**Comment by gkatsev** [comment]
Are you talking about HLSe (encrypted HLS like https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.4) or actual DRM like Playready?

**Comment by saifeiLee** [comment]
> Are you talking about HLSe (encrypted HLS like https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.4) or actual DRM like Playready?

I mean encrypt/decrypt video by EXT-X-KEY.

**Comment by gkatsev** [comment]
videojs-flash won't play back HLS but you can try out https://github.com/brightcove/videojs-flashls-source-handler

**Comment by saifeiLee** [comment]
> videojs-flash won't play back HLS but you can try out https://github.com/brightcove/videojs-flashls-source-handler

Thank you! It did help me.

**Comment by gkatsev** [comment]
You're welcome.
