### ISSUE TITLE
I want to encrypt HLS AES-128 key to implement content protection

### ISSUE THREAD

**Issue by saifeiLee** [videojs/http-streaming#692]
## Description

Hello.(Sorry for my bad English.)
My goal is encrypting HLS AES-128 key and to decrypt it in player, so that I can protect my video content. My idea is modifying HLS key-loading logic in http-streaming plugin. Now, I have clone videojs and http-streaming project. And I have added code to http-streaming. But, when I try to use `npm link` to integrate local http-streaming package to local videojs,  I failed. I dont know what to do next.
Could you please give some advice:
1. If I want to develop http-streaming plugin locally, how to set up the environment and debug?
2. Is there a better way to accomplish my goal?

Thanks a lot. May you have a good day~!

**Comment by Brainiarc7** [comment]
Hello there,

This, in your case, can be done at the packaging side, depending on your workflow.
FFmpeg's HLS muxer and Shaka packager support this feature.

**Comment by saifeiLee** [comment]
> Hello there,
> 
> This, in your case, can be done at the packaging side, depending on your workflow.
> FFmpeg's HLS muxer and Shaka packager support this feature.

Thank you so much!!! Best wishes to you~!!
