### ISSUE TITLE
How to get hls bandwidth properties

### ISSUE THREAD

**Issue by huangdaman** [videojs/http-streaming#703]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Hey, may I ask what browser version the player.tech ().hls property is compatible with, because I tried to get the bandwidth in the hls property on a lower version of the browser and found that it is not available. Or the lower version browser obtained the hls attribute from another location.
By the way, is was work fine on chrome77

## Steps to reproduce
1.console.log(player.tech().hls.stats.bandwidth )
2.
3.

## Results
There is no hls attribute

### Expected
Successfully obtained bandwidth attributes of hls

### Error output
Uncaught TypeError: Cannot read property 'stats' of undefined

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
Is was auto included by videoJS

### videojs version
what version of videojs does this occur with?
video.js 7.6.5

### Browsers
what browsers are affected? please include browser and version for each
Chromium M47 ~ Chromium M63

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Tizen TV & LG TV

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
IMA

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
The HLS property is only available when native playback isn't being used. Take a look at https://github.com/videojs/http-streaming#overridenative. Platforms like TVs often have native HLS implementations which we defer to by default.
A recommendation would be to set overrideNative to something like `!videojs.browser.IS_ANY_SAFARI` to let safari handle HLS natively but not other browsers and devices.
Hope this helps.

**Comment by Gemerz** [comment]
@huangdaman    #6194  According to this issues which can help you show tech().hls 
 properties.Especially the nativeTextTracks , nativeAudioTracks, nativeVideoTracks must be false.Hopefully this combine config can help Tizen/ Lg Webos developer.
