### ISSUE TITLE
DASH fails to start unless scrub bar is clicked

### ISSUE THREAD

**Issue by HankBrown** [videojs/http-streaming#704]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description

DASH video loads forever (or will eventually stop with "Could not download the video").
BUT if you click the scrub bar, the video starts playing.

Happens in Firefox and OSX. Happened in Chrome when video tag was set to auto play.

https://gist.github.com/HankBrown/3e234b586ae646fcb2c9dda7f33aa1f5

https://jsbin.com/vozuboj/edit?html,output

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

All our dash encodings have this issue. We use ffmpeg and bento. More details if/as requested.

## Steps to reproduce

Please see gist above. 

1. Open the gist in Firefox.
2. Click play

If the gist fails for some reason (my first gist) we have a simple test case at https://bh4.brownhanky.com/vjs-stream.html

### Expected

Video should begin playing when the Big Play Button is clicked.

### Error output
Console messages....

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. vjs-stream.html
VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins! video.js:80:49
Specified “type” attribute of “application/dash+xml” is not supported. Load of media resource https://bh4.brownhanky.com/task/90008/dash/stream.mpd failed. vjs-stream.html
All candidate resources failed to load. Media load paused. vjs-stream.html
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. video.js:23832:27
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.

## Additional Information
Please include any additional information necessary here. Including the following:

When we encode using GPAC, we do not get this issue.
However, our goal is DASH+CENC and we cannot get GPAC to produce an encrypted eencoding.
But we doubt the fault is bento. When we play in other test players (JW,bitmoving,ifDASH), no issues with this encoding.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.11.2

### videojs version
what version of videojs does this occur with?
video.js 7.7.3

### Browsers
what browsers are affected? please include browser and version for each

Firefox 71.0
Chrome (when autplay is true)  Version 79.0.3945.88 (Official Build) (64-bit)

### Platforms
what platforms are affected? please include operating system and version or device and version for each

MAC 10.13.6

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.

    "aes-decrypter": "^3.0.0",
    "argparse": "^1.0.10",
    "axios": "^0.19.0",
    "bluebird": "^3.5.4",
    "bulma": "^0.7.4",
    "chown": "^0.1.2",
    "cookie-parser": "^1.4.4",
    "cross-env": "^5.2.0",
    "dashjs": "^2.9.3",
    "express": "^4.17.1",
    "font-awesome": "^4.7.0",
    "hls-server": "^1.5.0",
    "http-attach": "^1.0.0",
    "lodash": "^4.17.15",
    "m3u8-parser": "^4.3.0",
    "mkdirp": "^0.5.1",
    "path": "^0.12.7",
    "requestretry": "^2.0.2",
    "sass-mq": "^5.0.0",
    "tus-node-server": "^0.3.2",
    "url": "^0.11.0",
    "video.js": "7.7.3",
    "videojs-contrib-dash": "^2.11.0",
    "videojs-contrib-eme": "^3.5.0",
    "videojs-errors": "^4.2.0",
    "vue-color": "^2.7.0",
    "vue-i18n": "^7.8.1",
    "vue-multiselect": "^2.1.6",
    "vue-slider-component": "^2.8.16",
    "vue-toasted": "^1.1.26",
    "vue-touch": "^2.0.0-beta.4",
    "vue2-google-maps": "^0.10.6",
    "vuejs-datepicker": "^1.5.4",
    "webpack-visualizer-plugin": "^0.1.11",
    "when": "^3.7.8"

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

vue

**Comment by gkatsev** [comment]
@HankBrown interestingly enough, when loading it locally, your test stream works fine in some cases and fails in other, though, it always fails when loading it on videojs.github.io/http-streaming.

I thought that maybe the work we've been doing in master will fix it but it seems like it doesn't. We'll definitely fix it in master and depending on specifics, we may back port it to the current "1.x" branch but hopefully we'll be ready to release master soon.

**Comment by gkatsev** [comment]
We should also test with the content from #747, for example this test page https://s3.eu-central-1.amazonaws.com/static.kliment.me/vjs-clearkey.html

**Comment by gkatsev** [comment]
Was just able to reproduce the issue in chrome, interesting.

**Comment by gkatsev** [comment]
We're definitely going to look into it as it's a regression.

**Comment by douglasg14b** [comment]
Also experiencing this issue.

Is there a certain version we can target to avoid this?

**Comment by PrestonN** [comment]
Adding a +1 to also having this issue.  Hope to see it fixed soon! :)

> Is there a certain version we can target to avoid this?

Using Video.js version `7.6.6` seems to be the last working version.  That should work for now.

**Comment by gkatsev** [comment]
I can reproduce the original issue in the jsbin though, when playing the stream with a newer version of VHS/Video.js, for example via https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fbh4.brownhanky.com%2Ftask%2F90008%2Fdash%2Fstream.mpd&type=&keysystems= I can no longer reproduce.

**Comment by gkatsev** [comment]
The stream from #704 no longer works for me at all.

**Comment by PrestonN** [comment]
I still experience this issue with my application.  I have to stay downgraded for the time being.  Let me know if you need any more video examples to help debug this.

**Comment by HankBrown** [comment]
> The stream from #704 no longer works for me at all.

Sorry I did not catch your comment (dunno why, I did get the "this issue has been expired" notice).
The page at https://bh4.brownhanky.com/vjs-stream.html has been restored (sorry abut that).
The jsbin link referenced a src on the the vjs site so I can't fix that fast.

I've asked our player developer to update us. I know we continue to experience difficulties in production with dash+cenc+vjs. We did find how to encrypt with GPAC and that has helped, but we still get an unacceptable fail rate.

**Comment by douglasg14b** [comment]
This issue still exists, ca we not with the stalebot cancer?

**Comment by gkatsev** [comment]
So, things are working good on the upcoming version of our playback engine https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fbh4.brownhanky.com%2Ftask%2F90008%2Fdash%2Fstream.mpd&type=&keysystems=
It's been taking a while to release, but we're really close now (last known issue was just merged #952).

**Comment by gkatsev** [comment]
@HankBrown thanks for fixing the source, I think it's fixed in VHS 2.x see previous comment.
