### ISSUE TITLE
Playready not working when overrideNative: false

### ISSUE THREAD

**Issue by ZHAJOR** [videojs/http-streaming#706]
## Description
This ticket is a follow up of [https://github.com/videojs/video.js/issues/6374](https://github.com/videojs/video.js/issues/6374).
I discovered that overrideNative should be set to true to be able to play on Edge/IE11 on Windows 10.

## Sources
```
        player.src({
            src: dash_obj.url,
            type: 'application/dash+xml',
            keySystems: {
                'com.widevine.alpha': {
                    url: wv_license_server_url,
                    licenseHeaders: headers

            },
                'com.microsoft.playready': {
                    url: pr_license_server_url,
                    licenseHeaders: headers
                }
            }
        })
```

## Steps to reproduce

1. Init the player without options and with eme()
2. Try to play a DRM protected video on IE11 or Edge on Windows 10
3. CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED
4. Now add html5.hls = { overrideNative: true }; to the options.
5. It will play.

### Expected
This should play without having to enable overrideNative.

### Error output
CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED

### videojs-http-streaming version
Included by videojs (from notes http-streaming 1.10.6)

### videojs version
7.6.6

### Browsers
Edge 44.18362 + IE11

### Platforms
Windows 10

### Other Plugins
eme

**Comment by gkatsev** [comment]
Oh, just realized that Edge supports DASH playback (not sure whether chromium edge will). So, that's probably why it didn't work there without overrideNative.
Though, that still leaves out IE11.
