### ISSUE TITLE
播放m3u8时，只会播放最后一个ts

### ISSUE THREAD

**Issue by kgdnone** [videojs/http-streaming#712]
videojs-http-streamimg.js文件
第19242行，
if (!this.syncPoint_) {
	        this.syncPoint_ = this.syncController_.getSyncPoint(this.playlist_, this.duration_(), this.currentTimeline_, this.currentTime_());
	      }
this.syncPoint_.segmentIndex没有初始化，导致后面不能和整数判断大小，播放m3u8时，会从播放列表最后一个ts播放， 最后只能播放一个ts。
在下面加一个判断
if (!this.syncPoint_.segmentIndex) {
          this.syncPoint_.segmentIndex = 0;
        }
解决问题

**Comment by gkatsev** [comment]
Can you please provide more information about your scenario? Are you playing back Live HLS? Have a sample or a reduced example we can take a look at? Which version of VHS and Video.js are being used? What browser and OS?
Thanks.

**Comment by kgdnone** [comment]
The video has four ts files. video-js only load the last ts file.
Please check out the attachment for more detail.







At 2020-01-14 03:17:53, "Gary Katsevman" <notifications@github.com> wrote:

Can you please provide more information about your scenario? Are you playing back Live HLS? Have a sample or a reduced example we can take a look at? Which version of VHS and Video.js are being used? What browser and OS?
Thanks.

**Comment by gkatsev** [comment]
I'm not seeing any attachments.
