### ISSUE TITLE
Force to limit fragments in buffer with HLS

### ISSUE THREAD

**Issue by pmendozav** [videojs/http-streaming#715]
## Description
Currently I am using HLS VOD streaming. When I pause the player, fragments continue downloading until the last. Is it possible to force to stop fragments downloading? but not globally (that is, I have another video playing).

My question is because I am using a device with too limited resources and the first buffering time requires more than 10 seconds (I can't to touch the eternal m3u8). A simple solution is keep 2 players but the problem is that the second requires cpu and memory that device does not have. For that, I want to download only first 3 segments of the second and pause it until the first one ends.

**Comment by gkatsev** [comment]
While we don't recommend it, you can tweak the `GOAL_BUFFER_LENGTH` and `MAX_GOAL_BUFFER_LENGTH` values via `videojs.Hls.{{property}}`.
