### ISSUE TITLE
handleManifestRedirects not working in internet explorer 11

### ISSUE THREAD

**Issue by asadmalik3** [videojs/http-streaming#717]
## Description
We have a load balancer server that redirect manifest call to another server. We are setting **handleManifestRedirects** to true in video js options and it is working fine in chrome, all subsequent manifest and chunk calls are sent to new server. Unfortunately it is not working in internet explorer, once manifest file is redirected to new server, all subsequent manifest and chunk calls are being sent to old load balancer URL again.

## Steps to reproduce
1. Configure load balancer and provide URL to Video JS
2. Launch web page in internet explorer
3. See network log, manifest file is redirected by load balancer but all subsequent chunk calls are sent to load balancer URL

## Results
All subsequent chunk calls should be sent to server from where manifest file is loaded.

### videojs version
what version of videojs does this occur with?
video.js 7.6.4

### Browsers
* Internet Explorer 11

### Platforms
* Windows 10

**Comment by asadmalik3** [comment]
I have done some debugging and it seems like responseUrl is not available in internet explorer and Video JS rely on responseUrl to construct new URL. Is there a work-around for this issue?

**Comment by gkatsev** [comment]
Unfortunately, there is no work around. There is no way to handle redirects on IE11. This is one of the reasons why we haven't had this enabled by default. Apparently, when we added it we never documented the limitations with IE11.
