### ISSUE TITLE
FireFox Android HLS stream fails

### ISSUE THREAD

**Issue by sebpatu** [videojs/http-streaming#723]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.

With latest videojs, if i try to play this HLS stream on FireFox android on my samsung S7, i get the error "The media could not be loaded"
My setup works fine for the demo m3u8 "elephants dream"
My stream works fine on other browser like chrome and Samsung browser.
Codec is AVC1, may it be the reason?

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

https://talos-hwe-eventsapp-data.s3-eu-west-1.amazonaws.com/videos/82e01940-59c0-4dec-9bad-7f0a7a4fb018/hls/playlist.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.simply try to load it in videojs

## Results
unsupported media error.

### Expected
should load and play the stream

### Error output
"The media could not be loaded"

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by mister-ben** [comment]
The HLS URL is missing CORS headers. The other browsers can play HLS natively which doesn't need CORS.

**Comment by sebpatu** [comment]
it does not work either on the demo page with previous hls implementation:
https://videojs.github.io/videojs-contrib-hls/

but it works fine on hlsjs demo:
https://hls-js-latest.netlify.com/demo/

and also works fine with bitmovin demo:
https://bitmovin.com/demos/stream-test?format=hls&manifest=https%3A%2F%2Ftalos-hwe-eventsapp-data.s3-eu-west-1.amazonaws.com%2Fvideos%2F82e01940-59c0-4dec-9bad-7f0a7a4fb018%2Fhls%2Fplaylist.m3u8

**Comment by sebpatu** [comment]
For test purpposes i added CORS to the links i mentioned above.
They were not missing cors for my dns.
if you try to access it directly from browser url bar, you could download the m3u8.

what cors auth you would need so i can let you do some tests?

**Comment by gkatsev** [comment]
It looks like audio is ADTS, which is likely going to cause a problem. Also, you may want to force overrideNative on firefox for android, I don't remember whether it reports native HLS support or not.

I do seem to be able to play it locally in firefox on macos, so, sounds like cors isn't an issue anymore.

**Comment by sebpatu** [comment]
> It looks like audio is ADTS, which is likely going to cause a problem. Also, you may want to force overrideNative on firefox for android, I don't remember whether it reports native HLS support or not.
> 
> I do seem to be able to play it locally in firefox on macos, so, sounds like cors isn't an issue anymore.


if it is because of ADTS audio, it is a filter error of videojs for feature detection, because it works fine on bitmovin and hlsjs demo.

or is it videojs that has issues with ADTS?

**Comment by sebpatu** [comment]
i think Firefox android dont has native support, but has MSE support

**Comment by sebpatu** [comment]
the audio codec should be aac

**Comment by gkatsev** [comment]
We've been busy with other things and haven't had the time to get back to this.

**Comment by gkatsev** [comment]
Looks like this is no longer an issue with latest VHS, can you double check?

**Comment by sebpatu** [comment]
I double tested before opening the issue.
i used the latest official release and it happened clearly, i did not try the nightly builds.

Did you test with the video link i provided?

**Comment by gkatsev** [comment]
I tested with the links provided. We've also had several releases since the issue was created.
