### ISSUE TITLE
Degraded performance when switching to full-screen video

### ISSUE THREAD

**Issue by maduggan** [videojs/http-streaming#730]
## Description
When streaming HLS video quality is very degraded when you switch to full-screen for 10-20 seconds. Setting limitRenditionByPlayerDimensions to false doesn't seem to impact performance. Example can be seen here: [jsfiddle](https://jsfiddle.net/L4okeft9/1/)

## Sources
[Example source and sample video](https://jsfiddle.net/L4okeft9/1/)

## Steps to reproduce

1. Start playing the video normally
2. Full screen
3. Watch as degraded video quality continues for a clip until suddenly higher resolution video starts to play

### Expected
Since I'm trying to disable the limit quality by player size setting, I would expect video.js to detect bandwidth speed and then play the highest resolution possible regardless of the currently size of the window, making switching to fullscreen hitless. 

### Error output
None

**Comment by mjneil** [comment]
http-streaming options need to be set nested in an object
```
{
  "html5": {
    "hls": {
      "limitRenditionByPlayerDimensions": false,
      "bandwidth": 10000
    }
  },
  "controls": true
}
```

Be aware using the `limitRenditionByPlayerDimensions` will increase bandwidth usage for viewers with small viewports
