### ISSUE TITLE
Video have small audio: Failed to execute 'appendBuffer' on 'SourceBuffer'

### ISSUE THREAD

**Issue by CuongPhi** [videojs/http-streaming#746]
## Description
When I merge small audio with large video and convert to HLS playlist, this error occur when playing it by videojs/http-streaming. 
When clicking at the time video have no audio, player wait for until all segments have been downloaded, it make player buffers was overflow.
I think this library check audio and video bytes length for download next segments, it make this bug was fire
## Sources
I have private sources
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Preparing: video.mp4 (50mins) + audio.mp3 (5mins)
2. Using ffmpeg merge them, only video from video.mp4 + audio from audio.mp3 -> merged.mp4
3. Using ffmpeg convert merged.mp4 -> HLS playlist (merged.m3u8, merged_01.ts, merged_02.ts, .....)
4. Using videojs7x to play merged.m3u8, it's work but all *.ts segments being downloaded but video does not play until all segments have been downloaded (at the time video merge dont have audio), then error happen: 

> Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers

### Expected
Video playing fine without audio
### Error output
Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers

## Additional Information
Some time I am getting this issue "Uncaught TypeError: Cannot read property 'byteLength' of undefined"

### videojs-http-streaming version
videojs/http-streaming 1.10.6
Included by videojs 7x

### videojs version
Video.js 7.6.5

### Browsers
Chrome 79.0.3945.130

### Platforms
Windows 10

### Other Plugins
videojs/videojs-contrib-quality-levels.js
videojs/videojs-hls-quality-selector.js
### Other JavaScript
Jquery 3.2.1

**Comment by rhyswilliamsza** [comment]
I am experiencing this (well, a similar situation with equal consequence) whilst using VideoJS on a Chromecast as a client.

I believe the bug fix would be to wait on a failure of appendBuffer, thereafter retrying once space has become available.

Alternatively, it seems that some browsers fail to correctly implement clearing of buffers. A bad solution would be to keep track of keyframes in our source, and upon keyframe at time `T`, clear our buffers completely from `(0, T)`. However, this comes with it extra compute and complexity.

I'll update this if I find a better solution :)
