### ISSUE TITLE
DASH fails to start playing in Firefox unless user scrubs a little bit

### ISSUE THREAD

**Issue by klimentLambevski** [videojs/http-streaming#747]
## Description
Briefly describe the issue.
DASH fails to start playing in Firefox, user needs to scrub a little bit to start playing. This happend after http-streaming upgrade from 1.10.5 -> 1.11.x, more specificlly mux.js bump 5.2 -> 5.4

Test page reproducing the issue
https://s3.eu-central-1.amazonaws.com/static.kliment.me/vjs-clearkey.html
Test page with no issue (vjs 7.6.3, http-streaming 1.10.5)
https://s3.eu-central-1.amazonaws.com/static.kliment.me/vjs-clearkey-old.html

## Sources
Test video
https://s3.eu-central-1.amazonaws.com/static.kliment.me/test1/test1.mov
Script to generate DASH
https://s3.eu-central-1.amazonaws.com/static.kliment.me/test1/dash_encoding.sh

## Steps to reproduce

1. Generate DASH with GPAC or Bento4
2. Use latest http-streaming
3. Play the stream in firefox

### Expected
Video  start playing   

### Error output
No errors

### videojs-http-streaming version
videojs-http-streaming 1.11.x

### videojs version
video.js 7.6.6

### Browsers
Mozila Firefox

### Platforms
Mac OSX

### Other Plugins
video-contrib-eme

### Other JavaScript
No

**Comment by HankBrown** [comment]
https://github.com/videojs/http-streaming/issues/704

**Comment by gkatsev** [comment]
Reopning #704 and moving this there as it's like a duplicate.
