### ISSUE TITLE
How to select other playlist selectors?

### ISSUE THREAD

**Issue by EhsanCh** [videojs/http-streaming#749]
How we can choose other selector functions like movingAverageBandwidthSelector  or minRebufferMaxBandwidthSelector  in runtime with videojs or by recompiling vhs?

May you please explain with an example?

**Comment by gkatsev** [comment]
Right now, it isn't an option. We're going to be updating our ABR algorithm in the coming months and may create something to be able to switch these. Unfortunately, right now the best bet is to either re-build VHS or copy and paste the method and override [selectPlaylist](https://github.com/videojs/http-streaming#hlsselectplaylist).
