### ISSUE TITLE
FireFox Android HLS stream fails, "The media could not be loaded"

### ISSUE THREAD

**Issue by sebpatu** [videojs/http-streaming#750]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
With latest videojs, if i try to play this HLS stream on FireFox android on my samsung S7, i get the error "The media could not be loaded"
My setup works fine for the demo m3u8 "elephants dream"
My stream works fine on other browser like chrome and Samsung browser.

## Sources
https://talos-hwe-eventsapp-data.s3-eu-west-1.amazonaws.com/videos/82e01940-59c0-4dec-9bad-7f0a7a4fb018/hls/playlist.m3u8

## Steps to reproduce
1.simply try to load it in videojs

## Results
unsupported media error.

### Expected
should load and play the stream, or at least detect it as not supported format and switch to other source format available.

### Error output
"The media could not be loaded"

## Additional Information
i gave full cors rights, 

it does not work either on the demo page with previous hls implementation:
https://videojs.github.io/videojs-contrib-hls/

it does not work from firefox android on samsung S7, but it all works on desktop firefox

and it works fine on hlsjs demo: (even on firefox android)
https://hls-js-latest.netlify.com/demo/

and also works fine with bitmovin demo: (even on firefox android)
https://bitmovin.com/demos/stream-test?format=hls&manifest=https%3A%2F%2Ftalos-hwe-eventsapp-data.s3-eu-west-1.amazonaws.com%2Fvideos%2F82e01940-59c0-4dec-9bad-7f0a7a4fb018%2Fhls%2Fplaylist.m3u8

so its a videojs error

the audio codec is aac not adts

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
There's no need to open a new issue, the old one is still valid.
