### ISSUE TITLE
setCurrentTime is stuck on loading spin

### ISSUE THREAD

**Issue by sebpatu** [videojs/http-streaming#752]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
When i play a HLS stream and click to seek out of buffered segments, quite often it will stay stuck in loading spin animation. it happens more if the seek is far to the end. If i pause and play, it will unstuck and play properly.
If after that i try to go backand try again, it will not stay stuck anymore like if it was buffered, but it does not appear on play bar like so.
The stream has audio segments separated from video segments with slightly different segment duration, maybe its the cause. it is as if the player was waiting audio segment associated to next video segment.

## Sources
It happens with this stream: (cors cleared)
https://d10sop4yvbk6lz.cloudfront.net/videos/f90bd8ef-78e8-498f-a6ac-1836bca135f7/hls/playlist.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. load stream
2.seek to almost end of video

## Results
it get stuck on loading state
### Expected
load and then play the rest of the video

### Error output
no output

## Additional Information
It also happens with previous version online: 
https://videojs.github.io/videojs-contrib-hls/
but this one stay stuck even after new pause/play when stuck.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
i removed other plugins

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Looks like this is no longer an issue with latest VHS. Can you double check?

**Comment by sebpatu** [comment]
I double tested before opening the issue.
i used the latest official release and it happened clearly, i did not try the nightly builds.
since my video encoder made it possible to merge audio and video chunks, the issue disappeared, meaning that the issue is related to separated audio files.

Did you test with the video link i provided?
