### ISSUE TITLE
Catch event from HLS Usage Events

### ISSUE THREAD

**Issue by davidboutet** [videojs/http-streaming#761]
Im supposed to listen HLS Usage events like so?

defaultPlayer.tech().on("hls-audio-change", function(){
        console.log("audio changed");
    });

I cant find example anywhere and but maybe its a bug and event are not triggered

Thanks

**Comment by gesinger** [comment]
Hey @davidboutet , you can catch usage events using the event type of usage, e.g.,

```javascript
player.on('ready', () => {    
      player.tech_.on('usage', (e) => {
        console.log(e.name);
      });
    });  
```

Hope this helps!
