### ISSUE TITLE
How can i set custom headers for dash and hls

### ISSUE THREAD

**Issue by khavishbhundoo** [videojs/http-streaming#765]
I need to set some headers (laravel_session) in `beforeRequest` any request in videojs(dash & hls) but i see only `player.hls.xhr.beforeRequest` in the docs.

**Comment by douglasg14b** [comment]
What was the resolution here @khavishbhundoo ?

I need to set headers on every request, such as a JWT.

**Comment by sahilkashyap64** [comment]
@khavishbhundoo @douglasg14b  https://docs.microsoft.com/en-us/azure/media-services/latest/how-to-video-js-player

I'm not sure if this would help, but take a look
```
setupTokenForDecrypt (options) {
  if (options.uri.includes('keydeliver')) {
    options.headers = options.headers || {}
    options.headers.Authorization = 'Bearer=' + this.getInputToken()
  }

  return options
}
```


`videojs.Hls.xhr.beforeRequest = setupTokenForDecrypt;`
