### ISSUE TITLE
HLS stream fails on ie11

### ISSUE THREAD

**Issue by sebpatu** [videojs/http-streaming#766]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
I have HLS stream with separated audio that is not playing on ie11. i have another video without audio that is playing ok, but the one with audio is not. it gets stuck after 3 secondes. plus the player fill the audio menu witj two fields even if stream has only one audio stream source.
When i change to mp4 it streams fine.
https://talos-hwe-eventsapp-data.s3-eu-west-1.amazonaws.com/videos/82e01940-59c0-4dec-9bad-7f0a7a4fb018/hls/playlist.m3u8

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
last

### Browsers
ie11
*

### Platforms
windows 10
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Given that I haven't seen issues any more with latest VHS so, can you re-test, please?

**Comment by sebpatu** [comment]
I double tested before opening the issue.
i used the latest official release and it happened clearly, i did not try the nightly builds.
since my video encoder made it possible to merge audio and video chunks, the issue disappeared, meaning that the issue is related to separated audio files.

Did you test with the video link i provided?

**Comment by gkatsev** [comment]
I tested the video provided and I get playback on IE11. I don't get any audio with the above stream on multiple platforms and also VLC.
