### ISSUE TITLE
Cookies not being sent `withCredentials` for dash

### ISSUE THREAD

**Issue by khavishbhundoo** [videojs/http-streaming#767]
## Description
Even when i use `withCredentials` option and set it to true , cookies are not sent by videojs in GET request

Full details : https://stackoverflow.com/questions/60690849/sending-origin-cookies-in-cors-not-working-with-videojs

### videojs version
what version of videojs does this occur with?
video.js 7.6.6

**Comment by gkatsev** [comment]
Not quite sure what's happening, but as a workaround, you can set withCredentials in `beforeRequest` https://github.com/videojs/http-streaming#hlsxhr
