### ISSUE TITLE
IS_SAFARI on IOS device and IS_IOS on desktop

### ISSUE THREAD

**Issue by jnomade** [videojs/http-streaming#768]
## Description
In videojs documentation, 'browser.IS_SAFARI' is described as:
    static, constant IS_SAFARI :Boolean   >>>   Whether or not this is **desktop** Safari.
and 'browser.IS_IOS'
    static, constant IS_IOS :Boolean   >>>    Whether or not this is an iOS device.

However, on my iPhone, IS_SAFARI is true.
On the desktop, IS_IOS is true.

## Steps to reproduce
1.  I simply print the variable on the screen

### Expected
IS_SAFARI should be false on the iPhone (IOS) device.
IS_IOS should be false on the desktop.
Don't have an iPAD to test

## Additional Information
iPhone 6S, IOS 13.3.1
Desktop - MacOs HighSierra 10.3.6, Safari 11.1.2
video-js-7.7.5

**Comment by gkatsev** [comment]
What version of Safari are you seeing IS_IOS set to true? In all my testing I've never seen it.

As for IS_SAFARI, it's likely that it should represent just desktop but unfortunately, the reality is that it just represents a Safari browser. We do have `IS_ANY_SAFARI` which was supposed to be any Safari browser but I think the only real distinction right now is that `IS_ANY_SAFARI` will return true for iOS devices but `IS_SAFARI` might not, particularly inside WebViews.

Unfortunately, I don't think we can fix this easily to strictly limit IS_SAFARI only to desktop cases as it could break users of Video.js who rely on IS_SAFARI's current behavior.

I would recommend checking for mobile first with IS_IPHONE/IS_IOS/IS_IPAD and then checking for IS_SAFARI. Or depending on your needs, just going to `IS_ANY_SAFARI` or combining the two checks.
