### ISSUE TITLE
videojs error with parsed manifest as object

### ISSUE THREAD

**Issue by sampathkumar7** [videojs/http-streaming#773]
videojs not playing when used like in docs
`player.src({
  src: `data:application/vnd.videojs.vhs+json,${JSON.stringify(parser.manifest)}`,
  type: 'application/vnd.videojs.vhs+json'
});`
Giving error
`video.min.js:12 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. `

**Comment by gesinger** [comment]
Hey @sampathkumar7 , would you mind filling out the issue template and including a [reduced test case](https://css-tricks.com/reduced-test-cases/)? we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use. Thanks!

**Comment by sampathkumar7** [comment]
oh got it its working after doing npm build from master branch
But in safari the video doesnt start autoplay

**Comment by gesinger** [comment]
Thanks for the update. Yeah, right now that feature is only available on the master branch.

The video won't play in Safari unless you use https://github.com/videojs/http-streaming#overridenative , but note that `overrideNative` hasn't been tested with that feature. Let us know if you run into any issues.
