### ISSUE TITLE
Seeking and duration display with Shaka Packager DASH Content

### ISSUE THREAD

**Issue by TcT2k** [videojs/http-streaming#789]
## Description
When loading an MPD which was packed by shaka packager the remaining time duration only shows -0:30 and jumps as soon as the next segment (?) is reached. Playback continues but time display and the seek bar is messed up (jumpy).

## Sources
https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load the sample https://videojs.github.io/http-streaming/
2. Playback this MPD https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd (in my experience the same for all shaka packager content)
3. View remaining time and the seek bar

### Expected
Display the remaining time and update the progress bar accordingly. Same content shows correct time in shaka-player demo or on android devices.

With my own content that was packaged as HLS and DASH I've not seen the problem occur when using HLS under Safari (using native HLS as recommened).

### Error output
None

## Additional Information
Please include any additional information necessary here. Including the following:

I see that the `mvhd` atom duration is set to 0 in the content, maybe that is an issue?

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
From sample URL

### videojs version
what version of videojs does this occur with?
video.js 7.6.6 (and latest from sample URL)

### Browsers
what browsers are affected? please include browser and version for each
* Firefox
* Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* macOS
* Windows

### Other Plugins
None

### Other JavaScript
Just the sample

**Comment by gkatsev** [comment]
Thanks for opening the issue, I had just noticed it recently. It's definitely something we want to fix but unfortunately, we're unlikely to get to it in the super short term. We're trying to get our master branch squared away so that we can finally switch to it. On the bright side, the video plays without issues aside from the progress bar not being fully available.
But yeah, I think it's likely because we aren't doing the right thing to calculate the duration from the mpd and we update it as segments are loaded.

**Comment by gkatsev** [comment]
We have a fix for this https://github.com/videojs/http-streaming/pull/794, we'll see if we can do it for 1.x as well.

**Comment by TcT2k** [comment]
I've just tried with the manual built http-streaming from master (including the fix) and it works for me.

Thank you for the quick reply and fix.
