### ISSUE TITLE
Playback with audio only DASH content fails loading

### ISSUE THREAD

**Issue by TcT2k** [videojs/http-streaming#797]
## Description
I've tried playing MPD content that only contains a single audio track.
Loading times out.
I've looked into a fix and came up with the following changes (against 53543184f0b2931d2410008240a6f67bb0358e79 `dist/videojs-http-streaming.js`).
This allowed me to playback audio only content without a problem and still be able to playback normal (video+audio) content.

I works but seems a bit hackish and if I'm not mistaken some lines are changes in [mpd-parser](https://github.com/videojs/mpd-parser).
Before preparing appropriate pull request(s). I would like some feedback on the changes and possible improvements.

## Sources
```diff
4909a4910,4912
>     if (videoPlaylists.length == 0)
>       audioPlaylists = mergeDiscontiguousPlaylists(dashPlaylists.filter(audioOnly)).map(formatVideoPlaylist);
>     var masterPlaylists = (videoPlaylists.length > 0) ? videoPlaylists : audioPlaylists;
4921c4924
<       playlists: addSegmentInfoFromSidx(videoPlaylists, sidxMapping),
---
>       playlists: addSegmentInfoFromSidx(masterPlaylists, sidxMapping),
25144a25148,25149
>     if (tech.videoTracks().length == 0)
>       settings.segmentLoaders.main.setAudio(true);
27385c27390
<     var audioContentType = codecs.audio ? "audio/mp4;codecs=\"" + codecs.audio + "\"" : null; // upsert the content types based on the selected playlist
---
>     var audioContentType = "audio/mp4;codecs=\"" + (codecs.audio ? codecs.audio : codecs.video) + "\""; // upsert the content types based on the selected playlist
27391,27392c27396
<         audioContentType: audioContentType,
<         videoContentType: videoContentType
---
>         audioContentType: audioContentType
27393a27398,27399
>       if (videoPlaylist.length > 0)
>         keySystemContentTypes[keySystem].videoContentType = videoContentType;
```

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load a audio only MPD with DRM.

### Expected
Playback after loading the content

### Error output
Loading times out because the master segment loader doesn't get content.

### Browsers
what browsers are affected? please include browser and version for each
* Chrome, Firefox
* Under Safari I used the corresponding HLS file and native HLS support

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* macOS, Windows

**Comment by gkatsev** [comment]
Unfortunately, we don't support audio-only or video-only DRM streams right now.
However, that is something that we want to support and we'll work on that at some point.
