### ISSUE TITLE
HLS Playback Stops With 'pts' Error

### ISSUE THREAD

**Issue by mikeswanson** [videojs/http-streaming#798]
## Description
When playing back some HLS-encoded media, video.js shows a buffering spinner and will not continue playback. The underlying problem has been fixed in recent versions of the mux.js library.

## Sources
The issue can be seen in this single variant HLS stream around the 34-second mark: https://app.voodle.dev/assets/2ba91016-4810-4de8-884d-ab1990709fe4/playlist.m3u8

## Steps to reproduce
Here is a simple page that uses video.js to playback a problematic HLS stream. The problem happens around 34 seconds into the video: https://app.voodle.dev/assets/2ba91016-4810-4de8-884d-ab1990709fe4/index.html

### Expected
I expect the video to continue playback. A version with the latest mux.js does not have this issue.

### Error output
```
Uncaught TypeError: Cannot read property 'pts' of undefined
    at findSeiNals (video.js:35979)
    at video.js:36084
    at Array.forEach (<anonymous>)
    at parseCaptionNals (video.js:36068)
    at parseEmbeddedCaptions (video.js:36120)
    at CaptionParser.parse (video.js:36222)
    at video.js:49019
    at Object.callback (video.js:39502)
    at cbOnce (video.js:8532)
    at XMLHttpRequest.loadFunc (video.js:8606)
```

## Additional Information
This issue has been fixed in later versions of mux.js. Specifically: https://github.com/videojs/mux.js/blob/48bfe005139aac25618453e9b3f5203f3895b1a5/lib/mp4/caption-parser.js#L88-L101

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.13.2

### videojs version
what version of videojs does this occur with?
video.js 7.6.6

### Browsers
At least Chrome 80.0.3987.163
### Platforms
what platforms are affected? please include operating system and version or device and version for each
* At least macOS Catalina (10.15.4)

### Other Plugins
None

### Other JavaScript
None

**Comment by gkatsev** [comment]
Looks like this should be fixed in master but we'll also make sure to update mux.js in the 1.x branch and get a release out soon.

**Comment by jessica-pixvana** [comment]
@gkatsev how do i track when this fix makes it into master of video.js?

**Comment by gkatsev** [comment]
1.13.3 was just released with this change, you can include it manually, otherwise, you can wait till next release of Video.js.
