### ISSUE TITLE
[question] prevent prefetch hls playlist on page load

### ISSUE THREAD

**Issue by kinoher** [videojs/http-streaming#813]
# Description
I have server side video transcoder . video transcoding will starting when request hls playlist. On my page 5 instances videojs and browser trigger start 5 encoding process when page loaded in sametime, it's very bad and generate overload.
how to load playlist after click play button?
## Sources
[gist](https://gist.github.com/kinoher/26762ad3b906ab1f701abe3b4fe07fa8)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 7.6.6(videojs from cdn)

### videojs version
what version of videojs does this occur with?
video.js 7.6.6 (cdn)

### Platforms/browsers
what platforms are affected? please include operating system and version or device and version for each
* linux/firefox 75.0
* android/firefox 68
* windows/chrome 80.0.3987

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Unfortunately, that is a bug that we need to address. For now, the workaround would be to not set the source on the player until a play request is made.

**Comment by kinoher** [comment]
thanks for your reply.
Please provide detail explain or example for this solution, i'm noob in javascript.

**Comment by gkatsev** [comment]
We've since addressed this issue https://github.com/videojs/http-streaming/pull/1060
