### ISSUE TITLE
Refrence error P is not defined 

### ISSUE THREAD

**Issue by saurabhkhandelwal** [videojs/http-streaming#819]
[
<img width="1092" alt="Screenshot 2020-03-24 at 3 20 44 PM" src="https://user-images.githubusercontent.com/11537601/79383032-1f8c8400-7f82-11ea-818f-af62ce89df0a.png">
](url)

![](https://files.slack.com/files-pri/T04R1GUPQ-F01091PCSLS/screenshot_2020-03-24_at_3.24.45_pm.png)

**Comment by saurabhkhandelwal** [comment]
<img width="791" alt="Screenshot 2020-03-24 at 3 24 45 PM (1)" src="https://user-images.githubusercontent.com/11537601/79383159-5bbfe480-7f82-11ea-8073-469a85b5c233.png">

**Comment by deltafactory** [comment]
Are you able to recreate the error using the unminified version of video.js? That stack trace would be a lot easier to troubleshoot.

**Comment by saurabhkhandelwal** [comment]
hi @deltafactory sorry for the late response 
I am actually using videojs version 6.7 and have included the Http streaming library explicitly.
Can you tell me how to enable dev mode for http streaming, so that I get a proper stack trace.

**Comment by deltafactory** [comment]
If you're using CDN urls then most likely removing `.min` will work.

For example:
http://vjs.zencdn.net/5.4.6/video.min.js becomes
http://vjs.zencdn.net/5.4.6/video.js

https://unpkg.com/browse/@videojs/http-streaming@1.13.3/dist/videojs-http-streaming.min.js becomes
https://unpkg.com/browse/@videojs/http-streaming@1.13.3/dist/videojs-http-streaming.js

**Comment by gkatsev** [comment]
A live reduced test case is really important for us to be able to help debug and fix the issue.
In addition, try your stream with https://videojs-http-streaming.netlify.app/, which will be an upcoming version of VHS which includes fixes.
