### ISSUE TITLE
What are the differences to videojs-contrib-hls?

### ISSUE THREAD

**Issue by wowcut** [videojs/http-streaming#82]
Hi, I seriously appreciate your work and I am totally overwhelmed that there are now two hls projects in the videojs org, but it also would be really great if you would like to explain (maybe in a blog post) the reasoning behind those two repos - why does this repo exist and how does it relate to [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls)?

As a casual user I find the current situation very confusing. Which codebase to follow?

Thank you very much!

**Comment by forbesjo** [comment]
We're currently working on a blog post and will update the videojs-contrib-hls README to link to here. Basically this project is the next version of videojs-contrib-hls but with experimental DASH support. We decided to rename the project and reset the version to reflect that is plugin is not just for HLS.

**Comment by forbesjo** [comment]
The blog post and READMEs have been updated, closing this
