### ISSUE TITLE
How use only a url without a .m3u8 file

### ISSUE THREAD

**Issue by HKTIBIA** [videojs/http-streaming#821]
Hey how a use only a url to stream IPTV channels without .m3u8 file finishing, as:

http://domain.com:80/xxxxx/xxx/xxxxx > this url release a .m3u8 file but i cannot use then in your live example html **https://jsbin.com/gejugat/edit?html,output**

can u help me ?

__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Is the stream the raw h264 data? If so, unfortunately, we don't support it. Your best bet is to use something like nginx-rtmp or ffmpeg to convert the iptv output into an HLS or DASH stream.
Alternatively, it is possible to create a video.js plugin that can accept raw h264 stream and input it into MSE.

**Comment by HKTIBIA** [comment]
but can u explain how a link like http://canais.servidor.tv:8080/1mxh0u/o64ceo/1521 works on vlc and jwplayer and doesn't work on videojs. Only link with .m3u8 works. can u help me ?

**Comment by gkatsev** [comment]
VLC specifically makes sure that it can play just about everything. I'm not sure what JWPlayer is doing to make it work. It's definitely something that is possible to get working but unfortunately, we don't have the bandwidth to implement it and it isn't really within the scope of VHS itself. We're built around getting m3u8 or mpd playback work.

**Comment by gesinger** [comment]
Hey @HKTIBIA , VHS supports multiple different types, e.g., application/x-mpegURL (normally seen as a .m3u8 extension,) and application/dash+xml (normally seen as a .mpd extension). It doesn't check the extension of the URL itself, so if the URL is delivering those manifests, and the type is set appropriately, it should work. If it's delivering a different format, then it will not be able to play back.

If you are delivering one of those types, and it's just the URL that's different, we'd be happy to look into the issue, but will need working a source to debug. If so, please feel free to reopen and include the sample! Thank you.

**Comment by Goran7777** [comment]
3 years passed and nothing new in this field,we can put on the web only streams with .m3u8 and .mpd.Nothing new on the horisont.Sadly.

**Comment by Nika2212** [comment]
If I understand your question correctly, you have the same issue that I had. My API endpoint, which returns an m3u8 source, looks like https://example.com/source/:id without the .m3u8 extension in the URL. My solution was to modify the Video.js source file where it checks the URL format, getFileExtension method)

VideoJS version 7.2.3

**Comment by mister-ben** [comment]
If it's HLS without an m3u8 extension, the type should be specified when loading the source.

```js
player.src({
  src: 'https://example.com/source/:id',
  type: 'application/x-mpegURL'
});
```
