### ISSUE TITLE
No Sound When Playing HLS Video

### ISSUE THREAD

**Issue by lawchihon** [videojs/http-streaming#834]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
When I tried to play m3u8 file, there are no sound when playing.
https://codepen.io/lawchihon/pen/vYNeyKd

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.
https://cdn-1.okp2pweb.com/hls/2020/04/25/EbLWBf50/playlist.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load the video through videojs
2. Play the video

### Expected
Please describe what you expected to happen that did not happen in the description.
Video playing with sound

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.13.3

### videojs version
what version of videojs does this occur with?
video.js 7.7.5

### Browsers
what browsers are affected? please include browser and version for each
* Chrome v81.0.4044.113

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* MacOS

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* None

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* None

**Comment by gkatsev** [comment]
Unfortunately, we don't currently support mp3 audio. We recommend delivering audio via aac.

**Comment by lawchihon** [comment]
@gkatsev is there any plan for supporting that?

**Comment by gkatsev** [comment]
We'd like to support it but it isn't something that we have planned any time soon due to limited bandwidth on our end.
