### ISSUE TITLE
On IE11, Safari, multitrack audio icon is displayed for Single audio Dash streams

### ISSUE THREAD

**Issue by ssanth** [videojs/http-streaming#835]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Single audio Dash stream shows multiple audio tracks on IE11, Safari

Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

reduced repro:
https://tridentatearcticwolf.htmlpasta.com

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. create dash media with single audio track
2. load the url in ie11 or safari 

## Results
-shows multitrack icon on the control bar
-on safari sometimes i dont hear audio

### Expected
Please describe what you expected to happen that did not happen in the description.
no multitrack icon on the control bar

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:
noticed on the browsers that support nativetracks this issue shows up
player.tech_.featuresNativeAudioTracks is true
and also the track is not loaded ( meaning no loaded_ flag)

following code gets called for adding tracks:
https://github.com/videojs/video.js/blob/dbd5203a0be2ac58faec948b1934f86063dc3b6f/src/js/tech/html5.js#L299
https://github.com/videojs/http-streaming/blob/master/src/media-groups.js#L772

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
noticed on video.js 7.6.6
but repros on latest

### Browsers
what browsers are affected? please include browser and version for each
* ie11
* safari on desktop

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* mac
* windows 10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Interesting, we'd have to investigate a bit more why things aren't working. I noticed that I'm not getting any audio playback but I do get some video playback. I also noticed that the manifest is currently using `$Time$` for the template urls. Unfortunately, we do not currently support that in DASH manifests https://github.com/videojs/http-streaming#dash-assets-with-time-interpolation-and-segmenttimelines-with-no-t
