### ISSUE TITLE
using web worker

### ISSUE THREAD

**Issue by sampathkumar7** [videojs/http-streaming#837]
I have 6 players playing in single page which is breaking page after sometime.

is there any option i can use webworker to have each player in each worker. So it can increase performance

**Comment by gkatsev** [comment]
Unfortunately, the answer is not really. Right now, we have to interact with media source extensions and that requires DOM interaction and isn't allowed in web workers. We do offload work to web workers when we can, for example for transmuxing and for decrypting. Ultimately, even if we did offload most of the processing to web workers, you may still potentially not be able to play more videos.
Are you seeing any errors on the page when you try to play multiple players?

**Comment by sampathkumar7** [comment]
actually no errors but latency is 30 seconds. Is there any option to reduce 30sec latency.
