### ISSUE TITLE
HLS MPEG-1 Audio Layer 2 / mp2

### ISSUE THREAD

**Issue by impleotv** [videojs/http-streaming#838]
Hi there,

Is MPEG-1 Audio Layer 2 audio supported? AAC audio seems to be Ok, but I can't get mpeg audio working...
This is something that used to work for me in the past - videojs (with videojs-contrib-hls).
How to get it working with videojs/http-streaming ?

Thanks,

Alex

**Comment by gkatsev** [comment]
Have a sample? I wouldn't expect it to work in contrib-hls but if it did I'd expect it to work here.
Also, can you give it a try on https://videojs-http-streaming.netlify.app/? It's a big update that we have pending.

**Comment by impleotv** [comment]
Hi Gary,

Thanks for your reply.
Here is the link to a sample:

[https://impleo-video.s3-eu-west-1.amazonaws.com/hls-audio/3M_AUDIO_Ruhama1/EO-IR-3M_AUDIO_Ruhama1.m3u8](https://impleo-video.s3-eu-west-1.amazonaws.com/hls-audio/3M_AUDIO_Ruhama1/EO-IR-3M_AUDIO_Ruhama1.m3u8)

or with a master playlist (video/audio + drone telemetry):
[https://impleo-video.s3-eu-west-1.amazonaws.com/hls-audio/Master-Ruhama-EO-IR.m3u8](https://impleo-video.s3-eu-west-1.amazonaws.com/hls-audio/Master-Ruhama-EO-IR.m3u8)

I can see the video using the link you've provided, but audio is still missing. 
It works fine with Vlc and some other players.

Thanks for your help,

Alex

**Comment by gkatsev** [comment]
I tried your sample in our contrib-hls sample page but couldn't get audio working there either. The HLS spec specifically calls out only AAC, mp3, ac-3 or e-ac-3 as valid audio. Currently, we only support AAC but hope to support others eventually.
Our recommendation would be to switch to AAC audio.

**Comment by impleotv** [comment]
Hi Gary,

Ok. Will switch to AAC.

Thanks,

Alex
