### ISSUE TITLE
Dash playlist loader is breaking the `dispose` API

### ISSUE THREAD

**Issue by Keytwo** [videojs/http-streaming#845]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Create a new video with Dash source type
2. Start the streaming
3. Dispose the player

### Expected
The video runtime gracefully dispose and clears all timeouts

### Error output
After the `dispose` call you get multiple stacktraces:

```
video.cjs.js:99 VIDEOJS: ERROR: TypeError: Cannot read property 'buffered' of null
    at Html5.<computed> [as buffered] (video.cjs.js:20462)
    at MasterPlaylistController.updateDuration (video.cjs.js:43251)
    at DashPlaylistLoader.<anonymous> (video.cjs.js:42474)
    at DashPlaylistLoader.data.dispatcher (video.cjs.js:1902)
    at trigger (video.cjs.js:2038)
    at DashPlaylistLoader.EventTarget.trigger (video.cjs.js:2440)
    at DashPlaylistLoader.refreshMedia_ (video.cjs.js:37115)
    at DashPlaylistLoader.<anonymous> (video.cjs.js:36541)
    at DashPlaylistLoader.data.dispatcher (video.cjs.js:1902)
    at trigger (video.cjs.js:2038)
```

## Additional Information
When this event is triggered, 
https://github.com/videojs/http-streaming/blob/master/src/dash-playlist-loader.js#L269

the timeout is renewed again and again
https://github.com/videojs/http-streaming/blob/master/src/dash-playlist-loader.js#L818

Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
@videojs/http-streaming@1.12.2

### videojs version
what version of videojs does this occur with?
video.js 7.7.5

### Browsers
what browsers are affected? please include browser and version for each
Chrome: Version 81.0.4044.138 (Official Build) (64-bit)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Mac Os

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by NujiaLin** [comment]
why did you close this issue?
i have the same problem and is looking for a solution

**Comment by gkatsev** [comment]
Unfortunately, I'm unable to reproduce. @NujiaLin can you create some kind of reduced test case that shows off the issue reliably? Thanks.

**Comment by dieterwalckiers** [comment]
I just ran into the same error.
It seems to originate in the ABR code.
There's an interval in there that calls `checkABR_` every 250 milliseconds:
```
    this.abrTimer_ = window.setInterval(function () {
      return _this2.checkABR_();
    }, 250);
```
My guess is that this timer isn't cancelled when the video is disposed.

Our quick and dirty fix is to delay the disposal of the player with 500ms:
`setTimeout(() => player.current.dispose(), 500);`

Hope this helps.

**Comment by zemlanin** [comment]
Alternative fix: pause the player, wait until it is paused, and _then_ dispose of it

```js
const dispose = () => {
  if (playerRef.current) {
    playerRef.current.dispose();
    playerRef.current = undefined;
  }
};

if (!playerRef.current.paused()) {
  playerRef.current.one('pause', dispose);
  playerRef.current.pause();
} else {
  dispose();
}
```
