### ISSUE TITLE
Trying to never play specific bandwidth option in m3u8 file

### ISSUE THREAD

**Issue by benlivermore-intellify** [videojs/http-streaming#846]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
We are seeing a behavior with our videos playing the low bandwidth audio-only track from our m3u8 file even when bandwidth seems enough to play the video tracks.  We have followed the advice to avoid getting stuck in low bandwidth from initial load but the audio-only track still plays after it seems to attempt to use the initial bandwidth.  We don't have a quick way to update the master playlist in m3u8 to not have the audio-only tracks so wondering if there is a way to prevent the choice of the audio-only track in all cases from within the client settings since we don't need really want that behavior anyway.  

Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

## Sources
Don't have a publicly accessible example of this as our videos need authentication to access.
Here is a sample m3u8
```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-0",NAME="Default",AUTOSELECT=YES,DEFAULT=YES,URI="OURURI"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="Default",AUTOSELECT=YES,DEFAULT=YES,URI="OURURI"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=19787000,CODECS="avc1.4d001f",URI="OURURI"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=16722000,CODECS="avc1.4d001f",URI="OURURI"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=11854000,CODECS="avc1.4d001e",URI="OURURI"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5093000,CODECS="avc1.42001e",URI="OURURI"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3605000,CODECS="avc1.42001e",URI="OURURI"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2536000,RESOLUTION=640x480,CODECS="avc1.4d001f,mp4a.40.2",AUDIO="audio-1"
https://ourdomain.com/api/hls-proxy/hls.m3u8?playlistUrl=url
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1921000,RESOLUTION=640x480,CODECS="avc1.4d001f,mp4a.40.2",AUDIO="audio-1"
https://ourdomain.com/api/hls-proxy/hls.m3u8?playlistUrl=url
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1334000,RESOLUTION=576x432,CODECS="avc1.4d001e,mp4a.40.2",AUDIO="audio-1"
https://ourdomain.com/api/hls-proxy/hls.m3u8?playlistUrl=url
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=857000,RESOLUTION=426x320,CODECS="avc1.42001e,mp4a.40.2",AUDIO="audio-1"
https://ourdomain.com/api/hls-proxy/hls.m3u8?playlistUrl=url
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=490000,RESOLUTION=384x288,CODECS="avc1.42001e,mp4a.40.5",AUDIO="audio-0"
https://ourdomain.com/api/hls-proxy/hls.m3u8?playlistUrl=url
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=588000,RESOLUTION=384x288,CODECS="avc1.42001e,mp4a.40.2",AUDIO="audio-1"
https://ourdomain.com/api/hls-proxy/hls.m3u8?playlistUrl=url
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=97000,CODECS="mp4a.40.5",AUDIO="audio-0"
https://ourdomain.com/api/hls-proxy/hls.m3u8?playlistUrl=url
```
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Restrict bandwidth either by a proxy like Charles or via Chrome network tab throttling to something like 3G bandwidth
2. Launch one of our hls streaming videos with videojs (used latest Chrome)
3. On load, immediately play the video via the UI or autoplay setting.

## Results
After some loading, audio-only track plays despite seemingly enough bandwidth to run the low res videos.  We do see briefly a call to use higher res video but we never see this video play and then requests to the audio-only track commence.

### Expected
We'd expect to see low res video to play.  Because we don't really want audo-only to ever play, we wanted to be able to prevent it from being chosen from the playlist via the http-streaming api.

### Error output
No errors.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
* Mac Chrome 81.0.4044.129
* Windows Chrome
*  (maybe others)

**Comment by gkatsev** [comment]
Try setting [`enableLowInitialPlaylist`](https://github.com/videojs/http-streaming#enablelowinitialplaylist) which starts at the lowest video+audio rendition. Alternatively, and may be more of what you're looking for, you can set the [`bandwidth`](https://github.com/videojs/http-streaming#bandwidth) option to tell VHS where to start.
