### ISSUE TITLE
Playback HLS 

### ISSUE THREAD

**Issue by akhilleusuggo** [videojs/http-streaming#847]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description

I'm newbie . **My question is straightforward** . Where can I change the value that indicates how much data need the player to download before starts playback ?
I'm using HLS , `EXTINF:6.000000` . Anyway to make the playback start right after downloading the first segment ?

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
No errors , just taking longer to load .

### videojs-http-streaming version
videojs-http-streaming 1.11.2

### videojs version
Video.js 7.7.4

### Browsers
Google Chrome 83

### Platforms
Ubuntu Server 18.04 TLS ( video hosted )
Playback Video Windows 10

### Other JavaScript

**Comment by gkatsev** [comment]
We do not have an option for this. We rely on the browser for the actual playback, and we will continue providing it video data until it plays. Though, with six second segments, it should start playback when we append that segment to the source buffer.

**Comment by akhilleusuggo** [comment]
So how can I improve the load ?
On mp4 videos , using the `-movflags +faststart ` while encoding ffmpeg does help , and start very fast. But when it comes to HLS takes really long .

I just want to insight that could help improving the speed load / buffer . 
I appreciate it . Greetings
