### ISSUE TITLE
Detect empty HLS playlist during live playback

### ISSUE THREAD

**Issue by popler** [videojs/http-streaming#852]
Videojs 7.6/7.8.1

Hi I have problem with live streaming and empty playlist. When stream is not more available the playlist still can be download, but it is empty. The ended event is not fired and player still loading empty chunks.m3u8 files.
Is there any event on which I can check if playlist contains at least one level?

**Comment by gkatsev** [comment]
Unfortunately, this isn't something that we're going to be looking into right now and it isn't something we currently support. Your media backend is producing invalid HLS when the stream ends per the HLS specification:
>    The server MUST NOT remove a Media Segment from a Playlist file
>   without an EXT-X-ENDLIST tag if that would produce a Playlist whose
>   duration is less than three times the target duration.  Doing so can
>   trigger playback stalls.

https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-6.2.2
