### ISSUE TITLE
Unable to get HLS manifest with fmp4s to play

### ISSUE THREAD

**Issue by rkalpakova** [videojs/http-streaming#866]
## Description
When trying to play HLS manifest containing fmp4s, only the first couple of seconds play. The player then shows 

> The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

Here is an example: https://jsbin.com/fopekap/edit?html,output

It is reproducible on Chrome and Safari after overriding native behaviour. Same manifest plays fine with https://hls-js-latest.netlify.app/demo/ 

## Sources
Here is link to the manifest: https://dwt8x9rms639l.cloudfront.net/d/hZfhOGxvXFxwqQIEXL3io.1202.m3u8

### Expected
Please describe what you expected to happen that did not happen in the description.

### Error output
After a few seconds player shows this:
> The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

Console shows this: 

> VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs version
7.3.0

### Browsers
I have tested on Chrome and Safari

### Platforms
I use a mac 

### Other Plugins
No, I tried in incognito mode. 

### Other JavaScript
No

**Comment by gkatsev** [comment]
Confirmed that this is still an issue with VHS 2, we'll try and take a look at this soon.

**Comment by gkatsev** [comment]
Seems to be working fine in latest changes in `main` now.

**Comment by gkatsev** [comment]
Confirmed. I am able to play this video back using latest Video.js (7.10 and newer) which includes VHs 2.x and newer.
