### ISSUE TITLE
Adaptive quality/resolution on resize

### ISSUE THREAD

**Issue by dannyuk1982** [videojs/http-streaming#868]
Apologies if this has been covered, I've been searching for a while and can't see anything though.

## Description
I have a video as a hero background, so it can be anything from ~300px wide up to 1400px depending on the viewport size. 

I am using a HLS video stream from Vimeo.

### How I expect this to work
On Safari (with native HLS support) if the window initially loads with a small viewport (say 400px)  a lower resolution version of the video is played, if the window is resized to 1400px, after a couple of seconds high resolution version of the video is switched to. 

### What is happening
On Chrome (which is using videojs/VHS as a polyfill) this doesn't happen, so if the window initially loads with a small viewport (say 400px) a lower resolution version of the video is played, if the window is resized to 1400px the same lower resolution version continues to play. After a refresh the correct higher resolution is loaded.

Although the same happens in reverse (starting with a large viewport and resizing to make it smaller), this isn't a problem as the video remains crisp.

Is there a workaround for this, or some options I have missed?

**Comment by gkatsev** [comment]
Unfortunately, we do not currently try to change rendition on a player resize. This may be a reasonable thing to do, though.
A workaround would probably be something like listening to `playerresize` and then disabling the current rendition (via https://github.com/videojs/videojs-contrib-quality-levels for example) which will cause the player to switch renditions (or even manually select another rendition).
We will eventually upswitch, but we only use segment downloads as an adaptation opportunity.
