### ISSUE TITLE
[Question] Is there a way to obtain the timestamp of the current HLS fragment being played?

### ISSUE THREAD

**Issue by suggestedfixes** [videojs/http-streaming#870]
I understand that this is a duplicate of this issue
https://github.com/videojs/video.js/issues/6706

I think posting this on this repo will get more visibility.
I understand that we can get it from text track by using this method.
https://github.com/videojs/http-streaming#segment-metadata

However, I think the update speed is a bit slow, is there a faster method?

**Comment by rhyswilliamsza** [comment]
Yeah, you should definitely be able to do so via the Segment Metadata event :)

https://github.com/videojs/http-streaming#segment-metadata

**Comment by suggestedfixes** [comment]
@rhyswilliamsza Thanks for the quick response! Is there a method to override the video player behavior to update the cue more frequently? I might have been wrong, I think the last time I checked, the 'cuechange' event does not fire very frequently at first, then it gradually gets up to speed.

**Comment by rhyswilliamsza** [comment]
You could run your own timer and poll the TextTrack instead of waiting for an event :) It should allow you to grab info sooner?

**Comment by gkatsev** [comment]
For better and worse, we trigger cuechange based on timeupdate, but it should generally be good enough for most usecases.
What are you trying to do with the segment metadata?

**Comment by suggestedfixes** [comment]
I'm extracting timestamps from m3u8 playlist, and trying to map the current segment being played to one of the timestamps in the playlist. Here is a sample of the playlist
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:407
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-DISCONTINUITY
#EXT-X-MAP:URI="url"
#EXT-X-PROGRAM-DATE-TIME:2020-06-24T18:27:18.735Z
#EXTINF:1.001,
#EXT-X-MAP:URI="url"
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2020-06-24T18:27:19.736Z
#EXTINF:1.0,
------------ more lines -----------
```

**Comment by suggestedfixes** [comment]
Here is a list of timestamps I'm getting registering events on loadedmetadata using https://github.com/videojs/http-streaming#segment-metadata, it will be nice if there is a way to update once per second.

```
Wed Jun 24 2020 13:10:27 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:29 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:32 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:33 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:34 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:37 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:38 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:39 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:40 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:41 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:42 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:46 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:47 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:56 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:57 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:10:58 GMT-0700 (Pacific Daylight Time)
video.es.js:4750 [Violation] 'requestAnimationFrame' handler took 54ms
videoPlayer.js:121 Wed Jun 24 2020 13:10:59 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:11:00 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:11:01 GMT-0700 (Pacific Daylight Time)
videoPlayer.js:121 Wed Jun 24 2020 13:11:03 GMT-0700 (Pacific Daylight Time)
```

**Comment by suggestedfixes** [comment]
I think I figured out why there are missing segments. Some of the segments don't have a start or end attribute.

**Comment by suggestedfixes** [comment]
I think this is the check for start and end attributes happening.
https://github.com/videojs/http-streaming/blob/main/src/segment-loader.js#L2647
Inspecting individual segment from the master playlist, some has start & end, but some of those don't, when do they get parsed and computed?

**Comment by gkatsev** [comment]
When a segment is downloaded, it first goes through https://github.com/videojs/http-streaming/blob/c80793075c1d5d00cf5f16bbe9bb0ea608e11826/src/segment-loader.js#L2158-L2164.
Actual parsing of segments is likely in the mux.js project.

**Comment by suggestedfixes** [comment]
I wrote a custom text track instead after capturing 'progress' event. Are segments appended to cue in increasing timestamp order? Or can they be loaded slightly out of order?

**Comment by gkatsev** [comment]
They should show up in increasing timestamp order.

**Comment by suggestedfixes** [comment]
Thanks! I think this can be resolved and closed.

**Comment by robinmonjo** [comment]
Hello, I also need something similar, i.e: I need to know at a given time what is the absolute time of a HLS stream, and not the relative time (relative to when I opened the player).

For example

- stream starts at 14:00 (the server starts broadcasting)
- user 1 open videojs at 14:00 => absolute time = 0
- user 2 open videojs at 14:07 => absolute time = 7

I have a snippet that kinds of work but I'm not sure if it's the best way to do it or even if it will work reliably in every contexts 😊:

```javascript
const vhs = player.tech().vhs;
const segments = vhs.playlists.media().segments;
const lastSegment = segments[segments.length - 1];

if (lastSegment && lastSegment.videoTimingInfo) {
  console.log("absolute time is :", lastSegment.videoTimingInfo.baseMediaDecodeTime);
}
```

Any feedback on this would be amazing
