### ISSUE TITLE
[Question] How to get parsed playlist manifest object

### ISSUE THREAD

**Issue by fawaztahir** [videojs/http-streaming#879]
How can get I get a parsed playlist manifest object? I'm trying to implement FairPlay with EME and few portions of the license url is found in playlist manifest. EME does have an option to provide a custom function for fetching license.

Checking the Network Tab, requests are sent in following order:

1. Master Playlist
2. Bitrate Playlist(Contains License Information)
3. License Request

Is it possible to get Bitrate Playlist Object within the Custom License Request.

**Comment by gkatsev** [comment]
You can try getting it via `player.tech().hls.playlists.master`, though, by that time it's likely too late to initialize eme for that source, so, you may need to re-set the source again.
