### ISSUE TITLE
Audio delayed for hls v7 with cmaf

### ISSUE THREAD

**Issue by chrisrng** [videojs/http-streaming#882]
## Description
Theres a significant audio delay when testing out an HLS v7 with cmaf on https://videojs.github.io/http-streaming/

However when we tested out this out [under the videojs-http-streaming.netlify.app](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fstreameus2-livectorprodmedia15-use2.licdn.com%2F94c850bd-bbd9-4f85-a147-9c95b241e726%2FL4E5cb368537c414000-livemanifest.ism%2Fmanifest(format%3Dm3u8-cmaf)&type=application%2Fx-mpegurl&keysystems=) there is no audio delay

## Sources
Video: https://streameus2-livectorprodmedia15-use2.licdn.com/94c850bd-bbd9-4f85-a147-9c95b241e726/L4E5cb368537c414000-livemanifest.ism/manifest(format=m3u8-cmaf)

## Steps to reproduce

Reproducable here:

1. Navigate to https://videojs.github.io/http-streaming/
2. Add `https://streameus2-livectorprodmedia15-use2.licdn.com/94c850bd-bbd9-4f85-a147-9c95b241e726/L4E5cb368537c414000-livemanifest.ism/manifest(format=m3u8-cmaf)` to source
3. Play and listen for audio delay

However not reproducable here –

1. Navigate to https://videojs-http-streaming.netlify.app/
2. Add `https://streameus2-livectorprodmedia15-use2.licdn.com/94c850bd-bbd9-4f85-a147-9c95b241e726/L4E5cb368537c414000-livemanifest.ism/manifest(format=m3u8-cmaf)` to source
3. Play and there is no audio delay

### Expected
No audio delay

### videojs-http-streaming version
videojs-http-streaming v1.13.3

### videojs version
video.js 7.8.3

### Browsers
* Chrome 83.0.4103.116 reproducable
* Safari Version 13.1.1 not affected

**Comment by gkatsev** [comment]
VHS 2.0 is out as pre-release. We hope to get it fully released this week

**Comment by chrisrng** [comment]
Thanks! Seems like its resolved in VHS 2.0 :)

**Comment by gkatsev** [comment]
Cool, VHS 2.1 is coming to Video.js *soon*.
