### ISSUE TITLE
[question] Can I use http-streaming without videojs?

### ISSUE THREAD

**Issue by interlark** [videojs/http-streaming#885]
Can I use http-streaming without videojs?
Something like:
```html
<script src="videojs-http-streaming.min.js"></script>
<video>
  <source
     src="https://example.com/index.m3u8"
     type="application/x-mpegURL">
</video>
```

**Comment by gkatsev** [comment]
Unfortunately, not really. When we switched from `videojs-contrib-hls` to videojs http-streaming (VHS), we thought about it but decided that there's more benefit from being tied to Video.js.
At some point, we plan to make Video.js a bit more modular so you can use pieces of it without necessarily needing all of it but unfortunately we don't have a timeline for it.
If you can't use Video.js and want to use a project directly with a video element, I would suggest trying out hls.js or shaka player. Is there a particular reason you want a standalone VHS?

**Comment by interlark** [comment]
I use my own player and thought about http streaming support. And found this repo by

> This project addresses that situation by providing a polyfill for HLS
> on browsers that have support for [Media Source
> Extensions](http://caniuse.com/#feat=mediasource).
> You can deploy a single HLS stream, code against the
> regular HTML5 video APIs, and create a fast, high-quality video
> experience across all the big web device categories.

Hls.js is good one, but it has troubles with multi-buffer gaps and holes during playback, Shaka Player is interesting one too, but it got strange behavior with streaming captions.
