### ISSUE TITLE
Playback Vimeo stops after 6s

### ISSUE THREAD

**Issue by MusicPartner** [videojs/http-streaming#887]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.

https://jsbin.com/golehavefa/1/edit?html,output

## Sources
Is a certain source or a certain segment affected? please provide a public (accesible over the internet) link to it below.
Any video from Vimeo
https://player.vimeo.com/external/386726140.m3u8?s=450453ba93a66c95b82c68966e2f82b9e44b3418

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play a Vimeo HLS video
2. After 6s it stops playing (works in other players)

### Expected
It should continue playing

### Error output
No Errors

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.0.0

### videojs version
what version of videojs does this occur with?
video.js 7.8.2

### Browsers
what browsers are affected? please include browser and version for each
* Chrome
* Microsoft Edge Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Windows 10, 1909

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
Unfortunately, I am unable to reproduce. I can see playback continue past 6 seconds.

**Comment by MusicPartner** [comment]
Try Microsoft Edge or Microsoft Edge (Chrome) latest 85.0

**Comment by gkatsev** [comment]
Looks like this is fixed in our main branch. I was able to reproduce when I installed Edge Canary. Stable versions work fine.
But when loading it via https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=%20https%3A%2F%2Fplayer.vimeo.com%2Fexternal%2F386726140.m3u8%3Fs%3D450453ba93a66c95b82c68966e2f82b9e44b3418&type=application%2Fx-mpegurl&keysystems= (which loads whatever is in latest branch) it seems to work fine.

**Comment by MusicPartner** [comment]
Thanks for quick response, works fine here also with the latest latest

**Comment by gkatsev** [comment]
Cool! We hope to get latest main released this week or early next week.
