### ISSUE TITLE
HLS with 302 redirect stuck pending after pre-roll ads.

### ISSUE THREAD

**Issue by danrossi** [videojs/http-streaming#888]
I have a custom pre-roll feature using the ads api. It fails to begin loading a redirect live HLS and stuck pending. I have tried multiple things. The HLS delivered with videojs is worse than hard coding the github version. However the only way to force it to play and load segments and reloading it twice after a timeout. 

pseudo code would act like

```
player.src(redirecthls);
player.src(adshls);

```

After calling

```
player.ads.endLinearAdMode();
```

I have to run a second call  to get it passed being stalled. And has to be 2 seconds after. 

```
 player.setTimeout(function () {
         player.src(player.ads.snapshot.sources);
         player.volume(1);
        }, 2000);
```

**Comment by gkatsev** [comment]
Are you using https://github.com/videojs/http-streaming#handlemanifestredirects?
Also, would you be able to provide a live, minimal, complete, verifiable exaple?

**Comment by danrossi** [comment]
Here is a test case. You can see the request failing with pending after the switch streamed has completed. 

https://dev.electroteque.org/httpstreaming/hlsswitch.html

And a real world case with an ads contrib plugin.  

https://dev.electroteque.org/httpstreaming/hlsads.html

impossible to debug this project but the work around is to re-request it after a timeout

```
 player.setTimeout(() => {
              player.src(player.ads.snapshot.sources);
              player.volume(1);
              player.play();
            }, 1000);
```

**Comment by danrossi** [comment]
The refactored config is now this I believe

```
html5: {
                      vhs: {
                        handleManifestRedirects: true,
                        overrideNative: true
                      }
                    },
```

**Comment by danrossi** [comment]
Any ideas ? my test shows the bug. it fails to load.

**Comment by danrossi** [comment]
Is this test clear enough ?

**Comment by gkatsev** [comment]
Yeah, I can reproduce it in your example. Looked at it again. I think the issue is your redirect server. Seems like the redirect sometimes doesn't return anything. When I hardcoded the URL that the redirect was pointing at everything worked fine.

**Comment by danrossi** [comment]
They said it used to work before. Chrome sits there with a pending request. I have to make a second call to bring up manifests and begin downloading segments. It fails at loading the master then I think. Is that the server not returning with a response ?

**Comment by gkatsev** [comment]
As far as I can tell, this is an issue with the redirect server. We use ads elsewhere, and they work and if I use different URLs it works fine as well.

**Comment by danrossi** [comment]
It's not related to ads, but when loading a different manifest as per the tests. Its a wowza redirect server so they have to ask them about it. They claimed it was working before then suddenly stopped loading. Its a live load balancer redirect.

**Comment by danrossi** [comment]
Have you tested any redirects loading new files ? If not I will have to setup another test case with a redirect url in nginx not wowza.  Im not sure why a second call to load works then. 

Is there a url resolving option as the redirect hostname can be loaded first to build the filename with.

**Comment by gkatsev** [comment]
Using your URL, often setting the source really soon after doesn't work. Need to wait a few seconds before it works.

**Comment by danrossi** [comment]
I put in a timeout after the second clip has ended and still pending. Then after a while the status is "cancelled". Is it that wowza service ? Is there another redirect server test to confirm ?

https://dev.electroteque.org/httpstreaming/hlsswitch.html

**Comment by danrossi** [comment]
It's a problem with wowza load balancer redirects. Using nginx redirects its loading. Sorry about that

https://dev.electroteque.org/httpstreaming/hlsswitch.html

**Comment by danrossi** [comment]
I just found a middleware can help do resolving for the wowza redirect. It has an option to return just the edge host. Which can be used for building a source out of.
