### ISSUE TITLE
IE - Videojs player page becomes not responding after minimize and 20 minutes played.

### ISSUE THREAD

**Issue by dovelive** [videojs/http-streaming#891]
## Description and Steps to reproduce
Open videojs test page on IE. https://videojs.github.io/http-streaming/
Start to play the stream and minimize the IE.
And about 20 minutes(maybe take longer according to the case) later, I would find that IE became not responding status.
And I found that VM memory usage became almost 1.5G.

### Expected
Meanwhile jwplayer works fine in that case.
https://www.jwplayer.com/developers/web-player-demos/live-streaming/

### videojs-http-streaming version
videojs-http-streaming 1.13.3

### videojs version
video.js 7.8.2

### Browsers
IE 11

### Platforms
Windows 10
*

**Comment by gkatsev** [comment]
This is likely fixed with Video.js 7.9.1 release.
