### ISSUE TITLE
Can not play video HLS on Samsung TV 2020 Premium

### ISSUE THREAD

**Issue by luuthibaochau** [videojs/http-streaming#892]
## Description
I can not play video on Samsung TV 2020 Premium. Have anybody gotten the same issue as me ? Could you please to share your solution to resolve it ? Thanks so much 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Init with config options 
  var options = {
      html5: {
        nativeCaptions: false,
        hls: {
          overrideNative: true
        }
      }
    }
2. Set up player and then play when ready 

### Expected
Can play normal on Samsung TV 2020 Premium 

## Additional Information
Reference the link for video specification https://developer.samsung.com/smarttv/develop/specifications/media-specifications/2020-tv-video-specifications.html 

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.12.2

### videojs version
what version of videojs does this occur with?
video.js 7.7.5

### Browsers
Use Chromium version M69 

### Platforms
Web application on Tizen OS 5.5

### Other Plugins
Use with other plugins :  videojs-contrib-ads, videojs-ima, videojs-contrib-dash

**Comment by gkatsev** [comment]
Any errors showing up? Have you tried the latest Video.js? Unfortunately, we may not be able to help debug because we do not have access to a 2020 samsung TV at the moment.
