### ISSUE TITLE
HLS VOD buffer

### ISSUE THREAD

**Issue by popler** [videojs/http-streaming#898]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

### Expected
Option to set buffer length in sec as in hls.js plugin.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.13

### videojs version
7.8.1

### Browsers
All

**Comment by gkatsev** [comment]
We do have it but do not recommend changing the value. Can be done by setting `videojs.Hls.GOAL_BUFFER_LENGTH` or `videojs.Hls.MAX_GOAL_BUFFER_LENGTH` (and with VHS 2, it will be `videojs.Vhs.GOAL_BUFFER_LENGTH`).
