### ISSUE TITLE
Not playing with encrypted hls source

### ISSUE THREAD

**Issue by saffari-m** [videojs/http-streaming#900]
## Description
Hi.
I'm using video.js player for playing hls stream, we use the encrypted hls stream tech.
When I try to play videos on TV or older browser, I catch error ``` TypeError: 'undefined' is not a function (evaluating 'ArrayBuffer.isView(r)') ```. So I added a polyfill library(__core-js__,..) to my project, but this error still exists.

I try to test my video player with other hls stream source and I found this issue when happening I use encrypted hls stream, non-encrypted hls source is ok.

is there any idea for solving that?

### Error output
‍‍‍```TypeError: 'undefined' is not a function (evaluating 'ArrayBuffer.isView(r)```

### videojs-http-streaming version
videojs-http-streaming 1.13.2

### videojs version
video.js 7.8.3

### Browsers
1. Mozilla/5.0(SMART-TV;Linux; Tizen 2.4.0) AppleWebkit/538.1 (KHTML,like Gecko) SamsungBrowser/1.1 TV Safari/538.1
2. Old Browsers

**Comment by gkatsev** [comment]
That's surprising that it still breaks after adding the polyfill. Make sure that the polyfill is included on the page before Video.js is loaded.
