### ISSUE TITLE
cuechange event is not fired on IOS device

### ISSUE THREAD

**Issue by ChandrakantGupta** [videojs/http-streaming#907]
cuechange event is not fired on IOS device

## Description
https://jsbin.com/yovilip/edit?html,output

### Expected
cuechange event must fire on IOS devices

### Error output
cuechange event do not fire on IOS devices

### videojs-http-streaming version

videojs-http-streaming v1.13.3

### videojs version

video.js 7

### Browsers
safari v13, chrome 83.0.4103.88
*

### Platforms
IOS 
*

*

**Comment by markquezada** [comment]
@ChandrakantGupta did you ever discover anything more about why this happens? Think I'm running into something similar.
