### ISSUE TITLE
Transcoded dash file using AWS Media Convert isn't working to play

### ISSUE THREAD

**Issue by Sujin1135** [videojs/http-streaming#909]
## Description
Transcoded mpeg dash(.mpd) file isn't working to play. but It's working If I use 'videojs-contrib-dash'. However, I want to use 'http-streaming' and It's working properly. because http-streaming provides to play HLS / Dash and use 'vediojs-contrib-eme'
Please give me a prompt reply. Thank you.

## Sources
Sample file: https://mz-cm-transcoding-output.s3.amazonaws.com/mz-cm-v1/assets/1594811871kcn9t7hw/mpd/BLACKPINK - ‘Kill This Love’ 0414 SBS Inkigayo (1).mpd

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play the sample file as above.
2. Check working to play.

### Expected
It's playing sample video

### Error output
No error printing

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
I knew that videojs-http-streaming is imported from videojs.js.

### videojs version
what version of videojs does this occur with?
video.js 7.8.3

### Browsers
what browsers are affected? please include browser and version for each
Chrome 84

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Windows 10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
The URL provided isn't URI encoded and therefore won't work. Also, the stream is DRMed, but a license URL isn't provided in the manifest. Therefore, even the reference dash.js player doesn't play the stream.
In addition, unfortunately, we don't support getting the license and keys from inside the manifest and it must be provided externally.

**Comment by Sujin1135** [comment]
Sorry about it. It was invalid URL and I give you valid test URL.

link: https://mz-cm-transcoding-output.s3.ap-northeast-2.amazonaws.com/mz-cm-v1/assets/1595553649kczjg3e7/Dog.mpd

Please give me a prompt reply. Thank you.

**Comment by gkatsev** [comment]
Looks like you're using SIDX, it's possible that it's something SIDX related that we don't support yet (like https://github.com/videojs/mux.js/pull/310)

**Comment by Sujin1135** [comment]
@gkatsev 
Thanks for your answer.

I just checked the above pull request([videojs/mux.js#310](https://github.com/videojs/mux.js/pull/310))
Can I know when It'll be supported?

**Comment by brandonocasey** [comment]
@Sujin1135 I am working on resolving this issue. I do see your source play with the mux.js change that has been linked. I think we will be able to get the change out soon. Would you mind if we re-host `https://mz-cm-transcoding-output.s3.ap-northeast-2.amazonaws.com/mz-cm-v1/assets/1595553649kczjg3e7/Dog.mpd` on our own servers so that we can add it to our unit tests so that we don't break things in the future?

**Comment by Sujin1135** [comment]
@brandonocasey 
Yes, thank you in advance that you'll solve this problem.
good luck!
