### ISSUE TITLE
Playback cannot continue. No available working or supported playlists.

### ISSUE THREAD

**Issue by DispatchCommit** [videojs/http-streaming#910]
## Description
updated to http-streaming 2.x and I'm having an issue where files that previously would play in video.js are now showing an error. Granted, there is an issue with the HLS stream not containing any video stream data, but previously this type of situation  would just show the cover image for the playerand play the audio only. Now there is an error shown / thrown and no audio will play. When attempting to open in VLC, the same occurs, no video, just a black screen, but audio *will* play. Codec info will show a video stream is defined and exists at a resolution, but will show 0 bytes of data incoming. Audio will show correctly.

Here is the output when loading this on https://videojs-http-streaming.netlify.app/?debug=true&autoplay=true&muted=false&minified=true&liveui=true&partial=false

![image](https://user-images.githubusercontent.com/45262335/87762589-3c766480-c7c8-11ea-9349-44855306d595.png)

Now I was able to walk the streamer through configuring OBS to use profile: `high` / tune: `zerolatency` and setting the keyframes to `2`, and for some reason this issue appears to always show up when OBS is in simple mode, and profile / tune are set to `(None)`, but this is easy enough to work around and instruct streamers to modify. 

The main question / concern I have is that previously, these streams, while technically "broken" at least allowed audio to be played and did not appear as an immediate error, but now they do. Is this intended?

I also noticed this error message: `message:
```js
blacklistDuration: Infinity
Video found in segment when we expected only audio. We can't switch to a stream with video from an audio only stream. To get rid of this message, please add codec information to the manifest."
__proto__: Object
```

And it is correct in that my current m3u8 files do *not* output any codec information. 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:8952
#EXT-X-TARGETDURATION:2
#EXTINF:2.000,
1594973022638.ts
#EXTINF:2.000,
1594973024684.ts
#EXTINF:2.000,
1594973026695.ts
...
```

I'm mostly concerned / curious as to why this no long is functional, when it previously was. Though it would seem that the solution is to simply add codec info to the m3u8 file? Sadly I cannot figure out how to reproduce this type of stream issue with my own version of OBS studio, but it's an error I've seen users encounter a number of times that I cannot immediately and simply resolve automatically.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
"@videojs/http-streaming": "^2.0.0",
videojs-http-streaming 2.0.0

### videojs version
what version of videojs does this occur with?
video.js 7.9.1

### Browsers
Chrome & Firefox both tested, both same behavior / issue.

### Platforms
tested on win 10

**Comment by DispatchCommit** [comment]
Codec info:
![image](https://user-images.githubusercontent.com/45262335/87766765-85311c00-c7ce-11ea-8492-97456325b6ea.png)

(personal note: should read through #762 to see if that may have affected this)

**Comment by gkatsev** [comment]
One thing to try is creating a main manifest with codec information that links to that manifest and see whether that ends up working.

**Comment by gkatsev** [comment]
This may be an issue where we see an audio only segment and only create an audio source buffer and then can't switch to an audio and video segment.
We could help more with a sample stream but trying to wrap it in a master manifest with codec info could help.

**Comment by JeppeTh** [comment]
I have similar issue on Samsung TV Emulator - in older version HLS streams played fine (with audio) - now I get this error or it just hangs on stalled.
On actual Samsung device it previously didn't work at all though - seems all playlist were blacklisted or similar - then hanging on stalled. With new version I get like 2 seconds of video but without audio - then just hangs - no error...

**Comment by MycujooMats** [comment]
We are seeing a similar issue, which is reproducible in the https://videojs-http-streaming.netlify.app demo page. Try it with this stream url: https://playlists.mycujoo.football/eu/ckjvdj4k4f10e0gdrn9322dgm/master.m3u8

For comparison, it can be played fine in other players, e.g. Akamai's demo player: https://players.akamai.com/players/hlsjs?streamUrl=https%3A%2F%2Fplaylists.mycujoo.football%2Feu%2Fckjvdj4k4f10e0gdrn9322dgm%2Fmaster.m3u8

**Comment by gkatsev** [comment]
@video-archivist-bot save VEeVjJ

**Comment by z0mb1ek** [comment]
Same error with Chrome on MacOS

**Comment by McMac** [comment]
This video works on my iPad : https://invidio.xamh.de/watch?v=0dFz10R529g but fails with the same error message on my own hosted instance?!

**Comment by alxjzx100** [comment]
I have the same issue.

DASH is set to auto. Some videos shows error "Playback cannot continue. No available working or supported playlists."

Selfhosted instance in docker. 
Client - MacOs Safari Version 16.0 (17614.1.25.9.10, 17614)

**Comment by luhuaei** [comment]
I have encountered this problem too. Has anyone solved this issue? Thank you.

**Comment by McMac** [comment]
Why is this closed? What did I miss? Point being, if dash fails I need to go into settings and chance it for the entire invidiuous instance instead of just for one video?!?
