### ISSUE TITLE
[Challenging Issue] Increased likelihood of stalling with HLS protocol with large timestamp gap

### ISSUE THREAD

**Issue by suggestedfixes** [videojs/http-streaming#914]
Here is a bit of background. We are recording motion from devices and uploading them to cloud. When we wanted to playback recorded video, we then stream the video with HLS LIVE protocol, the version without the endlist tag.

After some investigation, it does seem like with footage of large discontinuities, the "duration" property does seem to bias towards a larger value. This might have affected the ability for the player to determine whether the buffer is full.

We also compared videojs with hls.js. It does seem like hls.js has a lower likelihood of stalling.

Here is a sample m3u8 list format, note the large gap between 50min:06s to 51min:04s, or jump for 54:58 to 25:08 of next hour.
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:13
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-DISCONTINUITY
#EXT-X-MAP:URI=URI
mber=1"
#EXT-X-PROGRAM-DATE-TIME:2020-07-20T12:50:01.408Z
#EXTINF:5.0,
URI
mber=1
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2020-07-20T12:50:06.408Z
#EXTINF:3.3,
URI
mber=1
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2020-07-20T12:51:04.408Z
#EXTINF:5.0,
URI
mber=1
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2020-07-20T12:51:09.408Z
#EXTINF:3.95,
URI
mber=1
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2020-07-20T12:54:53.408Z
#EXTINF:5.0,
URI
mber=1
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2020-07-20T12:54:58.408Z
#EXTINF:2.9,
URI
mber=1
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2020-07-20T13:25:08.408Z

**Comment by gkatsev** [comment]
How does the stream look if you run it in https://videojs-http-streaming.netlify.app/?

**Comment by suggestedfixes** [comment]
Also confirmed stalls

**Comment by gkatsev** [comment]
Unfortunately, we can't really help without a live playlist for us to try.

**Comment by suggestedfixes** [comment]
Still a thank you for asking for more information!

**Comment by gkatsev** [comment]
We have an internal stream that showcases the same issue. We'll probably work on it at some point. Sorry I don't have a better answer right now.
