### ISSUE TITLE
[Question] What is the best way to play LIVE like VOD mode?

### ISSUE THREAD

**Issue by suggestedfixes** [videojs/http-streaming#919]
We are streaming past footage at live mode.
There are several problems we have to tackle:
- When we search for a time start time, live mode tends to jump to the end of the playlist.
- When we pause the video for a few seconds then play, since the playlist is updating in the background, play will not resume at where we are at.
- At live mode, there is a certain probability that the player will skip to the end of the playlist.

Essentially we want the behavior of VOD mode, with the added benefit of live mode being able to update playlist automatically.
What would be a recommended approach?

**Comment by gkatsev** [comment]
For the UI, you can able `liveui: true` on the player to show the progress control for live playback.
To start at the beginning you can seek to the seekable start time.
The other things are something that we'll need to address, likely as part of https://github.com/videojs/http-streaming/issues/310, when we get to it.

**Comment by suggestedfixes** [comment]
Is there an easy method to temporarily pause playlist loading and segment loading when pausing the player?

**Comment by gkatsev** [comment]
There's no way to do that right now.

**Comment by suggestedfixes** [comment]
Thanks for taking the time for the answers!
