### ISSUE TITLE
On Edge HLS playback stops after few seconds

### ISSUE THREAD

**Issue by nerdbeere** [videojs/http-streaming#920]
## Description
On the new chromium-based Edge (Version 84.0.522.48, tested in macOS and Windows 10) certain HLS Streams stop playback after a few seconds.
This is reproducible on https://videojs.github.io/http-streaming/ with the following URL: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

## Sources
So far I could only reproduce this issue with streams from bitmovin:

https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Open https://videojs.github.io/http-streaming/
2. Paste one of the test urls from above
3. Start playback

Playback stops and leads to endless loading spinner after a few seconds.

### Expected
Playback of bitmovin HLS streams play in Edge as they do in other browsers.

### Error output
No errors on console

### videojs-http-streaming version
Latest from https://videojs.github.io/http-streaming/ 

### Browsers
what browsers are affected? please include browser and version for each
* Edge Version 84.0.522.48 (Official build) (64-bit)

### Platforms
* macOS
* Windows 10

**Comment by olysyuk** [comment]
It appears that player never loads second segment of audio. 
![image](https://user-images.githubusercontent.com/1804266/88908089-20f86880-d262-11ea-86ae-25ecbd366dde.png)

**Comment by olysyuk** [comment]
It appears to be not only bitmovin issue, this stream stops playing as well https://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/elephantsdream2.smil/playlist.m3u

**Comment by klipstein** [comment]
We were able to fix the issue by setting: `{ html5: { nativeAudioTracks: false }}`

**Comment by gkatsev** [comment]
Looks liek a similar issue to https://github.com/videojs/video.js/issues/6762 and the workaround seems to be to make sure that overrideNative is set
