### ISSUE TITLE
m3u8 contains both audio-only and audio-video streams, how can we switch btw them when bandwidth changes?

### ISSUE THREAD

**Issue by yxwu** [videojs/http-streaming#922]
I have m3u8 as below, where stream_0.m3u8 is audio only, and stream_1.m3u8 is audio_video. 
My question is: when bandwidth changes, will videojs switch btw these two streams automatically? I tested again chrome and firefox, seems not able to.

```
#EXTM3U
#EXT-X-VERSION:3

#EXT-X-STREAM-INF:BANDWIDTH=70400
stream_0.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=370400
stream_1.m3u8
```

**Comment by gkatsev** [comment]
Unfortunately, right now we do not support switching from audio only to audio+video renditions.
Your best bet is to have a rendition with video that's basically a static image.
