### ISSUE TITLE
qualityLevels list doesn't get populated for HLS on iOS devices + MacOS/Safari

### ISSUE THREAD

**Issue by mrkos67** [videojs/http-streaming#930]
## Description
The qualityLevels list doesn't get updated with any quality levels from an HLS source on iOS devices and MacOS/Safari. As such, the "addqualitylevel" and "change" events never fire.

[reduced test case](https://dev.option5.net/CNCT/Megaphone/dev-stable/tests/videojs/)

### Expected
In the above test case, four buttons should be auto-generated next to the "quality:" label, one each for "1920", "960", "640", and "360". (See desktop/Chrome for working example). Console.log dumps function calls and lots of other info. 

### Error output
No errors.

### VideoJS + Plugins
* video.js : 7.7.6
* videojs-contrib-quality-levels: 2.0.9

### Affected Platforms/Browsers
* iOS/Safari
* iOS/Chrome
* MacOS/Safari

**Comment by gkatsev** [comment]
This is expected. quality-levelss only works with our playback engine. Unfortunately, with native HLS playback, there's no way to see or control the different renditions.
For desktop safari, you can overrideNative to use our playback, but we don't recommend it. It isn't possible to use our playback engine on iPhones.

**Comment by mrkos67** [comment]
I guess I don't follow what that means exactly — the difference is between the playback engine and native playback — and why iOS/Safari can't use the playback engine.

**Comment by gkatsev** [comment]
So, internally, we use an API called (Media Source Extensions (MSE))[https://en.wikipedia.org/wiki/Media_Source_Extensions]. We then handle deciding which segments to download and use MSE to play those back. On iOS this API is not available.
For desktop Safari, we prefer letting the browser handle everything as Safari's HLS handling is the gold standard. Desktop Safari does have MSE, so, it's possible to have us handle downloading segments and use MSE for playback but we would still recommend against doing so.

**Comment by mrkos67** [comment]
Roger that. I was wondering if it had something to do with MSE (which I'm still not really sure what this is and why some browsers can use it and some don't).

So, because of MSE doesn't work on iOS, there's no way to program manual control of quality levels from DASH or HLS streams?

**Comment by gkatsev** [comment]
DASH won't work without MSE on iOS and that is why you can't see the list of quality levels on iOS.

MSE is basically only missing on iOS and older browsers.

**Comment by mjrox** [comment]
Has there been any progress in providing support for quality levels on iOS since 2020?
