### ISSUE TITLE
Add audio track manually

### ISSUE THREAD

**Issue by davidboutet** [videojs/http-streaming#935]
Hello, is there a way to add manually an audio track?

Im trying with this code:

```
var track = new videojs.AudioTrack({
    enabled: true,
    id: 'my-french-audio-track',
    kind: 'main',
    label: 'French',
    language: 'fr'
});

playerInstance.videoJsInstance.audioTracks().addTrack(track);
```

But nothing is added to the track list

Am I doing something wrong? or maybe it is just impossible to add a track manually
Thanks

**Comment by gkatsev** [comment]
Unfortunately, that isn't supported. The audio tracks are there from the HLS/DASH stream and we don't support adding audio tracks out of band.

**Comment by FireMasterK** [comment]
Can't we construct an HLS/DASH stream with the audio track and video file?
