### ISSUE TITLE
Define upper limit for bandwidth while auto-switching

### ISSUE THREAD

**Issue by fawaztahir** [videojs/http-streaming#941]
My case is I need to serve at max 720p on web-browsers while serving 1080p on native mobile apps for same content. Is it possible to provide an upper limit to VHS so it wouldn't go higher it?

**Comment by gkatsev** [comment]
You can use the [representations API](https://github.com/videojs/http-streaming#vhsrepresentations) or the https://github.com/videojs/videojs-contrib-quality-levels plugin to turn off the renditions that are higher than 720p but still have all the other renditions enabled.

**Comment by fawaztahir** [comment]
Thanks. I tried this on Safari but it doesn't populate the object like in example. Is this due the native playback in Safari?

**Comment by mister-ben** [comment]
Correct, you can't control which rendition plays with native playback.
