### ISSUE TITLE
[Question] Should Bandwidth defined in vhsstats.bandwitdth = bitrate?

### ISSUE THREAD

**Issue by tokidoki11** [videojs/http-streaming#945]
I send hls video stream via wowza streaming server.
The sender send video of small 500Kbps bitrate stream, I would see the bandwidth fluctuates from a couple of Mbps to tens of Mbps.

If I'm wrong, is there any suitable way to count for one?

**Comment by gkatsev** [comment]
That value is the rate bits per second of the last downloaded segment. See https://github.com/videojs/http-streaming#vhsstats.

**Comment by tokidoki11** [comment]
Sorry, could you elaborate more in easier way? or anything to be read is very appreciated

do it have connection with the video bitrate itself?
