### ISSUE TITLE
How to detect if decryption has failed

### ISSUE THREAD

**Issue by samueleastdev** [videojs/http-streaming#951]
## Description

I would like to know if there is a way to detect if the decryption process for an encrypted stream has failed.

Currently, the player just keeps trying instead of failing

I can do this.
~~~
player.tech().on('usage', function(e){
                    
                    console.log(e.name);

                    if(e.name === 'hls-rendition-blacklisted'){

                        player.pause();
                        player.error({
                            code: 7,
                            message: 'hls error'
                        });

                    }  
                
});
~~~

But I am worried there will be other user cases where a playlist gets blacklisted.

I am looking for an error event that detects if the decryption key is wrong so I can display a message to a user?

Thanks

**Comment by gkatsev** [comment]
That can usage event definitely happen for a whole host of reasons. Unfortunately, I'm not sure we currently provide a way to know exactly why a stream or a rendition failed.
