### ISSUE TITLE
segements are downloaded from orign domain instead of host domain

### ISSUE THREAD

**Issue by prashantham** [videojs/http-streaming#955]
## Description
I have a m3u8 file on aws cloudfront.  The player is able to download the manifest. But subsequent requests are NOT downloaded from host cloudfront but from the origin domain where the videojs is hosted. 

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
All segments to be downloaded from host domain.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.1.0. Tested on https://videojs.github.io/http-streaming as well. 

### videojs version
what version of videojs does this occur with?
video.js 7.0

### Browsers
what browsers are affected? please include browser and version for each
*

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by gkatsev** [comment]
That's weird, I don't think we've ever seen that before. We've definitely had issues where if a manifest had a redirect set up we wouldn't handle it (which we have an option (handleManifestRedirect) for which in VHS 2.2 we turned on by default).
Can you share a sample stream? If you can't share it publicly, can you share it privately over slack?
