### ISSUE TITLE
[Question] Does the Segment Loader have a retry mechanism?

### ISSUE THREAD

**Issue by suggestedfixes** [videojs/http-streaming#961]
We often found that with slow network and our custom playlist ~ 1mbps from chrome emulation, (5 second duration segments, 600kB per segment). The first segment download tends to fail. When the first segment fails due to cancelation. The player stalls.
Our current workaround is to skip this failed cancelation segment and seek past this segment. We also suspect that a lot of the discontinuities are due to segment download timeouts and cancelations.

Call stack for the failed segment
![image](https://user-images.githubusercontent.com/61390265/94574866-73d1aa80-0228-11eb-94a6-894b01c5b1fd.png)

**Comment by gkatsev** [comment]
I think this will be greatly helped if not fully resolved by the PR I just submitted #978.
