### ISSUE TITLE
HLS Playback init sometimes leave the video loading only (media is downloading)

### ISSUE THREAD

**Issue by tokidoki11** [videojs/http-streaming#972]
## Description
I have videojs instance with live http stream, when the stream ends, I will send an error to the instance an error message.
Meanwhile, I will keep on checking if the streaming is coming back to the server or not.

If the stream is there, I will run `player.dispose` and recreate the the instance.
How I create the instance is that I will create a video tag using document api, and run the `videojs` function to the tag.

Sometimes I find the player with the loading spinner keep on spinning, I can see the media is being downloaded in the background.

**Further check, i can see the `tech().hls.stats.buffered`  is being empty array but
`(tech as any).hls.playlists.media()` is returning something**

I'm very sure that the player is new one since calling `player.id()` giving me different ID everytime

## Sources
No code reproduce but find the screenshot below
<img width="748" alt="スクリーンショット 2020-10-09 14 01 25" src="https://user-images.githubusercontent.com/7564844/95545141-00097c00-0a38-11eb-9aec-51050e20834d.png">

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. create a video tag
2.  create instance on the video tag
3. dispose the instance (will erase the tag as well)
4. create another video tag
5. create instance on new video tag

repeat until the problem happens

### Expected
The video should be loading

### Error output
Sometimes  this warning popups, but i can be very sure it is not the cause
since sometimes even it shows, the video is running well
```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the only playlist.
```

### videojs-http-streaming version
bundled with video.js 7.8.4

### videojs version
what version of videojs does this occur with?
video.js 7.8.4

### Browsers
Tested on chrome and firefox

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* MacOS X

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* https://github.com/brightcove/videojs-contextmenu-ui

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* nuxt js

**Comment by gkatsev** [comment]
This definitely seems possible that we aren't doing a great job with disposing things.
