### ISSUE TITLE
cacheEncryptionKeys has no effect with subtitle streams

### ISSUE THREAD

**Issue by phloxic** [videojs/http-streaming#973]
## Description
Reduced test case can be found [here](https://phloxic.productions/test/videojs/cachevttkeys.html).

## Steps to reproduce

1. AES encrypted HLS source with subtitle stream
2. set `cacheEncryptionKeys: true`
3. play and monitor GETting of key files

### Results
Keys for video renditions are fetched once, key(s) for subtitles are re-fetched and not cached.
### Expected
Key files for subtitle streams should be cached too.

**Comment by blacktrash** [comment]
Still happening with 7.11.1:
<img width="454" alt="Screen Shot 2020-12-31 at 15 22 54" src="https://user-images.githubusercontent.com/168338/103416066-c5b60380-4b7c-11eb-9895-fda63308c064.png">

**Comment by blacktrash** [comment]
Could the "outdated" label be removed? imho the issue is not outdated. Thank you.

**Comment by blacktrash** [comment]
oh, thank you bot

**Comment by gkatsev** [comment]
Looks like a long time ago I wrote a response to this, and then this got lost in the churn. Thankfully, Firefox saved my response, which is posted below. A PR would be helpful, as it's clearly something we're unlikely to get to any time soon.

----

Looks like our [VTT Segment Loader](https://github.com/videojs/http-streaming/blob/main/src/vtt-segment-loader.js) isn't aware of that option, but our [regular segment loader is](https://github.com/videojs/http-streaming/blob/main/src/segment-loader.js). It should be relatively straight forward to add.

**Comment by phloxic** [comment]
Wanted to look into this anyway, thanks for the nudge. Will have a go.

For the time being I had brushed this under the carpet somewhat by shamelessly increasing targetduration for vtt.

**Comment by phloxic** [comment]
unstale

**Comment by venomone** [comment]
Any update onto this? Would also interest me to have this fixed ...

**Comment by phloxic** [comment]
@venomone - this is fixed I believe.

**Comment by phloxic** [comment]
Fixed via 66a5b17de192eee5d23fadba6a21f6a54f0eb34c
