### ISSUE TITLE
Disable/enable auto quality switching?

### ISSUE THREAD

**Issue by Zebraslive** [videojs/http-streaming#974]
I want to disable auto quality switching and re-enable later, is there an option for this?

**Comment by gkatsev** [comment]
You can do so by either overriding the [selectPlaylist](https://github.com/videojs/http-streaming#vhsselectplaylist), using the [representations API](https://github.com/videojs/http-streaming#vhsrepresentations), or even better using the [quality levels api](https://github.com/videojs/videojs-contrib-quality-levels) to turn off all but a single rendition.

**Comment by gsimko** [comment]
@gkatsev what is the proper way of overriding selectPlaylist? If I wait for player.ready() so that player.tech() is available, I already miss the selection. I'd need to somehow override selectPlaylist before creating the player but could not figure out a way.
