### ISSUE TITLE
It is not working with Apache Server 2.4

### ISSUE THREAD

**Issue by larryxia-ddl** [videojs/http-streaming#990]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
We have a HLS server with Apache web server. When I use Native HLS playback extension it works in Chrome. But when I changed to video.js, it did not work. I got this error message. "The media could not be loaded, either because the server or network failed or because the format is not supported.". 

In the developer tool, I can see it failed to load the m3u8 file. the response section is "failed to load response data". but in the header section, I saw status is 200, and from apache log, I also saw the response is 200. 

here is page loaded: 

hls%20-%20Copy.html
--
video-js.css
video.js
videojs-http-streaming.js
video-js.css
video.js
videojs-http-streaming.js
data:application/fo…
blob:null/baa399e1-74e2-431e-866f-6422c0c394f6
blob:null/1325a810-76de-4136-a4d6-620636ae33ed
blob:null/28506a07-356b-4790-ba02-586fdf3f1f11
blob:null/a1a23501-68d3-4a29-aac2-8f40ee0ac475
blob:null/742be7a9-ad7d-426b-9970-0231dc758748
session0.m3u8

The M3u8 failed. 

Here is the response header of the step of download M3u8 file: 

HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Length: 185
Content-Type: application/x-mpegURL
Date: Wed, 04 Nov 2020 21:25:02 GMT
Etag: W/"b9-5b34e9cb807e6"
Last-Modified: Wed, 04 Nov 2020 21:25:01 GMT
Server: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.10

Here is the request header: 
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: xxxx
If-Modified-Since: Wed, 04 Nov 2020 21:24:49 GMT
If-None-Match: W/"b9-5b34e9bfd6e99"
Origin: null
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. download Apache web server from http://www.appservnetwork.com/
2. set up HLS folder under www root. 
3.Streaming to HLS folder 
4. view HLS from video.js following the sample. 

<body>
  <h1>Video.js Example Embed</h1>

  <video-js id="my_video_1" class="vjs-default-skin" controls preload="auto" width="640" height="268">
    <source src="http://IP/hls/session0.m3u8" type="application/x-mpegURL">
  </video-js>
  
  <script src="https://unpkg.com/video.js/dist/video.js"></script>
  <script src="https://unpkg.com/@videojs/http-streaming/dist/videojs-http-streaming.js"></script>
  
  <script>
    var player = videojs('my_video_1');
  </script>
  

### Expected
Please describe what you expected to happen that did not happen in the description.
If I try with some sample HLS site, it works fine, but it is not working with our HLS server. But out HLS server with with Native HLS playback extension in Chrome. 

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:
The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming x.y.z

### videojs version
what version of videojs does this occur with?
video.js x.y.z

### Browsers
what browsers are affected? please include browser and version for each
Chrome.  

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Windows 10, Chrome and Apache server 2.4

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
NO

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
NO

**Comment by larryxia-ddl** [comment]
I have figured out how to solve this issue. It works after we turned cross-origin resource sharing in Apache . Native HLS Playback use HLS.js 0.12.4 which don't check the status of XHR request. so it works. 

Now we can close this ticket.

**Comment by gkatsev** [comment]
Given that it's an extension, it likely has different security implications compared to something running in the page itself. Hls.js outside of the plugin wouldn't work without CORS either, see our [hosting considerations](https://github.com/videojs/http-streaming#hosting-considerations) for more info.
