### ISSUE TITLE
hlscmof urls not playing in videojs

### ISSUE THREAD

**Issue by Sushmahp95** [videojs/http-streaming#991]
Description:
I am using videojs player to play hls and dash urls. But when i try to play drm encrypted hlscmf url, video is not playing , it is keep on loading and there is no errors also in console. For dash url, it is working fine, We are using widwine licenced token to encrypt the content. But when i try to play same url in bitmovin player , it is playing. I am not getting what is the issue. i am new to videojs. Kindly help me in solving this issue. 

Expected:
Encrypted hlscmof url should play in videojs player.

Actual:
hlscmof urls not playing in videojs

Error Output:
No errors are showing in console

Versions:
Videojs: 7.6.6
videojs-contrib-eme: 3.6.0

Browsers:
Chrome(86.0.4240.111)

OS:
Windows(10, 64 bit)

**Comment by gkatsev** [comment]
It's possible that you're not configuring contrib-eme correctly. Would you be able to share a reduced test case? It'll be incredibly hard to help you out without one.
