### ISSUE TITLE
Player infinite buffering with HLS stream

### ISSUE THREAD

**Issue by Gregory-Gerard** [videojs/http-streaming#999]
Hello :smile: 

## Description
For information, my stream is a live stream (24/24) coming from a nginx server with the rtmp module. The different HLS variants don't always seem to be synchronized with different `EXT-X-MEDIA-SEQUENCE`, but according to specifications, client should not using this variable to sync between variant?

When I change quality (or variant) or the quality changes automatically depending on the size of the player or the bandwidth, the player starts loading the next segments indefinitely without ever playing them.

It seems to happen only when I'm in "live" mode, if I go back a bit forward using the liveui, the quality change happens without any problem.

When the player tries to load the other segments indefinitely, if I click on the live button to sync again, it starts again  (you can check my video in additional information, it's easier to show than explaining).

## Sources
https://videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&minified=false&liveui=true&partial=false&url=https%3A%2F%2Flive.tvradio-pitchoun.fr%2Fhls%2Flive.m3u8&type=application%2Fvnd.apple.mpegurl&keysystems=&buffer-water=false
or
https://live.tvradio-pitchoun.fr/hls/live.m3u8 this link should work as it's a 24/24 livestream.

_edit 2020-12-01: sorry live stream don't work anymore as i just added secure link module with nginx, please check the streamable link or tell me if it is necessary i will temporarily setup a test url for my live stream_

## Steps to reproduce

1. Load player in liveui mode
2. Be synced (in live mode with the red light on)
3. Change quality (1080p to 360p for example)

### Expected
Player should continue to play, or to recover after some seconds to load new variant, not after some minutes.

### Error output
No error.

## Additional Information
Here is a video capture of what's exactly happening : [https://streamable.com/p7e52p](https://streamable.com/p7e52p)

This problem seems not to appear on Firefox according to my tests.

### videojs-http-streaming version
* videojs-http-streaming 2.3.0

### videojs version
* video.js 7.8.2, 7.10.2, 7.11.0...

(seems not to occurs before 7.2.3)

### Browsers
* Chrome version 86.0.4240.193 (Build officiel) (64 bits)

### Platforms
* Ubuntu 20.04.1 LTS 64 bits
Intel® Core™ i7-4720HQ CPU @ 2.60GHz × 8 
NVIDIA Corporation GM204M [GeForce GTX 965M]

### Other Plugins
* videojs-contrib-quality-levels.js
* videojs-hls-quality-selector.js

### Other JavaScript
No.

Thanks :+1:

**Comment by gkatsev** [comment]
root cause is likely #1000.
